### ISSUE TITLE
Failed to install player; "The application encountered an unrecoverable error."

### ISSUE THREAD

**Issue by I-Have-An-Issue** [vinegarhq/vinegar#134]
Installed from AUR
CPU: Intel i5-10400F
Wine: wine-8.14 (Staging)

[vinegar.log](https://github.com/vinegarhq/vinegar/files/12502178/vinegar.log)
![Screenshot_2023-09-01_17-46-48](https://github.com/vinegarhq/vinegar/assets/34550332/562f67b6-8b4a-4faf-89a8-de25d22bc4cc)

**Comment by Thelolguy1** [comment]
Would you mind stating you distro and giving the Flatpak a try? Since the error is quite vague, it takes quite a lot of effort to narrow down the actual cause.

**Comment by Thelolguy1** [comment]
Additionally, since I know you're on the Discord, please send me a message in vinegar-developers or general, I usually get to those faster than the ones in here.

**Comment by I-Have-An-Issue** [comment]
> Would you mind stating you distro and giving the Flatpak a try? Since the error is quite vague, it takes quite a lot of effort to narrow down the actual cause.

I'm currently running a bastardized install of Artix Linux. I'll give flatpak a try and report back.

**Comment by I-Have-An-Issue** [comment]
Installing Vinegar with flatpak seems to have solved this issue, and I appear to be getting stable performance as well. I'll be closing this issue now.
