### ISSUE TITLE
How can i make roblox use my Rtx 3050

### ISSUE THREAD

**Issue by KennyDevT** [vinegarhq/vinegar#136]
Roblox just refuses to use the 3050 in my laptop and i can barely get 80 fps in arsenal

**Comment by Thelolguy1** [comment]
Please check your configuration and driver versions, DXVK should automatically switch to your dGPU by default.

Additionally, see the [article here](https://wiki.archlinux.org/title/PRIME) for more information about PRIME.

**Comment by KennyDevT** [comment]
I forgot to say I fixed it just by using the aur version but now my gpu usage stays at 40% In game hut in the menu its at 100%

**Comment by Thelolguy1** [comment]
In that case, it's likely functioning properly; Roblox won't use your GPU 100% all of the time.

**Comment by KennyDevT** [comment]
The problem is I'm still get very poor performance and seeing that roblox is only using 40% is not helping

**Comment by mr-sihc** [comment]
well, there's nothing vinegar can do...
You can try using a different renderer (explained on the vinegar website)
