### ISSUE TITLE
I can has Proton?

### ISSUE THREAD

**Issue by Hebgbs** [vinegarhq/vinegar#138]
Does Vinegar detect and use instances of Proton if Wine is unavailable? Before I even _bother_ attempting to run Roblox with Vinegar (since it's suppose to be issue-free for the most part), I want to know if it's possible without needing to install Wine, and using a copy which was built for Arch via the AUR.

I have this project built, I have Proton, can I avoid installing Wine? Seems weird, but I've avoided the need to install Flatpak and Wine up to this point and I wonder if I can keep it that way.

_Do mind_ I have no strict aversion to installing Wine, and if I took gaming on my machine a bit more seriously I would go through the bother of using Lutris for select titles with different hacks of Wine for better compatibility sake, but I'm looking to keep my installed packages minimal.

**Comment by Cristiandis** [comment]
Proton is only for steam game, use wine-ge instead if you want the patches

**Comment by Hebgbs** [comment]
> Proton is only for steam game, use wine-ge instead if you want the patches

_Huh?_ Ehm, I've ben able to run Windows executables through Steam before my guy. And there's a dedicated project for Proton prefix configuration called Protontricks which relies upon Winetricks (which relies upon Wine so then, what's the point?)

If you didn't know about any of that until now, then today you learned.

**Comment by Cristiandis** [comment]
Just use wine-ge you just making it harder for you

**Comment by Cristiandis** [comment]
> 

Vinegar creates its own wineprefix

**Comment by Hebgbs** [comment]
If I wanted to make it easy on myself I would boot into Windows.

**Comment by Hebgbs** [comment]
> > 
> 
> Vinegar creates its own wineprefix

Ah, didn't know that.

**Comment by Thelolguy1** [comment]
The suggestion is correct, wine-ge is identical to Proton and is designed for use with external applications. Set your wine-ge folder with the wineroot setting (see https://vinegarhq.github.io/Configuration/index.html for more details).

**Comment by Hebgbs** [comment]
I got it to launch with a directory symbolic link to an existing Steam Play prefix in `$HOME/.local/share/Steam/steamapps/compatdata` into `$HOME/.local/share/vinegar` as `prefix` and symlinking `wine`, `wine64`, `wine64-preloader` and `wineserver` from `$HOME/.local/share/Steam/steamapps/common/Proton\ -\ Experimental/files/bin` into `/usr/local/bin`.

_To be clear_ nobody should do this. But it's still fun to know I _can_ do it.

**Comment by mr-sihc** [comment]
you didn't know you could already do this?
bruh.
Anyway, install wine-ge/wine or you'll make yourself look like a fool when reporting issues
