### ISSUE TITLE
How to disable FPS indicator?

### ISSUE THREAD

**Issue by mak448a** [vinegarhq/vinegar#139]
How do I disable the FPS indicator in the top left corner?

**Comment by rockyamethyst** [comment]
```
[player.env]
DXVK_HUD = "0"
```
Should be this in the [configuration file](https://vinegarhq.github.io/Configuration/index.html), also please join the [discord server](https://discord.gg/dzdzZ6Pps2) for issues and questions like this, it's faster.

**Comment by mak448a** [comment]
Ok thanks!
