### ISSUE TITLE
How to change death sound?

### ISSUE THREAD

**Issue by mak448a** [vinegarhq/vinegar#140]

**Comment by Thelolguy1** [comment]
You can navigate to your Roblox folder in your prefix (either ```~/.var/app/io.github.vinegarhq/data/vinegar/prefix/vinegar/versions/**VERSIONIDHERE**/content/sounds``` or ```~/.data/vinegar/prefix/vinegar/versions/**VERSIONIDHERE**/content/sounds```) and change your ouch.ogg as necessary.

**Comment by apprehensions** [comment]
Alternatively, Vinegar has an overlay feature, which you can get the ouch.ogg and put it in the overlay directory for it to automatically be applied upon roblox installations.

https://vinegarhq.github.io/Configuration/tips-and-tricks/index.html#overlay

`~/.config/vinegar/overlay/content/sounds/ouch.ogg`

**Comment by tawnylure** [comment]
Or alternately if in neither path (which was the case for me) 
~/.local/share/vinegar/vinegar/versions/**VERSIONIDHERE**/content/sounds

Idk why it was their, but for anyone having issues above with the paths try this.
