### ISSUE TITLE
Reinstalled from source and flatpak still getting memory dump error's

### ISSUE THREAD

**Issue by StatixBolt** [vinegarhq/vinegar#143]
Arch Linux Latest
6.4.12-arch
Flatpack AUR and Source tested.

Same output no matter what I do, and arch doesn't have Wine 8.3. Also, I don't think Wine - GE is even there when installing from pak.
I even tried Grape-juice and cork same issue persists.

Also, I love salt and vinegar chips.
![ss](https://github.com/vinegarhq/vinegar/assets/108201239/bc5d802d-c6d1-4c80-b76a-194541df3ca9)

**Comment by Thelolguy1** [comment]
It is possible that your processor does not support AVX. What CPU do you have?

**Comment by StatixBolt** [comment]
For fun a Celeron N4020, I've always been able to play though. Is this a Roblox issue right now??

I heard it's even needed for cyberpunk now.

**Comment by Thelolguy1** [comment]
It wasn't required pre-Byfron.

**Comment by mr-sihc** [comment]
LOL an INTEL cpu from 2019 that doesn't have AVX, Runs in 1.1GHz and has only 2 cores.

you should've looked more at what piece of crap you bought...

(why would intel even make such shitty CPU's in 2019?!?!?!?)
