### ISSUE TITLE
Vinegar starts, but cannot connect

### ISSUE THREAD

**Issue by cacilhas** [vinegarhq/vinegar#144]
- Distro: **Arch Linux**
- Kernel: **`6.4.12-arch1-1`**
- Wine: **`wine-8.14`**
- CPU: **Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz**
- GPU: **NVIDIA GeForce RTX 4070 Ti/PCIe/SSE2**
- Installation method: both **AUR** and **Flatpak**, same issue
- Vinegar version: **1.4.1** (from AUR it’s **1.4.1-1**)

When I try to log in, I got the following error message:

```
Error [GENERAL |  | OpenXR-Loader] : RuntimeManifestFile::FindManifestFiles - failed to find active runtime file in registry
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - unknown error
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - failed to load a runtime
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed to find default runtime with RuntimeInterface::LoadRuntime()
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed querying extension properties
```

**Comment by apprehensions** [comment]
This error is harmless.

**Comment by Thelolguy1** [comment]
Please be aware that the login screen on the app version of Roblox is broken right now. Starting a game from the browser will work, however.
