### ISSUE TITLE
A bunch of Roblox Studio's UI flashes and breaks [Seizure Warning]

### ISSUE THREAD

**Issue by RedrcknRbn** [vinegarhq/vinegar#145]
Device Specifications:
Arch Linux
KDE Plasma 5
Xorg11
Nvidia GTX 1070
Intel(R) Core(TM) i9-9900K CPU
Two sticks of 8GB DDRM4

Some UI Elements of Roblox Studio seem to flash with screen tearing

https://github.com/vinegarhq/vinegar/assets/63996530/4d67fbe0-8d78-49c4-af66-22f28993b0c0

**Comment by Noted-Jrelvas** [comment]
Hey. This is an issue with the DX11+D3D/OpenGL renderers on studio. I'm afraid there's not much that can be done to fix them without the help of upstream.

However, there's good news! If your wine build has the childwindow patch, then DX11+DXVK/Vulkan should work fine! This patch will be applied by default in the vinegar flatpak, once the latest version is made. If you built vinegar from source or are using your distro's package, then you'll need to compile Wine [with this patch](https://github.com/flathub/io.github.vinegarhq.Vinegar/blob/master/patches/wine/childwindow.patch). It should apply on the latest staging.
