### ISSUE TITLE
Internet connection issues after exiting first game

### ISSUE THREAD

**Issue by echolessowl** [vinegarhq/vinegar#147]
Heya. Apologies if i'm describin this poorly, but i'm getting a strange issue

I reinstalled Arch Linux today and decided to hop on rblx with some friends. I managed to install vinegar and wine with no problems. The timeline of events is that I launch vinegar, hop on a roblox game, play for a while and exit, and after I exit, my internet connection across my whole device becomes extremely poor. I'm unable to download anything, load images or videos, load any roblox games from the launcher, nothing.

Anybody else having this issue or know a fix?

**Comment by echolessowl** [comment]
I should add, rebooting my machine fixes the issue, but it happens again once I launch a game through vinegar and exit again.

**Comment by Thelolguy1** [comment]
May be a network driver issue...check dmesg?

**Comment by echolessowl** [comment]
Good idea, will test soon

**Comment by echolessowl** [comment]
Nothing out of place in dmesg. No idea what's causing the issue. I'm connected to the internet using USB tethering to my phone, if that helps at all.

**Comment by echolessowl** [comment]
Nevermind, forgot to install a library to get it to work (lib32-gnutls). Works much better after going back and installing it. Sorry for wasting your time

**Comment by apprehensions** [comment]
You shouldn't need gnutls for Roblox. its technically only required for the Roblox installer.
