### ISSUE TITLE
Controller Support Xbox One bluetooth

### ISSUE THREAD

**Issue by greengeckowizard** [vinegarhq/vinegar#149]
Hello I have connected my Xbox One controller using bluetooth and I can't seem to get the Roblox window to accept the inputs from the Xbox controller.  I am running the latest version on Flathub (Flatpak) 1.4.1 and on Linux Mint 21.2 Cinnamon. Thank you devs for making this awesome and easy to run Roblox wrapper!

**Comment by mr-sihc** [comment]
there is a website to see if your controller works at all (the website isn't 100% accurate, but an official xbox controller would definitely be supported) it's called gamepadtester, and if it still doesn't work, the problem isn't from vinegar's side but from WINE's (winehq.org) most likely, report the issue there if it does work elsewhere.

**Comment by greengeckowizard** [comment]
thanks so it works controls can be a bit funky I had to close and reopen a game in the player and it recognized it. I'm gonna test wired now to see if it will work better. I used that site and it does register all buttons on bluetooth.

**Comment by greengeckowizard** [comment]
Wired has no issues. Bluetooth controls are wacky though
