### ISSUE TITLE
"Notification Stream is Currently unavailable"

### ISSUE THREAD

**Issue by SuperAtraction** [vinegarhq/vinegar#150]
Roblox says that the notfication stream is currently unavailable, as shown in the following image: 
![image_2023-09-10_125217808](https://github.com/vinegarhq/vinegar/assets/91375731/cf854655-9ae5-4ca6-bf60-7e59f91be797)

**Comment by apprehensions** [comment]
This is most likely a problem with WebView. Please wait until Wine can install it properly.

Related: #32
