### ISSUE TITLE
Change keyboard layout

### ISSUE THREAD

**Issue by WyeneCloud** [vinegarhq/vinegar#151]
Hi. im french and would like to play with my beloved azerty layout. is there any way to do it ?

**Comment by mr-sihc** [comment]
ask questions on the discord, dont open issue here, and yes you can use winecfg `vinegar exec winecfg` and the set your keyboard layout
![grafik](https://github.com/vinegarhq/vinegar/assets/85245131/e0be9aa5-078c-4f03-9441-78fb1f953be4)
