### ISSUE TITLE
Freezing after some amount of time in games.

### ISSUE THREAD

**Issue by PassiveLemon** [vinegarhq/vinegar#152]
I can't seem to pinpoint what is causing the issue. Phantom Forces will freeze anywhere from 20 minutes to an hour in. Same with Frontlines, and Miners Haven. A smaller game though, Factory Town Tycoon, can go several hours before freezing. The console does not produce any errors when it freezes.

Heres my config:
```
[env]
WINEFSYNC = "1"

[player]
renderer = "Vulkan"
dxvk = false
auto_kill_prefix = true

[player.env]
DXVK_HUD = "0"

[player.fflags]
DFIntTaskSchedulerTargetFps = 120
FFlagFixGraphicsQuality = true
```

I'm thinking it may have to do with effects/particles or something. Games with less effects tend to freeze less often. This may have to do with Vinegar (Using 1.4.2) or it could be Wine (currently using Staging 8.5).

**Comment by PassiveLemon** [comment]
Actually, I just managed to get a freeze with an error output:
```
012c:err:sync:RtlpWaitForCriticalSection section 00000000003400D0 "/build/wine-8.5/dlls/ntdll/heap.c: main process heap section" wait timed out in thread 012c, blocked by 0148, retrying (60 sec)
0134:err:sync:RtlpWaitForCriticalSection section 00000000003400D0 "/build/wine-8.5/dlls/ntdll/heap.c: main process heap section" wait timed out in thread 0134, blocked by 0148, retrying (60 sec)
```

**Comment by Thelolguy1** [comment]
Odd, that message appears on my non-functional system as well. Perhaps something in Roblox is locking up?

**Comment by Thelolguy1** [comment]
Try upgrading your wine. 8.5 is very old.

**Comment by PassiveLemon** [comment]
Upgrading to 8.14 seems to work? It's been a few hours and I haven't crashed yet, nor seen any errors in the console. I didn't realize 8.5 was fairly old. I'll mark this as solved.
