### ISSUE TITLE
Webcam Support

### ISSUE THREAD

**Issue by MacncheeseTTR** [vinegarhq/vinegar#154]
My webcam doesn't work, throwing a facial recognition error when turned on, the camera is indeed detected, but unusable. I only have 1 webcam, probably guessing this is a wine issue?

**Comment by maxrdz** [comment]
I don't have much details either but yes everyone gets the "Facial Animation feature is not available. Try rejoining the experience." message when trying to use that feature via wine.

**Comment by Thelolguy1** [comment]
Going to need more information. Installation method? Distro? Any special notes?

**Comment by MacncheeseTTR** [comment]
Sure, Im using popos currently, also using the flatpak installer.

**Comment by Thelolguy1** [comment]
This appears to be a wine issue; the flatpak is already set to use devices=all, allowing full access to webcam. Unfortunately, I don't have access to the camera features of Roblox, so I cannot test this.

**Comment by Thelolguy1** [comment]
More testing would be appreciated

**Comment by Lightmaxifrvr** [comment]
okay what ive figured out is that 

1. Integrated OR External Cameras do not work
2. Roblox has a Setting for selecting Cameras hover it does nothing
![2023-09-26_13-08](https://github.com/vinegarhq/vinegar/assets/100568192/c5bb0821-d2cb-4f3b-8df3-ee24b1fda54f)

**Comment by angrypig555** [comment]
Same for me on Debian 12
![kép](https://github.com/vinegarhq/vinegar/assets/84266804/45890e62-a9da-498f-9fe5-a2825fc97309)

**Comment by Noted-Jrelvas** [comment]
> ok so no one is fixing it. ill try looking into the wine version that vinegar uses
Well yeah, this is the worst possible combination if you want something fixed. It's a hard to debug issue which only affects a relatively niche usecase, and there's little actionable info.

I don't think this will ever be fixed unless someone either makes it a priority or we have new leads on this.

**Comment by cclockworks** [comment]
roblox may be detecting only the microphone on the webcam. i was having this issue and using obs virtual camera fixed it

**Comment by Noted-Jrelvas** [comment]
![imagem](https://github.com/vinegarhq/vinegar/assets/55360900/b59d2e38-8f65-4d5f-a754-747f20dc93da)

I gave the webcam a try. Here's some actionable information :)

@Thelolguy1 it's now confirmed this is not a permission issue with the flatpak.

**Comment by Noted-Jrelvas** [comment]
This is a dead end. The issue is with Wine trying to access the **v4l2** device with more than a single device and I am NOT touching that shit with a ten foot pole. There's no sane way to deal with this from vinegar's side (unless you find vinegar making v4l2 loopback devices behind the user's back acceptable). All we can do is document a way to provide a multi-process loopback with the help of OBS virtual camera.

@apprehensions @Thelolguy1

This crap will continue to be a problem until wine developers implement a pipewire driver. 
Needless to say, we will be waiting for a long time.

**Comment by Noted-Jrelvas** [comment]
We've decided this is out of scope as we have no feasible way of fixing it.

Unless someone has a really good lead which doesn't make us do something really stupid and overly complex, then I'm afraid this is going to remain broken until Wine has its pipewire driver up and running :(
