### ISSUE TITLE
make: *** [Makefile:18: vinegar] Error 2

### ISSUE THREAD

**Issue by Ximi123456** [vinegarhq/vinegar#155]
If i try type "make" i got this error

go build  -ldflags="-s -w -X main.BinPrefix=/usr/libexec/vinegar -X main.Version=`git describe --tags --dirty`" ./cmd/vinegar
# github.com/vinegarhq/vinegar/wine
wine/prefix.go:27:23: cmd.Environ undefined (type *exec.Cmd has no field or method Environ)
note: module requires Go 1.20
make: *** [Makefile:18: vinegar] Error 2

My distro is Kubuntu 22.04
How i can fix this

**Comment by apprehensions** [comment]
You need Go 1.20
