### ISSUE TITLE
RFC: Add "winehq report friendly" mode.

### ISSUE THREAD

**Issue by Noted-Jrelvas** [vinegarhq/vinegar#156]
Currently, Vinegar does some (sane) modifications by default, which technically invalidates all reports made to our upstream (Wine). ~~I'm suggesting a new top-level option to config.toml which automatically minimizes Vinegar's operation to just "installing Roblox into a wineprefix".~~ 
**V2 Update:** @apprehensions suggests to avoid `config.toml` and do this implicitly via the env instead, by setting the `WINEPREFIX` variable. Vinegar would have logic which detects said variable, switches to the prefix and disables whatever WineHQ instructs to (implicitly assumes the user is attempting to debug since they provided their own prefix).

This would be extremely useful for reporting upstream; no need to manually download Roblox and have a stray wineprefix in your system. There's also the fact that Roblox's web installer is still broken, we want to make sure that both us (and Wine contributors, if they're interested!) can easily test Roblox in an upstream-friendly manner.

Here's a high-level list of requirements:
- No DLL overrides.
- No DXVK.
- Isolated wine logs and crash information. (No Vinegar messages)
- (?) Potentially use a separate wineprefix while this mode is in use (with no changes applied); certifies that the issue we're trying to report isn't caused by changes we make to the registry via regedit, etc.

V2 Example: `WINEPREFIX="prefix-pain" vinegar studio`

~~Example:~~
```
wineroot = "/home/meow/wine-ge"
launcher = "gamemoderun"
# This option enables a special mode which simplifies making bug reports to WineHQ. DO NOT USE unless you're contributing to/developing Vinegar! 
winehq-report-mode = true

[env]
WINEFSYNC = "1"

[player]
dxvk = false
renderer = "Vulkan"
channel = "zcanary"

[player.env]
DXVK_HUD = "0"

[player.fflags]
DFIntTaskSchedulerTargetFps = 144

[studio]
renderer = "OpenGL"
```
~~Since there's zero utility for end users, we probably don't want to mention this option's existence in [documentation](https://vinegarhq.github.io/Configuration/index.html).~~

Comments welcome and asked for!

**Comment by Noted-Jrelvas** [comment]
Here's a list of guidelines we have to make sure vinegar is capable of following with this mode: https://wiki.winehq.org/Bugs

**Comment by apprehensions** [comment]
Can't you Add this to documentation N?

**Comment by Noted-Jrelvas** [comment]
I don't have anything against exposing this as an option in docs, but I do think it'd be better to hide this option from regular users to avoid confusion.

**Comment by rockyamethyst** [comment]
Maybe leave it on a separate docs page with more information about bug reporting? Along with more information on how to do a issue/bug report correctly, like expected formatting, basic information, etc. Would make the process of diagnosing (and sending things upstream) a lot easier.

**Comment by Noted-Jrelvas** [comment]
@rockyamethyst That could be a decent idea. For now, I'll continue hacking away at the proposal code

**Comment by Noted-Jrelvas** [comment]
I just made a PR (#157) which adds the changes necessary to satisfy the last point of the list. No actual WineHQReportMode (WIP name) additions yet-

> - (?) Potentially use a separate wineprefix while this mode is in use (with no changes applied); certifies that the issue we're trying to report isn't caused by changes we make to the registry via regedit, etc.

**Comment by Noted-Jrelvas** [comment]
PR #158 does not require major refactors to the codebase.

**Comment by Noted-Jrelvas** [comment]
Updated RFC (V2): Set winehq report mode implicitly via ENV.

**Comment by Noted-Jrelvas** [comment]
We've decided to go ahead ahead with RFC V2; I will make a third PR which reflects the design we agreed upon.

**Comment by Noted-Jrelvas** [comment]
Status update: WINEPREFIX and -config have been added, which are the necessary pieces to make this work. All that's left to do is to include a winehq-friendly cfg.

**Comment by Noted-Jrelvas** [comment]
@apprehensions actually can you not close this just yet? we still need an updated version of https://github.com/vinegarhq/vinegarhq.github.io/pull/66 (with the WINEPREFIX set in the configuration) merged.

**Comment by apprehensions** [comment]
ok
