### ISSUE TITLE
OpenGL 2.0 Error

### ISSUE THREAD

**Issue by gtsrhythm** [vinegarhq/vinegar#159]
**Distro:** Pop_OS! 22.04LTS
**Desktop Env:** Gnome 42.9, x11
**Wine Version:** 8.0.2
**Installation Method:** From Source
![image](https://github.com/vinegarhq/vinegar/assets/120328226/4b2e097d-0aa7-4409-8d23-5c020c026469)

**Comment by Cristiandis** [comment]
What gpu do you use

**Comment by gtsrhythm** [comment]
> What gpu do you use

Intel® Core™ i5-3570 igpu

**Comment by Cristiandis** [comment]
Do you have the latest mesa installed?

**Comment by Cristiandis** [comment]
Update your system

**Comment by gtsrhythm** [comment]
> Do you have the latest mesa installed?
Yeah.
![image](https://github.com/vinegarhq/vinegar/assets/120328226/b8d5701b-b6d3-4099-8aad-50f4fb245b2f)

**Comment by apprehensions** [comment]
Or your GPU
