### ISSUE TITLE
Roblox Studio Stuttering

### ISSUE THREAD

**Issue by gtsrhythm** [vinegarhq/vinegar#160]
[Roblox Studio.webm](https://github.com/vinegarhq/vinegar/assets/120328226/b742c8b9-ced6-4480-b58c-b6198c89e119)

While in the video, it doesn't show as clearly; Roblox studio is extremely stuttery, to the point where making anything other than ui is downright impossible.

**Distro:** Pop_OS! Latest
**Wine:** Latest
**Source:** Flatpak
**Desktop Env:** Gnome 42.9 x11

**Comment by Noted-Jrelvas** [comment]
Do you have any non-native QT widgets open? (Created by built-in plugins like the toolbox, or plugins you got from the marketplace) If so, then that's most likely the cause of this issue. The D3D/OpenGL renderers have an issue where said widgets can flicker and also massively decrease performance while they're open. If you're using these renderers, the only fix is to close these widgets. [A bug has been opened upstream at WineHQ](https://bugs.winehq.org/show_bug.cgi?id=52283), but there's nothing else we can do to address this issue.

If you require those widgets, and overall want studio to have some semblance of stability and performance, you can use the DXVK/Vulkan renderers. They require you to use a Wine binary with a specific patch applied, the childwindow patch, but should work much better. We're working on making this patch available in the flatpak and the DXVK renderer the default, but I'm not sure if the update has been published yet (@Thelolguy1 please confirm).

If not, you could either build vinegar from source and use a custom wine-tkg build with the patch applied, or you could build the latest version of the flatpak (found at https://github.com/flathub/io.github.vinegarhq.Vinegar), which should have the patch applied and ready to go. 

This hasn't gotten a lot of testing yet (but it has worked fine for both myself, @Thelolguy1 and some other people), so additional hardware and configurations here are appreciated.

**Comment by Thelolguy1** [comment]
`If you require those widgets, and overall want studio to have some semblance of stability and performance, you can use the DXVK/Vulkan renderers. They require you to use a Wine binary with a specific patch applied, the childwindow patch, but should work much better. We're working on making this patch available in the flatpak and the DXVK renderer the default, but I'm not sure if the update has been published yet (@Thelolguy1 please confirm).`

Yep, Flatpak already has this.

**Comment by gtsrhythm** [comment]
I installed the latest version and the problem seems to have been fixed now. Thank you.
