### ISSUE TITLE
Roblox Studio does not launch?

### ISSUE THREAD

**Issue by o-gui-blindao** [vinegarhq/vinegar#162]
Whenver i open studio, it just stays at the splash for a bit before closing with "An unexpected error has occured and roblox needs to quit" error, is there anyway to workaround or fix this?

**Comment by Thelolguy1** [comment]
Ensure you have the childwindow patch in Wine, set your DPI through winecfg to 192, and make sure your renderer is Vulkan or D3D11 with DXVK.

**Comment by MurzNN** [comment]
Thank you for the advice! Changing DPI through winecfg to 192 resolves the problem with launching Roblox Studio! But the interface became huge! @Thelolguy1  Is it possible to make it work with default 92 DPI?

**Comment by juguerre** [comment]
Same problem here,
Would be nice to get studio running with 92 DPI ... Is there any workaround?

**Comment by Thelolguy1** [comment]
Not at the moment, since it's a Roblox bug.

**Comment by Magicalus** [comment]
It looks like any DPI other than the default works, not just 192.

**Comment by MurzNN** [comment]
Yea, works with 120 DPI too! So, seems this is Wine issue, maybe it's a good idea to report it here https://bugs.winehq.org/describecomponents.cgi?product=Wine ? I can report, but what the component to choose?

**Comment by MurzNN** [comment]
With the latest release of Vinegar, Roblox started to work well with default 90 DPI, hooray!
