### ISSUE TITLE
Crash when trying to open using website

### ISSUE THREAD

**Issue by mr-sihc** [vinegarhq/vinegar#163]
when i try to join a game over the website, its a black screen then a second later it crashes

but the app works

**Comment by Thelolguy1** [comment]
Installation method? System specs?

**Comment by mr-sihc** [comment]
oh right...
Artix Linux installed over AUR
I dont think my specs are important
because it USED to work

it broke some time after i think an update of vinegar

**Comment by mr-sihc** [comment]
tried reeinstall of wineprefix, did nothing, tried D3D with DXVK, nothing too, different wine versions... nothing...

**Comment by apprehensions** [comment]
check ur logs

**Comment by mr-sihc** [comment]
github's too stupid to let me upload logs, so here's google drive

https://drive.google.com/file/d/1K6FDW0CEi_LeRiLIMY3bggyvG1-pjapq/view?usp=sharing

and also, add to the website where the logs are stored, i count find it had to check source code
and please remove old logs from the log dir, it piles up and makes it hard to find logs and takes space

**Comment by mr-sihc** [comment]
do you know what the problem is?

**Comment by apprehensions** [comment]
ni

**Comment by apprehensions** [comment]
no

**Comment by Thelolguy1** [comment]
Any update on this?

**Comment by mr-sihc** [comment]
i dont use flatpack but even if i use pipewire-pulse instead of alsa it crashes on the pulse driver (that it doesn't even use when i use alsa but still has the same crash)
```
Assertion failed: !status, file ../wine-ge-custom/proton-wine/dlls/winepulse.drv/mmdevdrv.c, line 226

0120:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
```

**Comment by mr-sihc** [comment]
fixed itself!
