### ISSUE TITLE
Shift Lock issue

### ISSUE THREAD

**Issue by Zestski** [vinegarhq/vinegar#164]
When I move it, it manages to get out of the Roblox window and get in the way of my gameplay, how do I solve this?

**Comment by rockyamethyst** [comment]
Switch to x11 (there should be an option for that somewhere in your login screen) or use gamescope

**Comment by Zestski** [comment]
> Switch to x11 (there should be an option for that somewhere in your login screen) or use gamescope

Got it working, thanks! But how can I fix webview issue?

**Comment by apprehensions** [comment]
`vinegar install-webview2`
