### ISSUE TITLE
The application encountered an unrecoverable error.

### ISSUE THREAD

**Issue by ioletsgo** [vinegarhq/vinegar#167]
Wine Version - wine-8.16\
Vinegar Version - 1.4.2
OS - Arch Linux
CPU - AMD Ryzen 5800x3D
GPU - AMD Radeon 6750 XT

**Comment by TheComputerGuy96** [comment]
@ioletsgo https://bugs.winehq.org/show_bug.cgi?id=55604

**Comment by ioletsgo** [comment]
would a possible solution be to downgrade to a known good wine version?

**Comment by TheComputerGuy96** [comment]
> would a possible solution be to downgrade to a known good wine version?
@ioletsgo Wine v8.14 (or 8.15) shouldn't have that issue

**Comment by ioletsgo** [comment]
yeah it appears downgrading to 8.15 works
