### ISSUE TITLE
External Apps

### ISSUE THREAD

**Issue by gtsrhythm** [vinegarhq/vinegar#168]
Is there any way to add external apps like you are able to on grapejuice?

**Comment by Username404-59** [comment]
There's the [launcher configuration option](https://vinegarhq.github.io/Configuration/index.html#configuration-values) if that is what you are looking for

**Comment by gtsrhythm** [comment]
No I mean like, for example, a multi-instance or a fpsunlocker app that you'd normally use on windows.

**Comment by apprehensions** [comment]
`vinegar exec`

**Comment by apprehensions** [comment]
Vinegar uses a FFlag for fps unlocking, no need for a unnecessary external application.

**Comment by Username404-59** [comment]
```toml
[player.fflags]
DFIntTaskSchedulerTargetFps = 144
``` in the config

**Comment by gtsrhythm** [comment]
Oh alright thank you.

**Comment by apprehensions** [comment]
Read the documentation next time
