### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by TheAnnoyingFruit** [vinegarhq/vinegar#170]
I am running vinegar on a 6700xt and get very low fps. Sometimes in the 30s and sometimes lower. I have tried grapejuice as well and still have this issue. I have no idea why this is and will gladly provide any logs you need to assist. Just tell me what to do and I will provide them.

**Comment by apprehensions** [comment]
1. What distrobution are you using?
2. What installation method are you using of Vinegar?
3. Have you installed all of the necessary multilib graphics dependencies?
4. Have you tinkered with the configuration? (eg. disable Esync, change renderer)

**Comment by TheAnnoyingFruit** [comment]
1. I’m using opensuse tumbleweed
2. I’ve installed the flatpak
3. As far as I’m aware I don’t need anything else with the flatpak.?
4. I have tried with fsync on and off and have tried vulkan and dx11 via dxvk.

**Comment by apprehensions** [comment]
Do you have an integrated graphics card? Try using OpenGL

**Comment by TheAnnoyingFruit** [comment]
I do have an integrated intel igpu. Opengl is the same story

**Comment by apprehensions** [comment]
Then the issue is your integrated intel igpu, Roblox is most likely utilizing it.
```toml
[env]
DRI_PRIME = "1"
```

**Comment by TheAnnoyingFruit** [comment]
I tried this and nvtop even without using the variable shows it using my 6700xt but still poor performance. I will try to hard disable the igpu in my bios .

**Comment by TheAnnoyingFruit** [comment]
Any other ideas what could be causing this?

**Comment by Thelolguy1** [comment]
Please ensure that your drivers are up to date; flatpak occasionally does not update dependencies properly, leading to bugs and poor performance.

**Comment by TheAnnoyingFruit** [comment]
It seems fine with the recent update of vinegar. It seems some vinegar updates fix it and others return it to poor performance.

**Comment by webgtx** [comment]
I faced the same issue, I tired to install vinegar with flatpak and from source. No difference, still have about 15 fps with GTX 1050ti
I'm running Centos Stream 9 and yes my drivers are updated :shipit:

**Comment by Thelolguy1** [comment]
Apologies for my inactivity, I've been having trouble reproducing this issue. Roblox *did* push a buggy build recently, so try setting your quality to a fixed value.

**Comment by TheAnnoyingFruit** [comment]
Currently it seems to be fixed I will reopen if another update breaks performance again
