### ISSUE TITLE
Cant login.

### ISSUE THREAD

**Issue by h14turkiye** [vinegarhq/vinegar#176]
After typing my credentials and pressing Log In button. A white window appears, what I presume is roblox bot detect.
![image](https://github.com/vinegarhq/vinegar/assets/112547995/7ff26131-5c9e-4b76-b277-43cbbaa93cc9)

**Comment by apprehensions** [comment]
Please use Quick login, WebView is broken.

**Comment by apprehensions** [comment]
Duplicate of #32
