### ISSUE TITLE
Roblox studio loads forever

### ISSUE THREAD

**Issue by angrypig555** [vinegarhq/vinegar#178]
When i launch roblox studio it just shows the starting screen and does nothing. Doesnt launch it.

**Comment by Thelolguy1** [comment]
Please ensure that you have the childwindow patch (available in the Flatpak version), your DPI is set to 192, and you are either using DXVK with D3D11 or Vulkan.

**Comment by angrypig555** [comment]
If DXVK shows a fps counter i had it some time ago a few days ago i started roblox and it dissapeared

**Comment by angrypig555** [comment]
It works :D
