### ISSUE TITLE
Roblox Player and Roblox Studio can't run at the same time

### ISSUE THREAD

**Issue by MentoskaPraha** [vinegarhq/vinegar#181]
The Vinegar flatpak doesn't allow for the Player and Studio to be opened at the same time. When attempting to do so either the Player or Studio will throw the following error depending on which is being open:
```
02cc:err:esync:esync_init Failed to open esync shared memory file; make sure no stale wineserver instances are running without WINEESYNC.
02d4:err:esync:esync_init Failed to open esync shared memory file; make sure no stale wineserver instances are running without WINEESYNC.
2023/09/15 16:02:21 binary.go:158: exit status 1
```

**Comment by MentoskaPraha** [comment]
Just to add to this because, I forgor, according to wael on [Discord](https://discord.com/channels/1069506340973707304/1152229257964158996): "This might be due to the fact that there are two wineservers running simultaneously on the same wineprefix Flatpak makes a new sandbox so"

**Comment by apprehensions** [comment]
@Thelolguy1
