### ISSUE TITLE
Roblox Update works in Wine-GE but not flatpak included wine build

### ISSUE THREAD

**Issue by Bdogg202** [vinegarhq/vinegar#187]
Hi, just to preface this, I made a Github account today just to report this, sorry if I'm not very helpful or useful. 

My friend just called me asking for help with the issue that cropped up today with the client not launching after today's update. From our testing, we got it to work by setting wineroot to use wine-ge instead of the standard wine build included in the flatpak. Sorry again if this isn't much help.

**Comment by Bdogg202** [comment]
Right, here's the logs. First is with flatpak stock wine build, second is with wine-ge set to wineroot.
[player-2023-10-05T175448-0300-CRASH.log](https://github.com/vinegarhq/vinegar/files/12824160/player-2023-10-05T175448-0300-CRASH.log)
[player-2023-10-05T182327-0300-WINEGE.log](https://github.com/vinegarhq/vinegar/files/12824161/player-2023-10-05T182327-0300-WINEGE.log)

**Comment by MeemeeLab** [comment]
Probably related to the #185 or #186? There was Roblox update 6 hours ago which broke Vinegar.

**Comment by Bdogg202** [comment]
yes sorry, this is in reference to those issues

**Comment by MeemeeLab** [comment]
I didn't read OP enough, my bad.
I wonder what GE did to made it to not crash...

**Comment by Bdogg202** [comment]
No worries, this is my first github issue ever, i probably worded it wrong. To be very clear: the roblox client update from 6 hours ago. Crashes in flatpak on launch. It only crashes with the bundled build of wine. Setting wineroot to wine-ge fixes it. Sorry again for any confusion.

**Comment by Thelolguy1** [comment]
Please update your flatpak, there is a new build.

Additionally, it may be necessary to purge the flatpak with 

```flatpak remove io.github.vinegarhq.Vinegar --delete-data``` (answer yes)

and then reinstalling.

**Comment by Bdogg202** [comment]
Tested the flatpak update, works fine again. Thanks, closing the issue
