### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by EysseW** [vinegarhq/vinegar#190]
[error.txt](https://github.com/vinegarhq/vinegar/files/12834547/error.txt)

**Comment by Cristiandis** [comment]
are you trying to studio?

**Comment by EysseW** [comment]
No, this is upon running "vinegar player"

**Comment by Cristiandis** [comment]
How did you install vinegar

**Comment by EysseW** [comment]
I installed it from. AUR on base Arch.

**Comment by Cristiandis** [comment]
What wine version do you have?

**Comment by EysseW** [comment]
Latest from the Arch repos, can't check the specific version right now, sorry. It have updated half an hour ago, so it should be the very latest.

**Comment by Cristiandis** [comment]
Wine 8.16 and 8.17 don't work

**Comment by EysseW** [comment]
I see. Is that fixable?

**Comment by Cristiandis** [comment]
Either downgrade to 8.15 or use wine-ge if you don't care about studio

**Comment by EysseW** [comment]
I meant: is possible to make it work on newer versions of wine? Where is the problem? On wine's end?

**Comment by Cristiandis** [comment]
> I meant: is possible to make it work on newer versions of wine? Where is the problem? On wine's end?

Wine added a patch that broke roblox on 8.16, still not fixed in 8.17, wine-ge uses wine 8.16 but reverted that patch so it works

**Comment by EysseW** [comment]
Having downgraded wine,  I get even more serious errors, probably regarding depending packages.
How would I launch vinegar with wine-ge?

**Comment by Cristiandis** [comment]
Download it, unpack it somewhere and in the config file put the `wineroot =` to the path of wine-ge

**Comment by EysseW** [comment]
Thanks!
