### ISSUE TITLE
Make a Debian/Ubuntu package available

### ISSUE THREAD

**Issue by hl2jeep** [vinegarhq/vinegar#191]
I noticed there are no packages available for Debian/Ubuntu based systems, i refuse to use flatpak because it bloats massively, the flatpak vinegar package takes up 4gb disk space because of all the dependancies that i assure you my system already has but flatpak has to install them again, my laptop is dualbooted and my linux partition is small in size, i also don't really want to build the package everytime i reinstall.

**Comment by apprehensions** [comment]
Make it :D

**Comment by hl2jeep** [comment]
> Make it :D

there isn't even a build guide for debian/ubuntu based systems, im not even sure if the makefile has the right config for those systems

**Comment by apprehensions** [comment]
https://packaging.ubuntu.com/html/packaging-new-software.html

**Comment by apprehensions** [comment]
actually it belongs more like this
