### ISSUE TITLE
Installation of Webview2 fails

### ISSUE THREAD

**Issue by FauconFR** [vinegarhq/vinegar#192]
Hello,
Roblox studio isn't launching so I tried running `vinegar install-webview2`.
It runs for an hour then it says "Installation failed".

I'm using the flatpak version, and `winehq-stable`.

**Comment by apprehensions** [comment]
reminder that you dont need webview2 for login to studio, you can just login with player and studio will be authenticated
as for this, this is not our problem and most likely we will remove this later as we dont have much use for it and it doesnt seem to work.
