### ISSUE TITLE
Roblox Studio won't open pop os

### ISSUE THREAD

**Issue by SamuelEzequiasPlays** [vinegarhq/vinegar#193]
I'm trying to open Roblox Studio in Pop OS but it doesn't open, it just stays on the startup screen, I tested Roblox Player and it worked perfectly. I've been waiting for about 5 minutes and Roblox Studio won't open

https://github.com/vinegarhq/vinegar/assets/90923418/92cc4dae-cfd3-4138-8404-60e53aa2be58

**Comment by SamuelEzequiasPlays** [comment]
I found this
![Captura de tela de 2023-10-09 00-04-51](https://github.com/vinegarhq/vinegar/assets/90923418/db4be48f-051f-46fc-b2fc-111d472f4a8c)

**Comment by angrypig555** [comment]
Tried to update it?

**Comment by Thelolguy1** [comment]
Make sure you have the childwindow patch, and set your DPI to a number that is not the default by using `winecfg`

**Comment by SamuelEzequiasPlays** [comment]
> Tentou atualizá-lo?

How do I update? I downloaded it from the pop os store

**Comment by Vulpovile** [comment]
Happens to me too, @Thelolguy1 your comment really doesn't clarify what the childwindow patch even is, let alone how to run winecfg under vinegar in a flatpak

**Comment by SamuelEzequiasPlays** [comment]
> Make sure you have the childwindow patch, and set your DPI to a number that is not the default by using `winecfg`

How do I run winecfg for vinegar and where do I download this childwindow path?

**Comment by SamuelEzequiasPlays** [comment]
> How do I update? I downloaded it from the pop os store

I downloaded the update available in the pop shop and it continues the same way

**Comment by Vulpovile** [comment]
You can run it via "vinegar exec winecfg" or under flatpak using "flatpak run io.github.vinegarhq.Vinegar exec winecfg

**Comment by SamuelEzequiasPlays** [comment]
> flatpak run io.github.vinegarhq.Vinegar exec winecfg

It worked! Thank you very much, I changed the dpi to 144 and roblox studio opened

**Comment by Vulpovile** [comment]
Personally I wouldn't close this, there's a *workaround*, but this is definitely still a big
