### ISSUE TITLE
Trying to start Studio fails if DPI is default

### ISSUE THREAD

**Issue by Vulpovile** [vinegarhq/vinegar#194]
For some reason, studio crashes with a "We're sorry!" message if you try to launch it without setting the DPI to something else (even if it's only 1 higher) in winecfg. 

System is Debian 12, NVidia 1050ti with proprietary drivers, 16GB of RAM, i7-7700HQ with KDE Plasma desktop.

**Comment by Vulpovile** [comment]
[Vinegar Crash Log.log](https://github.com/vinegarhq/vinegar/files/12859986/Vinegar.Crash.Log.log)

**Comment by MurzNN** [comment]
With the latest release of Vinegar, Roblox started to work well with default 90 DPI, hooray!

**Comment by Vulpovile** [comment]
I personally set it to 97 and it works great too, and doesn't even scale the text lol. What a weird bug
