### ISSUE TITLE
Roblox doesn't launch under Edge, but under Firefox it does

### ISSUE THREAD

**Issue by tuca1234567890** [vinegarhq/vinegar#195]
As the title says, Roblox just doesn't show up when I click Play on Edge. The vinegar launcher shows up but nothing happens. On Firefox, it works as expected.

Log when launched on Edge: https://gist.github.com/tuca1234567890/9205bed6b59b87a7079f2a894ee9bad1
Log when launched on Firefox: https://gist.github.com/tuca1234567890/9cd15b8212845a1c0c2bfe80fdcd7def

**Comment by apprehensions** [comment]
```
011c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
011c:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
```

**Comment by tuca1234567890** [comment]
That doesn't explain anything since launching on Firefox doesn't give that error

**Comment by apprehensions** [comment]
ok then stop using edge lol

**Comment by BrycensRanch** [comment]
me when the code doesn't work as expected but its on a platform you despise
