### ISSUE TITLE
NixOS support

### ISSUE THREAD

**Issue by imnotrev** [vinegarhq/vinegar#197]
I mean- yes. You CAN use vinegar with flatpak. But it would be useful for people that don't like to use external package manager
I think this is planned? I don't know didn't see this mentioned anywhere

**Comment by apprehensions** [comment]
https://github.com/NixOS/nixpkgs/pull/251795

**Comment by imnotrev** [comment]
Ah, i see. For now i will use the flatpak version until its merged
