### ISSUE TITLE
"Roblox encountered an unexpected error"

### ISSUE THREAD

**Issue by Nightro-Fx** [vinegarhq/vinegar#199]
Here's the error I faced:
```
Roblox encountered an unexpected error
Click "Ok" to create a memory dump, then please share it on our support site: https://roblox.com/support
```

**Comment by apprehensions** [comment]
You need wine version 8.17 or staging 8.17 with a specific patch to revert a change which makes this error occur.

Although, it could also be due to your cpu not supporting AVX2(?)

**Comment by mikedebian** [comment]
Ryzen 3800x, Wine 8.17 on arch. Same issue.

**Comment by Thelolguy1** [comment]
Source or flatpak?

**Comment by hapsti** [comment]
same issue, arch linux

**Comment by mikedebian** [comment]
> Source or flatpak?

Source

**Comment by Thelolguy1** [comment]
Did you remember to patch with the segment registers patch?

**Comment by hapsti** [comment]
fixed my issue by using an older vesion of wine, downloaded this:
`https://archive.archlinux.org/repos/2023/05/21/multilib/os/x86_64/wine-8.8-1-x86_64.pkg.tar.zst`
and did `sudo pacman -U [file]` to replace my systems wine with it

**Comment by Thelolguy1** [comment]
Risky, that's a very old version of wine.

**Comment by lunarlettuce** [comment]
No response for 3 weeks, assuming completed.
