### ISSUE TITLE
'Unapproved third party applications or extensions detected.'

### ISSUE THREAD

**Issue by PedriNH4x** [vinegarhq/vinegar#200]
When I Try to Start Roblox is getting this problem below; 

![Screenshot_20231014_094508](https://github.com/vinegarhq/vinegar/assets/128862665/a06d06d1-338c-41f0-b8e3-5da1063f8c39)

This is appearing after the new Vinegar update on ArchLinux.

**Comment by apprehensions** [comment]
What's your type of vinegar installation? AUR or source? and what is your configuration?

**Comment by apprehensions** [comment]
Also, can you share your Wine logs? you can find them at `~/.cache/vinegar/logs`

**Comment by PedriNH4x** [comment]
> What's your type of vinegar installation? AUR or source? and what is your configuration?

Aur, i don't configured anything, just downloaded and tryied To Play.

**Comment by PedriNH4x** [comment]
> Also, can you share your Wine logs? you can find them at `~/.cache/vinegar/logs`

2023/10/14 09:44:26 version.go:74: Fetching latest version of WindowsPlayer for channel live (https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/)
2023/10/14 09:44:27 version.go:94: Fetched WindowsPlayer canonical version 0.598.0.5980624
2023/10/14 09:44:27 version.go:55: Found WindowsPlayer version version-57e2dd886e0e42a5
2023/10/14 09:44:27 binary.go:137: WindowsPlayer is up to date (version-57e2dd886e0e42a5)
2023/10/14 09:44:27 fflags.go:88: Using renderer: D3D11
2023/10/14 09:44:27 fflags.go:33: Applying custom FFlags
2023/10/14 09:44:27 fflags.go:51: FFlags used: {
  "DFIntTaskSchedulerTargetFps": 640,
  "FFlagDebugGraphicsDisableD3D11": false,
  "FFlagDebugGraphicsDisableD3D11FL10": true,
  "FFlagDebugGraphicsDisableOpenGL": true,
  "FFlagDebugGraphicsDisableVulkan": true,
  "FFlagDebugGraphicsPreferD3D11": true,
  "FFlagDebugGraphicsPreferD3D11FL10": false,
  "FFlagDebugGraphicsPreferOpenGL": false,
  "FFlagDebugGraphicsPreferVulkan": false
}
2023/10/14 09:44:27 dxvk.go:20: Enabling DXVK DLL overrides
2023/10/14 09:44:27 binary.go:66: Launching WindowsPlayer
2023/10/14 09:44:27 exec.go:24: Starting command: /usr/bin/wine /home/PedroArt/.local/share/vinegar/prefix/vinegar/versions/version-57e2dd886e0e42a5/RobloxPlayerBeta.exe
wineserver: using server-side synchronization.
002c:fixme:winediag:LdrInitializeThunk Wine TkG (staging) 8.17 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
2023/10/14 09:44:29 binary.go:87: Waiting for Roblox's process to die :)
0128:fixme:ntdll:NtRaiseHardError c0000005 stub
wine: Unhandled exception 0x80000004 in thread 128 at address 00006FFFFD8EF120 (thread 0128), starting debugger...
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
0140:fixme:dbghelp:elf_search_auxv can't find symbol in module
2023/10/14 09:45:15 prefix.go:28: Killing wineprefix
2023/10/14 09:45:15 exec.go:30: Running command: /usr/bin/wineserver -k

**Comment by apprehensions** [comment]
With that log, it displays that dialog window?

**Comment by PedriNH4x** [comment]
> With that log, it displays that dialog window?

Yes

**Comment by Thelolguy1** [comment]
Known bug, we don't know what is tripping up Hyperion atm. A workaround is to nuke your prefix

**Comment by PedriNH4x** [comment]
> Known bug, we don't know what is tripping up Hyperion atm. A workaround is to nuke your prefix

This bug that was happening was practically resolved after the last commit, but another one is happening now...

![Screenshot_20231015_095700](https://github.com/vinegarhq/vinegar/assets/128862665/1755300e-f355-4988-be87-3f56a19c009e)

**Comment by MacncheeseTTR** [comment]
so i was using a very outdated version of vinegar, whats interesting was that when i updated vinegar it worked fine, until roblox crashed (on zavatarteam) i restarted roblox, and got the error again, weird

**Comment by lunarlettuce** [comment]
No response for 3 weeks, assuming outdated
