### ISSUE TITLE
Implement BloxstrapRPC

### ISSUE THREAD

**Issue by apprehensions** [vinegarhq/vinegar#201]

**Comment by Noted-Jrelvas** [comment]
From my understanding, this is a functionality which implements the Discord "Rich Presence" functionality for Roblox. Is this something that their Linux client even supports?

**Comment by apprehensions** [comment]
What Linux client? Bloxstrap doesn't have one

**Comment by Noted-Jrelvas** [comment]
Not Bloxstrap, Discord.

**Comment by cloudirector** [comment]
I’m here too

**Comment by apprehensions** [comment]
There is some discussion regarding this feature and how Discord isn't much of a good platform, which adds some concern, but many users might like this feature:
![image](https://github.com/vinegarhq/vinegar/assets/47404953/eae83794-3480-4f17-8c5a-cc148ba29bf7)

**Comment by Noted-Jrelvas** [comment]
Sure, but first we need to figure out if RPC works on discord linux

**Comment by z-ffqq** [comment]
> From my understanding, this is a functionality which implements the Discord "Rich Presence" functionality for Roblox. Is this something that their Linux client even supports?

Discord's Linux client does indeed support RPC features.
