### ISSUE TITLE
Quesions on Gui for vinegar.

### ISSUE THREAD

**Issue by Disposable-account** [vinegarhq/vinegar#204]
Im curious if Gui will come in late 2023 or 2024 and if it will look like the grapejuice Gui or if it will be different from it.

**Comment by Noted-Jrelvas** [comment]
Vinegar will never have a GUI (probably).

**Comment by Disposable-account** [comment]
Oh, good to know though I will probably keep this up a bit more to see if there is other response types.

**Comment by Thelolguy1** [comment]
It will never have a GUI.
