### ISSUE TITLE
Exit Status 1 on Linux Mint

### ISSUE THREAD

**Issue by egayghost** [vinegarhq/vinegar#205]
Hi, idk what's causing this, I thought I just missed installing wine and I did it eventually, but still the error occurs.

```
2023/10/15 11:47:25 vinegar.go:131: Initializing wineprefix at /home/egayghost/.var/app/io.github.vinegarhq.Vinegar/data/vinegar/prefix
2023/10/15 11:47:25 exec.go:30: Running command: /app/bin/wineboot -i
wine: chdir to /home/egayghost/.var/app/io.github.vinegarhq.Vinegar/data/vinegar/prefix : No such file or directory
2023/10/15 11:47:25 vinegar.go:125: exit status 1`
```

**Comment by Thelolguy1** [comment]
What are you running to start roblox?

**Comment by egayghost** [comment]
> What are you running to start roblox?

I'm on linux mint 21.2

**Comment by Tundraexe** [comment]
Hello I am having the same issue. I installed the flatpack through the installation manager on mint, and ran the "Roblox App (Vinegar)" Then the window reads "exit status 1" This is the log: 2023/10/14 22:16:06 vinegar.go:131: Initializing wineprefix at /home/john/.var/app/io.github.vinegarhq.Vinegar/data/vinegar/prefix
2023/10/14 22:16:06 exec.go:30: Running command: /app/bin/wineboot -i
wine: chdir to /home/john/.var/app/io.github.vinegarhq.Vinegar/data/vinegar/prefix : No such file or directory
2023/10/14 22:16:07 vinegar.go:125: exit status 1

**Comment by egayghost** [comment]
> Hello I am having the same issue. I installed the flatpack through the installation manager on mint, and ran the "Roblox App (Vinegar)" Then the window reads "exit status 1" This is the log: 2023/10/14 22:16:06 vinegar.go:131: Initializing wineprefix at /home/john/.var/app/io.github.vinegarhq.Vinegar/data/vinegar/prefix 2023/10/14 22:16:06 exec.go:30: Running command: /app/bin/wineboot -i wine: chdir to /home/john/.var/app/io.github.vinegarhq.Vinegar/data/vinegar/prefix : No such file or directory 2023/10/14 22:16:07 vinegar.go:125: exit status 1
> 
> I am using a outdated graphics card that doesnt support vukan so that might cause issues.

shoudln't be an issue, was able to run vinegar on arch last month

**Comment by Thelolguy1** [comment]
known, we have a bug on latest vinegar. Will update asap

**Comment by apprehensions** [comment]
news flash I already solved it with the last commit minutes before this

**Comment by egayghost** [comment]
fix confirmed, thank you
