### ISSUE TITLE
Studio font fix (Removing SourceSansPro-Black.ttf)

### ISSUE THREAD

**Issue by z-ffqq** [vinegarhq/vinegar#207]
Studio's bold font issue can be fixed easily by removing SourceSansPro-Black.ttf from StudioFonts in the Studio version directory

Before and after:
![image](https://github.com/vinegarhq/vinegar/assets/36998498/6b74c592-d135-4acd-8086-3e44f9a60da9)
![image](https://github.com/vinegarhq/vinegar/assets/36998498/4df0390a-277e-4cd7-8e43-8f739b9de4b7)

This should be default functionality in Vinegar, having it be autoremoved after Studio is downloaded

**Comment by Noted-Jrelvas** [comment]
This is an absolutely great discovery. Awesome job. One more outstanding studio issue down.

@apprehensions can I take care of the implementation of this?

**Comment by apprehensions** [comment]
Fixed by 7670b5fab3ff0566f183df2b45f8beec7fb6d741

**Comment by Noted-Jrelvas** [comment]
Should've asked a hour earlier :(
