### ISSUE TITLE
Opening .rbxl/.rbxm files in Roblox Studio doesn't work unless they're located in the app's folder

### ISSUE THREAD

**Issue by Macosaro** [vinegarhq/vinegar#208]
Obviously that's because of flatpak's sandboxing :trollface:
Not sure if this will be fixed or not

**Comment by z-ffqq** [comment]
you can just use flatseal to fix this

**Comment by apprehensions** [comment]
Flatpak cannot access your home folder, you need to give it access via Flatseal, just as ffqq said.
