### ISSUE TITLE
RMB flicking screen

### ISSUE THREAD

**Issue by Tonytinza** [vinegarhq/vinegar#215]
The RMB on Roblox is used to rotate the character with precise control. However, in Vinegar whenever I use it if I hold it the moment I let go it snaps to a random rotation. This makes some games where precise control over the camera is important nearly unplayable.

**Comment by apprehensions** [comment]
Wayland?

**Comment by Tonytinza** [comment]
Yes, I use Wayland. This issue has been solved as I switched over from Hyprland to KDE, and it seems to have been a Hyprland issue rather than a Vinegar issue.
