### ISSUE TITLE
Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).

### ISSUE THREAD

**Issue by onyxcode** [vinegarhq/vinegar#216]
I can run for about 2-3 minutes with Flatpak but building from source/package results in this error on any update channel without ever seeing Roblox. I am unclear on what caused this because it worked a few hours ago.

**Comment by onyxcode** [comment]
Fixed by changing renderer to D3D11.

**Comment by apprehensions** [comment]
it is d3d11 by default.

**Comment by onyxcode** [comment]
> it is d3d11 by default.

it was vulkan for me 🤷

**Comment by apprehensions** [comment]
Because it uses DXVK, so it is Vulkan.
