### ISSUE TITLE
Vinegar doesnt open

### ISSUE THREAD

**Issue by Gilbertil** [vinegarhq/vinegar#218]
yee, idk what happen, i installed it from flatpak, my staging wine version is 8.18 and im using linux mint 21.2
error log:
2023/10/17 21:25:24 vinegar.go:136: Initializing wineprefix at /home/oshiroeo/.var/app/io.github.vinegarhq.Vinegar/data/vinegar/prefix
2023/10/17 21:25:24 exec.go:30: Running command: /app/bin/wineboot -i
/app/bin/wineboot: line 46: /app/bin/wine: cannot execute: required file not found
2023/10/17 21:25:25 vinegar.go:130: exit status 127

**Comment by awesfdawe** [comment]
it helped me to roll back from wine staging 8.18 to 8.15, try it.

**Comment by Gilbertil** [comment]
already did and that doesnt help at all 
![image](https://github.com/vinegarhq/vinegar/assets/84993798/6f5c2bb6-618d-467d-9729-cd5fe603795a)
![image](https://github.com/vinegarhq/vinegar/assets/84993798/39ff9445-4b38-4de7-9671-323f2fbaef69)

**Comment by onyxcode** [comment]
https://github.com/vinegarhq/vinegar/issues/217#issuecomment-1768460736

**Comment by Gilbertil** [comment]
i contacted the ds server and after some stuff they told me this
![Screenshot_2023-10-18-02-46-32-48_572064f74bd5f9fa804b05334aa4f912.jpg](https://github.com/vinegarhq/vinegar/assets/84993798/4eedc9e0-b15b-4732-a4b6-4d77e8ebe197)
