### ISSUE TITLE
exec: "winetricks": executable file not found in $PATH

### ISSUE THREAD

**Issue by khanmint** [vinegarhq/vinegar#220]
Hello!
I can't use winetricks with Vinegar
I'm using the flatpak version so maybe something has to do with the sandboxing?

Here's the error:
`exec: "winetricks": executable file not found in $PATH`

Please help

**Comment by apprehensions** [comment]
you need winetricks

its as shrimple as that

**Comment by lunarlettuce** [comment]
solved by org.vinegarhq.Vinegar/pull/15
