### ISSUE TITLE
keeps crashing with an error, it didn't do this a few days ago

### ISSUE THREAD

**Issue by KuraakaiGoro** [vinegarhq/vinegar#225]
2023/10/19 21:15:30 version.go:74: Fetching latest version of WindowsPlayer for channel live (https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/)
2023/10/19 21:15:30 version.go:94: Fetched WindowsPlayer canonical version 0.599.0.5990470
2023/10/19 21:15:30 version.go:55: Found WindowsPlayer version version-7cc666219b484414
2023/10/19 21:15:30 binary.go:211: WindowsPlayer is up to date (version-7cc666219b484414)
2023/10/19 21:15:30 fflags.go:88: Using renderer: D3D11
2023/10/19 21:15:30 fflags.go:33: Applying custom FFlags
2023/10/19 21:15:30 fflags.go:51: FFlags used: {
  "DFIntTaskSchedulerTargetFps": 640,
  "FFlagDebugGraphicsDisableD3D11": false,
  "FFlagDebugGraphicsDisableD3D11FL10": true,
  "FFlagDebugGraphicsDisableOpenGL": true,
  "FFlagDebugGraphicsDisableVulkan": true,
  "FFlagDebugGraphicsPreferD3D11": true,
  "FFlagDebugGraphicsPreferD3D11FL10": false,
  "FFlagDebugGraphicsPreferOpenGL": false,
  "FFlagDebugGraphicsPreferVulkan": false
}
2023/10/19 21:15:30 dxvk.go:20: Enabling DXVK DLL overrides
2023/10/19 21:15:30 binary.go:71: Launching WindowsPlayer
2023/10/19 21:15:30 exec.go:24: Starting command: /usr/bin/wine /home/romu/.local/share/vinegar/prefix/vinegar/versions/version-7cc666219b484414/RobloxPlayerBeta.exe -app
2023/10/19 21:15:30 discord.go:16: Authenticating Discord RPC
002c:fixme:winediag:loader_init wine-staging 8.18 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
2023/10/19 21:15:30 binary.go:143: Polling for Roblox log file, 10 retries
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0088:fixme:wineusb:query_id Unhandled ID query type 0x5.
0088:fixme:wineusb:query_id Unhandled ID query type 0x5.
0088:fixme:wineusb:query_id Unhandled ID query type 0x5.
0088:fixme:wineusb:query_id Unhandled ID query type 0x5.
0088:fixme:wineusb:query_id Unhandled ID query type 0x5.
0088:fixme:wineusb:query_id Unhandled ID query type 0x5.
010c:fixme:ntdll:NtRaiseHardError c0000005 stub
010c:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
010c:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
2023/10/19 21:15:40 vinegar.go:130: could not roblox log file after time 2023-10-19 21:15:30.239894044 -0400 EDT m=+0.209690967, has roblox successfully started?

I use EndeavourOS
Wine-staging 8.18

**Comment by YO-SC** [comment]
can confirm

**Comment by OddGee** [comment]
Possibly the latest roblox update? This is only hypothetical, tho.

**Comment by RetroWebVS** [comment]
FR

**Comment by YO-SC** [comment]
> Possibly the latest roblox update is breaking it? This is only hypothetical, tho.

I think so too

**Comment by KuraakaiGoro** [comment]
Roblox be like
*hates linux users*

**Comment by OddGee** [comment]
> Roblox be like _hates linux users_

It's more like they don't want to make an official linux build because we're not seen as "profitable" lolol

**Comment by KuraakaiGoro** [comment]
it sure seems "profitable" to patch out wine ig

**Comment by itsaerosphere** [comment]
> 010c:fixme:ntdll:NtRaiseHardError c0000005 stub

Hey, I have the exact same error coming out of my system. I also use Endeavour OS

I will say though, iirc Wine 8.16+ are all no-go for Roblox

**Comment by OddGee** [comment]
try forcing the version, it may fix your issue: `forced_version="version-57e2dd886e0e42a5"`

-grabbed from Vinegar's discord

**Comment by itsaerosphere** [comment]
> try forcing the version, it may fix your issue: `forced_version="version-57e2dd886e0e42a5"`
> 
> -grabbed from Vinegar's discord

Seems like that fixed it for me

**Comment by KuraakaiGoro** [comment]
> try forcing the version, it may fix your issue: `forced_version="version-57e2dd886e0e42a5"`
> 
> -grabbed from Vinegar's discord

I don't know what to do with this

**Comment by itsaerosphere** [comment]
Follow the instructions on the [documentation](https://vinegarhq.github.io/Configuration/index.html) to add the configuration line. What you're looking to add should look like this:
`[player]
forced_version="version-57e2dd886e0e42a5"`

**Comment by KuraakaiGoro** [comment]
doesn't work, it closes without error for me

**Comment by KuraakaiGoro** [comment]
I fixed the line, but it's giving me the unexpected error still

**Comment by KuraakaiGoro** [comment]
ok, it worked, I just had to downgrade wine to 8.15

**Comment by YO-SC** [comment]
> Follow the instructions on the [documentation](https://vinegarhq.github.io/Configuration/index.html) to add the configuration line. What you're looking to add should look like this: `[player]` `forced_version="version-57e2dd886e0e42a5"`



If you know, does updates to Vinegar override the conf file?

**Comment by apprehensions** [comment]
no
