### ISSUE TITLE
Roblox Studio and Roblox Player can't be run at the same time

### ISSUE THREAD

**Issue by z-ffqq** [vinegarhq/vinegar#227]
There's been an issue with the latest `master` which makes people unable to use Studio and Player at the same time.

This may affect a lot of developer's workflows, so I looked into it. After some debugging, I've found the [commit which causes this](https://github.com/vinegarhq/vinegar/commit/7eaacb14829f48718e9c2bec4cad0dcea47c65c6). Please look into it and fix it, thank you!

**Comment by apprehensions** [comment]
Is this a duplicate of #181? What sort of behavior does vinegar show when this bug occurs?

**Comment by z-ffqq** [comment]
> Is this a duplicate of #181? What sort of behavior does vinegar show when this bug occurs?

No it isn't, that's a completely different issue.

When I start Studio while the Player is running, the Studio splash screen shows for a split second and then closes abruptly.
Below is a video example of the issue:
https://github.com/vinegarhq/vinegar/assets/36998498/9c0206b7-cf97-4099-8b62-734880ab7ce3

This can also happen the other way around, with the Player not opening when Studio is open.

**Comment by apprehensions** [comment]
![image](https://github.com/vinegarhq/vinegar/assets/47404953/3080d7df-892d-4282-b54a-9d55180a7ed3)
Can't reproduce this issue. Maybe the latest 2 commits i made for more robust process checking fixed this issue on accident?

**Comment by z-ffqq** [comment]
![image](https://github.com/vinegarhq/vinegar/assets/36998498/56398861-ac83-41c3-92ef-0ac665409bd7)
That is indeed the case! Thank you for responding to the issue, I'll be closing it.
