### ISSUE TITLE
Custom cursor results in screen flickering

### ISSUE THREAD

**Issue by FemFruits** [vinegarhq/vinegar#228]
Whilst playing Vinegar on Armored Patrol, I noticed that when my cursor gets changed, the square area around it starts to flicker and make it difficult to see what your hovering over.

I am unsure what information I need to attach, I will note that I was running vinegar 1.5.3 as a flatpak on Linux Mint.

**Comment by FemFruits** [comment]
Apologies, I misclicked there.

**Comment by apprehensions** [comment]
Wayland?

**Comment by FemFruits** [comment]
No, I am running X11, especially since Nvidia seems to hate Wayland

**Comment by Noted-Jrelvas** [comment]
I remember having this issue in the past. I believe it's exclusive for Nvidia on X11.

**Comment by CrabbyDisk** [comment]
I have the same issue.

**Comment by gameskip** [comment]
I also have the same issue

**Comment by MightyAlex200** [comment]
This can be reliably reproduced on my end by setting "Camera Mode" to "CameraToggle" in the in-game menu, then right-clicking in third person to activate camera control. If memory serves me, the cursor used in that mode is transparent, so this may be an issue with partial transparency in the cursor.

**Comment by Noted-Jrelvas** [comment]
For everyone who has posted about this issue here; please give [this Experience](https://www.roblox.com/games/15065223203) a try and report back with a screen recording of the results.

For instance:
[example.webm](https://github.com/vinegarhq/vinegar/assets/55360900/45c6da63-c750-44b5-af50-c8b0a5a77d22)
