### ISSUE TITLE
Roblox is super laggy when maximized.

### ISSUE THREAD

**Issue by spenkluker645** [vinegarhq/vinegar#230]
The game can barely reach 10 FPS and mouse clicks and movement are almost completely screwed up and delayed. Tried changing everything i could to different values but it did no help and/or gave me white screens with different renderers. The Nvidia driver im using is 535.113.01-0ubuntu0.22.04.3 It could be related to that. I am on a Lenovo Legion 5 with the latest Linux Mint

**Comment by apprehensions** [comment]
https://vinegarhq.github.io/Troubleshooting/index.html#stuttering-and-freezing-nvidia-gpu

**Comment by spenkluker645** [comment]
Its not only fullscreen, but any window size. A lot of stuttering and lag.

**Comment by spenkluker645** [comment]
Any help? None of the 3 solutions worked.

**Comment by Noted-Jrelvas** [comment]
Very interesting. Sounds like your issue is unrelated then. Any logs?

**Comment by spenkluker645** [comment]
Nah, Roblox won't even launch anymore.

**Comment by spenkluker645** [comment]
Roblox is launching again, but the performance is not any better. It still has a lot of input lag and delayed, And its still very laggy. Lagginess depends on the window size, if i make it the absolute minimum, it will still have some lag. If i make it larger, it will become more laggy. Basically borked for me. Not even 1 graphics quality makes it better, and i'm VERY sure that my GPU is good enough for Roblox. It runs fine on Windows.

**Comment by spenkluker645** [comment]
Still no response? The problem got worse and now Roblox is randomly crashing. Completely unplayable.

**Comment by spenkluker645** [comment]
Should i open up a new issue?
