### ISSUE TITLE
Roblox process still runs after closing the app

### ISSUE THREAD

**Issue by expoodo** [vinegarhq/vinegar#231]
Whenever I close the roblox app by pressing the close button, it closes the window but not the `RobloxPlayerBet` process. This means I have to manually kill the process because if I try opening the app again, it does nothing (I guess vinegar thinks roblox is still running).

I'm running the flatpak version 1.5.3 vinegar and my distro is Linux Mint 21.2.

**Comment by apprehensions** [comment]
Update the flatpak, we are on 1.5.4

**Comment by expoodo** [comment]
That fixes the issue thank you
