### ISSUE TITLE
roblox keeps crashing

### ISSUE THREAD

**Issue by Rxpct123** [vinegarhq/vinegar#237]
it just crashes after a few minutes and i cant close the crash screen for some reason

**Comment by Thelolguy1** [comment]
Known, see pinned

**Comment by mzaulychny** [comment]
in my case it is noticeable that Roblox crashes when the program uses 45+% of CPU.

![Screenshot_20231026_105259](https://github.com/vinegarhq/vinegar/assets/23351834/dfdc62cc-c454-48a0-88d2-d607a37b5bf0)

**Comment by mzaulychny** [comment]
in my case it is noticeable that Roblox crashes when the program uses 45+% of CPU.
![Screenshot_20231026_105259-1](https://github.com/vinegarhq/vinegar/assets/23351834/d5b9a19e-bd19-49dd-bd9b-9a61e04dd8dc)

**Comment by Rxpct123** [comment]
> in my case it is noticeable that Roblox crashes when the program uses 45+% of CPU. ![Screenshot_20231026_105259-1](https://user-images.githubusercontent.com/23351834/278254992-d5b9a19e-bd19-49dd-bd9b-9a61e04dd8dc.png)yea but do you know how to fix or is it a problom that the devs gotta fix

**Comment by mzaulychny** [comment]
> > in my case it is noticeable that Roblox crashes when the program uses 45+% of CPU. ![Screenshot_20231026_105259-1](https://user-images.githubusercontent.com/23351834/278254992-d5b9a19e-bd19-49dd-bd9b-9a61e04dd8dc.png)yea but do you know how to fix or is it a problom that the devs gotta fix

at the moment, idk

**Comment by lokiran2** [comment]
i have like you and i can play the last week the issus be like kick the game for few munits and this craching

**Comment by Thelolguy1** [comment]
Merging with #236
