### ISSUE TITLE
roblox crashing after a few minutes 

### ISSUE THREAD

**Issue by lokiran2** [vinegarhq/vinegar#238]
When I enter the game after a few minutes, the game stops responding, so I used the old Roblox update, but unfortunately it was deleted. This was an alternative solution, and last week something similar happened, which is the automatic exit when you enter Roblox after a few minutes.
I would like a solution please

**Comment by Thelolguy1** [comment]
see pinned

**Comment by Thelolguy1** [comment]
Merging with #236
