### ISSUE TITLE
Roblox Studio unable to login via browser

### ISSUE THREAD

**Issue by itsaerosphere** [vinegarhq/vinegar#239]
Expected behaviour: Roblox Studio recognizes that the user (me) is already logged in via the browser and Roblox Player and automatically lets the user in

Actual behaviour: 
![image](https://github.com/vinegarhq/vinegar/assets/44062882/e79dba7c-c672-4838-ba27-9cfed322ec90)
Roblox Studio fails to recognize that the user is already logged in elsewhere and asks to install WebView2 (which is broken).

I'm using the Flatpak version of Vinegar.

Edit: When running Studio via console, this thing pops up:
`2023-10-28T04:15:29.808Z,29.808481,0114,6 [FLog::Output] RbxQt::openUrl: User opened an external link 'https://apis.roblox.com/oauth/v1/authorize'
Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface ?org.freedesktop.portal.OpenURI? on object at path /org/freedesktop/portal/desktop`

**Comment by itsaerosphere** [comment]
So, reinstalling the flatpak fixed it for some reason.

**Comment by brotherman123** [comment]
i did reinstall flatpak no work

**Comment by Foxelyss** [comment]
Same thing, reinstalling doesn`t fix the issue. Should issue be reopened or new created instead?

**Comment by itsaerosphere** [comment]
I personally don't have this issue anymore. I'd recommend you create a new issue.
