### ISSUE TITLE
Discord RPC has broken this software. (Arch Linux)

### ISSUE THREAD

**Issue by EpitaphEpitome** [vinegarhq/vinegar#240]
On Arch Linux, Roblox will work for a few minutes, and then freeze, my system claiming it's not responding.
After I force it to close, I try to run the software again. This time Roblox gives an error with an invalid parameter, and Vinegar claims it failed to run Roblox.

After viewing the log, it displays this.

`2023/10/28 05:51:26 version.go:54: Fetching latest version of WindowsPlayer 
2023/10/28 05:51:26 api.go:22: Performing Roblox API GET clientsettings request on v2/client-version/WindowsPlayer
2023/10/28 05:51:26 version.go:61: Fetched WindowsPlayer canonical version 0.600.1.6000716
2023/10/28 05:51:26 version.go:40: Got WindowsPlayer version version-faaebc838e2e45f6
2023/10/28 05:51:26 binary.go:262: WindowsPlayer is up to date (version-faaebc838e2e45f6)
2023/10/28 05:51:26 fflags.go:30: Applying custom FFlags
2023/10/28 05:51:26 dxvk.go:20: Enabling DXVK DLL overrides
2023/10/28 05:51:26 binary.go:96: Launching WindowsPlayer
2023/10/28 05:51:26 exec.go:51: Starting command: /app/bin/wine /home/YuuyaKZMI/.var/app/io.github.vinegarhq.Vinegar/data/vinegar/prefix/vinegar/versions/version-faaebc838e2e45f6/RobloxPlayerBeta.exe roblox-player:1+launchmode:play+gameinfo:WcuXKUVALNOvPWnvs59pz9W0fbiGNVJBr8p-6yAW-pqyLXAyMkYhu8Z-SEIM57ZqDrDEhDqhLHBDie_7fRDsNVAAXTPNVHpFiUs8UQ2AgSrpz3gkwYxlbyAUFFprnvCm3W4V1P7bwELQMqw8--CwY8KiE42JCxqfeDAd0gBJFhOcQdv-gwZQb8BvdnfmEJcZz7QJ2AyqtZ8E2cWfojWRVbvsJDt3ClK4thqKztXytdM+launchtime:1698486686346+placelauncherurl:https%3A%2F%2Fassetgame.roblox.com%2Fgame%2FPlaceLauncher.ashx%3Frequest%3DRequestGame%26browserTrackerId%3D197741173470%26placeId%3D7041939546%26isPlayTogetherGame%3Dfalse%26joinAttemptId%3Dcb7bcff7-bfca-461a-a04e-4e2b769f98d7%26joinAttemptOrigin%3DPlayButton+browsertrackerid:197741173470+robloxLocale:en_us+gameLocale:en_us+channel:
2023/10/28 05:51:26 discordrpc.go:16: Authenticating Discord RPC
2023/10/28 05:51:26 binary.go:134: Failed to authenticate Discord RPC: dial unix /run/user/1000/discord-ipc-0: connect: no such file or directory, disabling RPC
0448:fixme:ntdll:NtRaiseHardError c0000005 stub
2023/10/28 05:51:30 discordrpc.go:21: Deauthenticating Discord RPC
2023/10/28 05:51:30 vinegar.go:113: roblox process: exit status 87`

The obvious problem is the failure to authenticate Discord RPC through a file/directory missing.

My questions are:

1. How do I fix this?
2. Why is Discord RPC even necessary for Roblox?

**Comment by apprehensions** [comment]
no its not, roblox failed to run. it is not a failure, as the last error clearly states 'exit status 87'

if you read the documentation, it will state that it can be disabled.

**Comment by EpitaphEpitome** [comment]
I disagree, since this crash never happened before this update, and it's clear RPC is what caused the problem.
And your response didn't answer my question as to why RPC was added in the first place.

**Comment by apprehensions** [comment]
it is a feature. disable it with:
```
[player]
discord_rpc = false
```
if you do not believe me.

This is not because of Vinegar. Roblox has been very unstable the past few days and will crash. Please read #236

**Comment by EpitaphEpitome** [comment]
Alright, either way, I still want my answer as to why it was necessary to implement it regardless.

(I'd recommend setting the default to "false", too.)

**Comment by EpitaphEpitome** [comment]
Seems like with the fixes shown that it works again. Honestly, apologies for the haste and misunderstanding.
