### ISSUE TITLE
Text is a little blurry.

### ISSUE THREAD

**Issue by Sasha-Acoiners** [vinegarhq/vinegar#243]
So, I've tried looking this up, but I have not seen anybody talk about it. For some reason, text in Vinegar is a little blurry for me. Not to an extreme extend or anything, but it is an issue that I didn't have in Grapejuice. I switched over to Vinegar recently, as people have said it generally works better, and it absolutely does (for me at least. On Grapejuice, Roblox would pretty much break the prefix anytime it updated. Was super annoying) I didn't really think much of the blurry text until I played the game "World Zero" and I noticed that character dialogue (the stuff that gets displayed above character heads) is cut off. For instance, one of the characters is supposed to say "Help me!" but all it said was "Help" So, I feel like these two things may be connected. I haven't noticed it happen in any other games, but I felt like it was worth bringing up. Anyways, any insight on this would be greatly appreciated. I'll put my full specs here just in case.

Vinegar package: Flatpak

OS: Fedora 39 KDE

GPU: AMD Radeon RX 6600

CPU: i7-11700 @ 2.50GHz

RAM: 16GB

I've included three images below. The first one is how the text looks in the app, the second one is how the text looks in a web browser, and the third one is an example of the game "World Zero" where some text is being cut off. The text in the game is supposed to read something along the lines of "You'll get stronger the more monsters you slay"

![Screenshot_20231029_063903](https://github.com/vinegarhq/vinegar/assets/138019883/87dfe8ba-724f-4d8e-9e2c-c95de96a362d)

![Screenshot_20231029_063923](https://github.com/vinegarhq/vinegar/assets/138019883/11ce9879-1bf0-4c24-b861-dc5882a32f0f)

![Screenshot_20231029_064103](https://github.com/vinegarhq/vinegar/assets/138019883/90e42637-4a3b-411e-b262-39a2b90ce1ef)

Also, I apologize if this post isn't formatted extremely well, I'm not very good at this stuff, but I've tried to put as much info as possible. Any help would be greatly appreciated, thank you very much.

**Comment by apprehensions** [comment]
This is due to the fact that we set the DPI to 97. We set it to 97 as Studio will crash with the Wine default DPI of 96.

If you would like to change it: `vinegar exec winecfg` and head to Graphics; you will see the DPI slider there.
