### ISSUE TITLE
My roblox doens't stop crashing after 2 minutes

### ISSUE THREAD

**Issue by DNKES1** [vinegarhq/vinegar#245]
apparently, i can only play Roblox for **2 MINUTES** , first, it freezes, then after 5 seconds, it doens't respond anymore and i'm forced to close it, seems like **it's also affecting windows and linux players.** **I use Pop_Os**, is there anything i can do to fix it?

**Comment by lokiran2** [comment]
Use in flatpak run io.github.vinegarhq.Vinegar edit 
[player]
channel = "zavatarteam"
If you encounter the same problem as me, which is updating every minute, then use this command
forced_version="version-d57eb1ca92e94411"
under
[player]
channel = "zavatarteam"

**Comment by statulr** [comment]
> forced_version="version-d57eb1ca92e94411"

That doesn't work ether unfortunately

**Comment by statulr** [comment]
Nevermind it works perfect thank you @lokiran2

**Comment by Thelolguy1** [comment]
Merged with #236
