### ISSUE TITLE
White screen with Vulkan

### ISSUE THREAD

**Issue by spenkluker645** [vinegarhq/vinegar#247]
When trying to play Roblox with Vulkan without DXVK,  there is a white screen, When playing with DXVK, game works but is extremely laggy.

More info in issue #230

**Comment by spenkluker645** [comment]
![image](https://github.com/vinegarhq/vinegar/assets/114310071/5d77b54c-8dca-4a71-8ffd-3e632f3ed7e6)

**Comment by Thelolguy1** [comment]
You are using software rendering.

**Comment by Noted-Jrelvas** [comment]
@Thelolguy1 OP should consider a dual Xeon Platinum 8490H setup for improved software rendering performance.

**Comment by spenkluker645** [comment]
Thanks i didnt realize my flatpak drivers were broken
