### ISSUE TITLE
white screen with dxvk disable

### ISSUE THREAD

**Issue by starzation** [vinegarhq/vinegar#248]
First i try run vinegar with dxvk enable and roblox is not open and here is log: [vinegar-without-dxvk-err](https://paste.sr.ht/~starzation/f3cec794904eb38d4e006fec18707bdd3c7309bd)

And when i disable dxvk roblox is work fine the game is launch and working (know by sound and game console log) but the screen is white

**Comment by jojommeke** [comment]
same problem here

**Comment by jojommeke** [comment]
I think i found the solution:
try updating your drivers with
`flatpak update` (cntrl+alt+t to open terminal)

if this helped you, react with a thumsup
have a great day!

**Comment by starzation** [comment]
@jojommeke Can i ask you something 

Are you using nvidia or amd?
What version of vinegar did you use?

**Comment by RAN6O** [comment]
> I think i found the solution: try updating your drivers with `flatpak update` (cntrl+alt+t to open terminal)
> 
> if this helped you, react with a thumbsup have a great day!

This really helped me, thank you so much
