### ISSUE TITLE
Roblox studio crashes immediately when creating a new place or opening an existing one

### ISSUE THREAD

**Issue by expoodo** [vinegarhq/vinegar#250]
[log file](https://github.com/vinegarhq/vinegar/files/13209879/studio-2023-10-30T17.07.06-04.00.log)

[config file](https://github.com/vinegarhq/vinegar/files/13209893/config.txt)

Using flatpak version 1.5.4 
OS: linux mint 21.2
Kernel: 6.2.0-36-generic
Specs: AMD fx-6100, AMD rx-580, 16 gb ram, 1080p monitor

**Comment by DNKES1** [comment]
bro it already says that roblox studio crashes on the vinegar downloading web

**Comment by expoodo** [comment]
> bro it already says that roblox studio crashes on the vinegar downloading web

what are you trying to say...?

**Comment by Y1rd** [comment]
If you already have an existing place, I've had luck opening it via the creator hub, then click "Edit in Studio".
Otherwise, yeah.
