### ISSUE TITLE
Remove option for channels

### ISSUE THREAD

**Issue by MojaveMF** [vinegarhq/vinegar#253]
Roblox has recently pushed an update breaking lots of channels

cant use
https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zCanary
https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zavatarteam2

etc ..

this repo has also removed all of these
https://github.com/MaximumADHD/Roblox-Client-Tracker

The only purpouse of channels in vinegar are dead code now

**Comment by Sasha-Acoiners** [comment]
I was WONDERING why Roblox wasn't launching these past few hours. Thankfully, it seems like the "freezing after a few minutes of play" is no longer an issue on the live channel, as I've just tested for a few minutes, and it didn't freeze. But yeah, if those channels no longer exist, there is no reason in keeping that code.

**Comment by MeemeeLab** [comment]
I was curious about this, and I found out version file on setup.rbxcdn.com was still alive, not clientsettingscdn.

For example, zavatarteam2:
Player version: https://setup.rbxcdn.com/channel/zavatarteam2/version
Studio version: https://setup.rbxcdn.com/channel/zavatarteam2/versionQTStudio

And it still works... kinda.
![image](https://github.com/vinegarhq/vinegar/assets/57629983/1defc037-0d23-4724-b456-c53539e1c2c1)

Probably they noticed that we are using zavatarteam for unintended purpose and they disabled wine entirely

So channel options can be fixed to make it work again, but zavatarteam2 does not work (there's might be a channels that works with wine)

**Comment by Thelolguy1** [comment]
Our plan is to keep channel selector for the foreseeable future.
