### ISSUE TITLE
I can't open roblox: "Failed to setup roblox"

### ISSUE THREAD

**Issue by imatePGu** [vinegarhq/vinegar#255]
Here is my log:
2023/11/03 06:31:52 version.go:54: Fetching latest version of WindowsPlayer 
2023/11/03 06:31:52 api.go:22: Performing Roblox API GET clientsettings request on v2/client-version/WindowsPlayer/channel/zavatarteam2
2023/11/03 06:31:52 vinegar.go:113: response code 5: Not authorized to perform this action.

If you know how to fix pls help.

**Comment by apprehensions** [comment]
There is no fix. Roblox has now locked down all channels except LIVE. Please remove the `channel` entry in your configuration.
