### ISSUE TITLE
"0108:fixme:ntdll:NtRaiseHardError c0000005 stub"

### ISSUE THREAD

**Issue by imatePGu** [vinegarhq/vinegar#256]
Here is my log, maybe someone can help:
2023/11/03 11:32:58 version.go:45: Fetching latest version of WindowsPlayer for channel live
2023/11/03 11:32:58 api.go:22: Performing Roblox API GET clientsettings request on v2/client-version/WindowsPlayer/channel/live
2023/11/03 11:32:58 version.go:52: Fetched WindowsPlayer canonical version 0.601.0.6010507
2023/11/03 11:32:58 version.go:31: Got WindowsPlayer version version-6f0b02756d914e3e with channel live
2023/11/03 11:32:58 binary.go:243: WindowsPlayer is up to date (version-6f0b02756d914e3e)
2023/11/03 11:32:58 fflags.go:30: Applying custom FFlags
2023/11/03 11:32:58 discordrpc.go:16: Authenticating Discord RPC
2023/11/03 11:32:58 binary.go:122: Launching WindowsPlayer
2023/11/03 11:32:58 cmd.go:74: Starting command: /usr/bin/wine /home/imate/.local/share/vinegar/prefix/vinegar/versions/version-6f0b02756d914e3e/RobloxPlayerBeta.exe
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0108:fixme:ntdll:NtRaiseHardError c0000005 stub
2023/11/03 11:33:03 discordrpc.go:21: Deauthenticating Discord RPC
2023/11/03 11:33:03 vinegar.go:177: roblox process: exit status 4
2023/11/03 11:33:09 splash.go:141: Opening log file: /home/imate/.cache/vinegar/logs/Player-2023-11-03T11:32:58+01:00.log
2023/11/03 11:33:30 splash.go:141: Opening log file: /h

**Comment by apprehensions** [comment]
`vinegar sysinfo`

**Comment by imatePGu** [comment]
> `vinegar sysinfo`

vinegar sysinfo
2023/11/03 11:49:05 config.go:57: Using default configuration
## System information
* Distro: Arch Linux 
* Processor: AMD Ryzen 3 3100 4-Core Processor
  * Supports AVX: true
* Kernel: 6.6.0-x64v3-xanmod1
* Wine: wine-8.19
* Cards:
  * Card 0: nvidia /sys/class/drm/card0
[imate@hacker ~]$

**Comment by apprehensions** [comment]
that's interesting..

**Comment by apprehensions** [comment]
According to a user on the VinegarHQ discord, this can be solved by switching to the Flatpak distribution.

**Comment by imatePGu** [comment]
thanks

**Comment by Infinixius** [comment]
Installing on Flatpak worked perfectly on Arch Linux, got the same error as @imatePGu using the AUR package.
