### ISSUE TITLE
Implement WINE_HOME, like grapejuice

### ISSUE THREAD

**Issue by PetrifiedOak** [vinegarhq/vinegar#26]
This would be really nice.

I prefer not to compile wine for LFH, if this gets implemented ill just  be able to use a precompiled wine, without having to symlink/replace /usr/bin/wine

Thisll make it alot more plug-n-play too.

**Comment by apprehensions** [comment]
@Thelolguy1's thoughts on the situation:
> don't write to users' winehome, mainly for security purposes.

> keep it simple
> keep 1 prefix

**Comment by Thelolguy1** [comment]
additionally wine-staging is now LFH soooooooo

**Comment by apprehensions** [comment]
how

**Comment by Thelolguy1** [comment]
wine-staging is 8.2 which has lfh

**Comment by apprehensions** [comment]
it does not have lfh yet

**Comment by PetrifiedOak** [comment]
wine 8.3 has LFH, no need for a patched wine
