### ISSUE TITLE
Add configuration for custom Wine executable

### ISSUE THREAD

**Issue by SergSel2006** [vinegarhq/vinegar#261]
So, I've just tried to use custom wine executable in vinegar by using `[env]` to override PATH, but this didn't work for some reason and still, using this method sometimes confuse me. 
What I would like is something like `wineexec="/path/to/custom/wine"` in player, studio and global configurations. This will simplify the configuration a little, and make the problem with roblox making memory dump a less easier to workaround.

This might be easy, but unfortunately, I don't know how to code in Go

**Comment by apprehensions** [comment]
What sort of usecase would this provide? The only useful one that i've yet to implement is `wine64`. Maybe this is for proton?

**Comment by SergSel2006** [comment]
Usecases: many wine custom builds are installed in /opt or another user selected directory along with system Wine, making it a little complicated now.
To use GE version of wine I would need to change environment variable, or I would want to use wine from Lutris for Fsync, for example, it would also require to change environment variable. This would be easier.

**Comment by apprehensions** [comment]
If a wine installation is set to /opt, can't you just set the wineroot to it?

**Comment by SergSel2006** [comment]
Well, this is true, but it's unclear what do you mean by "Root" in documentation. I thought you meant wine prefixes root. It might be something like "A path to a valid directory where wine is installed".
I think there's nothing to discuss now and closing the issue. I'm sorry if I distracted you from more important things.

**Comment by apprehensions** [comment]
it ok :D
