### ISSUE TITLE
Crashes after a few seconds

### ISSUE THREAD

**Issue by mak448a** [vinegarhq/vinegar#264]
After launching the app with `flatpak run io.github.vinegarhq.Vinegar player`, it crashes after a few seconds. If this helps, Roblox was working fine on my system a few days ago. I also tried grapejuice launcher, which did work.

Fedora 38 KDE Spin
Wayland

**Comment by statulr** [comment]
Try now, and use live or ZMousse

**Comment by statulr** [comment]
*ZFlag

**Comment by apprehensions** [comment]
LIVE and Roblox is generally currently unstable.
