### ISSUE TITLE
fps doesn't unlock on roblox LIVE

### ISSUE THREAD

**Issue by Noobitee** [vinegarhq/vinegar#266]
Distro : Arch Linux installed via archinstall
Vinegar install method : chaotic-aur repository
mesa : mesa-tkg-git 24.0.0
GPU : AMD RX 6700XT
Performance booster : CoreCtrl and amdgpufeaturemask

My vinegar configuration out of the box and even after I configured it, doesn't change that my roblox player fps is bad

![2023-11-10_19-45](https://github.com/vinegarhq/vinegar/assets/125382035/9bcd76ae-3198-4556-8eef-279e53d5a07d)

![2023-11-10_19-46](https://github.com/vinegarhq/vinegar/assets/125382035/2a1908e4-891f-4738-89a0-8bcf2a994109)

![image](https://github.com/vinegarhq/vinegar/assets/125382035/6b926948-31d7-40ea-b26d-e5db05ce5226)

**Comment by apprehensions** [comment]
fps being greater than 60 means it is unlocked. Roblox currently on LIVE is facing bad performance.
