### ISSUE TITLE
SwapBuffer error on initialization (eglSwapBuffers failed (3008))

### ISSUE THREAD

**Issue by TrulySc** [vinegarhq/vinegar#268]
#### Describe the bug
After editing the configuration file in any way (this includes just metadata), vinegar will error with eglSwapBuffers failed consistently until all traces of vinegar's wineprefix is wiped and the config file is recreated.

#### To Reproduce
Use NVIDIA proprietary drivers
try to open, install, or in any way interact with Roblox player/studio through vinegar

### Logs
```
version.go:45: Fetching latest version of WindowsPlayer for channel live
api.go:22: Performing Roblox API GET clientsettings request on v2/client-version/WindowsPlayer/channel/live
vinegar.go:162: splash: eglSwapBuffers failed (3008)
```
### System information
Vinegar version 1.5.8 (tested with both flatpak and aur)
wayland (1.22.0)
KDE Plasma 5 
NVIDIA Proprietary drivers/utils (545 stable, also tested with 545 beta, 535, 525)
egl-wayland (1.1.13)
wine-ge-8.0 (also tested with base wine)
btrfs filesystem on SATA ssd

* Installation method:
## System information
* Distro: Arch Linux 
* Processor: AMD Ryzen 7 3800XT 8-Core Processor
  * Supports AVX: true
* Kernel: 6.5.11-lqx1-1-lqx
* Wine: wine-ge-8.0 (Staging)
* Cards:
  * Card 0: nvidia /sys/class/drm/card0

#### Additional context

Also of note is journalctl, which does complain that egl cannot initialize a dri2 screen.
`libEGL warning: egl: failed to create dri2 screen`

This is obviously an issue on my own end (or upstream from either NVIDIA or KDE not correctly defaulting this, or my own incompetence) but Vinegar's init failure only occurs when the config file has been edited in any way.

This may be slightly off topic, but part of me wonders if this egl error only being present after editing the config is related to #260 in any way as I currently still suffer from this issue myself.

**Comment by TrulySc** [comment]
Figured out the cause, the enviroment variable `EGL_PLATFORM` is not set by default. If the proper boot params are set to enable NVIDIA's DRM, this needs to be set as `drm`.

Sorry for not checking this earlier, one thing that slipped my mind.

**Comment by TheComputerGuy96** [comment]
@TrulySc I think setting that variable effectively disables the NVIDIA driver

**Comment by TrulySc** [comment]
> @TrulySc I think setting that variable effectively disables the NVIDIA driver

@TheComputerGuy96 Not sure on this, I took the past hour to look into it but I can't see any issues that I didn't already have without the variable. Do you have any examples? Not doubting you at all, just trying to cross reference here.

**Comment by pelaajahacks** [comment]
For some reason it works when using the flatpak...

**Comment by apprehensions** [comment]
Because the flatpak has no Wayland support. This issue is caused by Nvidia's egl-wayland.
