### ISSUE TITLE
Vinegar crashing upon launch

### ISSUE THREAD

**Issue by devastate347** [vinegarhq/vinegar#270]
Vinegar crashes upon opening with the error message of `002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).` whenever I run it through `flatpak run io.github.vinegarhq.Vinegar player`

Whenever I try to launch through the Roblox website it doesn't even launch, the loading bar goes all the way and then I get a wine popup that says Roblox encountered an unexpected error

**Comment by apprehensions** [comment]
Vinegar is not crashing. That error is harmless. The real error here is `Roblox encountered an unexpected error`. Which is roblox crashing, not Vinegar. 

Duplicate of #199
