### ISSUE TITLE
vinegar stuck at "launching player"

### ISSUE THREAD

**Issue by w4lll** [vinegarhq/vinegar#272]
#### Describe the bug
Vinegar just stuck at "Launching Player" instead of launching roblox player.

#### To Reproduce
Run the flatpak run io.github.vinegarhq.Vinegar player after installling using flatpak.

### Logs
```
2023/11/16 11:12:22 logs.go:27: Logging to file: /home/w4l/.var/app/io.github.vinegarhq.Vinegar/cache/vinegar/logs/Player-2023-11-16T11:12:22Z.log
2023/11/16 11:12:22 version.go:45: Fetching latest version of WindowsPlayer for channel live
2023/11/16 11:12:22 api.go:22: Performing Roblox API GET clientsettings request on v2/client-version/WindowsPlayer/channel/live
2023/11/16 11:12:23 version.go:52: Fetched WindowsPlayer canonical version 0.603.0.6030563
2023/11/16 11:12:23 version.go:31: Got WindowsPlayer version version-8390cf89d2c74e62 with channel live
2023/11/16 11:12:23 binary.go:243: WindowsPlayer is up to date (version-8390cf89d2c74e62)
2023/11/16 11:12:23 fflags.go:85: Using renderer: D3D11
2023/11/16 11:12:23 fflags.go:30: Applying custom FFlags
2023/11/16 11:12:23 dxvk.go:20: Enabling WINE DXVK DLL overrides
2023/11/16 11:12:23 discordrpc.go:16: Authenticating Discord RPC
2023/11/16 11:12:23 binary.go:80: WARNING: Could not initialize Discord RPC: dial unix /run/user/1000/discord-ipc-0: connect: no such file or directory, disabling...
2023/11/16 11:12:23 binary.go:122: Launching WindowsPlayer
2023/11/16 11:12:23 cmd.go:74: Starting command: /app/bin/wine /home/w4l/.var/app/io.github.vinegarhq.Vinegar/data/vinegar/prefix/vinegar/versions/version-8390cf89d2c74e62/RobloxPlayerBeta.exe
esync: up and running.
002c:fixme:winediag:loader_init wine-staging 8.18 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
0054:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\MountMgr": c0000135
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"MountMgr" failed to start: 126
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
Fontconfig error: "/etc/fonts/conf.d/57-dejavu-serif.conf", line 1: not well-formed (invalid token)
Fontconfig error: "/etc/fonts/conf.d/57-dejavu-serif.conf", line 1: not well-formed (invalid token)
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
Fontconfig error: "/etc/fonts/conf.d/57-dejavu-serif.conf", line 1: not well-formed (invalid token)
Fontconfig error: "/etc/fonts/conf.d/57-dejavu-serif.conf", line 1: not well-formed (invalid token)
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
00f0:fixme:bitmap:NtGdiCreateBitmap planes = 0
```

### System information

Arch Linux amd64, Xorg window manager with i3wm, nvidia graphics card, kernel version 6.6.1

* Installation method:
   Installed using the flatpak.

#### Additional context
* Launched vinegar using the `flatpak run` command and stuck at "Launching Player"
* When using the AUR version, the roblox crashed with this error "Roblox encountered an unexpected error"
* Flatpak couldn't update the vinegar app with this error: `Error: While pulling app/io.github.vinegarhq.Vinegar/x86_64/stable from remote flathub: opcode set-read-source: Opening content object aa3e07ef804c0bfc0278c8d1aa2bebfcd8b8376211f75cf8e1c3fe3bba733d7f: Opening content object aa3e07ef804c0bfc0278c8d1aa2bebfcd8b8376211f75cf8e1c3fe3bba733d7f: Couldn't find file object 'aa3e07ef804c0bfc0278c8d1aa2bebfcd8b8376211f75cf8e1c3fe3bba733d7f'`.

**Comment by apprehensions** [comment]
`flatpak uninstall io.github.vinegarhq.Vinegar --delete-data`, answer "y" at the prompt, `flatpak repair`, `flatpak install io.github.vinegarhq.Vinegar`

**Comment by w4lll** [comment]
> `flatpak uninstall io.github.vinegarhq.Vinegar --delete-data`, answer "y" at the prompt, `flatpak repair`, `flatpak install io.github.vinegarhq.Vinegar`

Flatpak still couldn't install vinegar with this error: `Error: While pulling app/io.github.vinegarhq.Vinegar/x86_64/stable from remote flathub: opcode set-read-source: Opening content object aa3e07ef804c0bfc0278c8d1aa2bebfcd8b8376211f75cf8e1c3fe3bba733d7f: Opening content object aa3e07ef804c0bfc0278c8d1aa2bebfcd8b8376211f75cf8e1c3fe3bba733d7f: Couldn't find file object 'aa3e07ef804c0bfc0278c8d1aa2bebfcd8b8376211f75cf8e1c3fe3bba733d7f'`

**Comment by lokiran2** [comment]
how i can slove it ??

**Comment by lunarlettuce** [comment]
@w4lll something is very iffy with your flatpak installation. double check that your remotes are set correctly?

**Comment by w4lll** [comment]
> @w4lll something is very iffy with your flatpak installation. double check that your remotes are set correctly?

i didn't configure any remotes in flatpak since i installed flatpak. planning to reinstall arch since some programs didn't work `Segmentation fault (core dumped)`.

**Comment by w4lll** [comment]
my hdd is now unusable, probally broken. uefi bios didn't detect my hdd.
