### ISSUE TITLE
Ran into a "duplicate"? error

### ISSUE THREAD

**Issue by Renen12** [vinegarhq/vinegar#273]
I am writing a port for the scratchpkg package manager for vinegar.
scratchpkg is basically a script that compiles packages from a repository, it's a little bit like an aur for gentoo.
When running roblox I get the error:
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
and 00cc:fixme:ntdll:NtRaiseHardError c0000005 stub
I have seen another closed issue describing this exact behavior, but that issue seems to have been fixed in a new vinegar version: [https://github.com/vinegarhq/vinegar/issues/186](url)

You can try to reproduce this issue with venom linux(the distribution that scratchpkg is used in) or install scratchpkg with the instructions provided in this repository: https://github.com/venomlinux/scratchpkg
Here is the spkgbuild: 
[vinegar.tar.gz](https://github.com/vinegarhq/vinegar/files/13402570/vinegar.tar.gz)
Note that you have to put the spkgbuild in a directory named vinegar to satisfy scratchpkg

Here are the logs:
[Player-2023-11-19T08:33:29+01:00.log](https://github.com/vinegarhq/vinegar/files/13402573/Player-2023-11-19T08.33.29%2B01.00.log)

I also run venom linux currently, I haven't compiled scratchpkg on another distro.

Here is my vinegar sysinfo:
* Distro: Venom Linux rolling rolling
* Processor: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  * Supports AVX: true
* Kernel: 6.6.1-Venom
* Wine: wine-8.20
* Cards:
  * Card 0: i915 /sys/class/drm/card0
Edit: Accidentally added the bug label and I have no idea how to remove it now.
Thanks in advance!

**Comment by apprehensions** [comment]
Roblox on Wine may require additional patches (ontop of Staging) to be able to run properly. 
https://github.com/flathub/io.github.vinegarhq.Vinegar/tree/master/patches/wine Those patches are applied with the Flatpak distribution of Vinegar.

**Comment by Renen12** [comment]
Ok, thank you!

**Comment by Renen12** [comment]
On what files should I apply the patches?
