### ISSUE TITLE
Memory dump error (ive tried everything, i think atleast)

### ISSUE THREAD

**Issue by poopsockman** [vinegarhq/vinegar#276]
#### Describe the bug
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported yes i have

A clear and concise description of what the bug is. It says memory dump for the error and it says Roblox has ran into an unexpected error.

#### To Reproduce
Steps to reproduce the behavior. I've tried every bootstrapper for roblox and it dont work.

### Logs
Reference log file contents, which are usually located in `~/.cache/vinegar/logs` or `~/..var/app/io.github.vinegarhq.Vinegar/cache/vinegar/logs/` for Flatpak, of a run reproducing the bug

### System information

* Installation method:
  first i install the 8.15 wine developmental version then i install vinegar and i still get the same error even with all the steps followed.

#### Additional context

Ive tried wine by itself, ive tried corky, ive tried any other bootstrapper including vinegar before and i always get the memory dump error also my graphics card info is:

description: Display controller
       product: Virtio GPU
       vendor: Red Hat, Inc.
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 01
       width: 64 bits
       clock: 33MHz
       capabilities: bus_master cap_list
       configuration: driver=virtio-pci latency=0
       resources: iomemory:40-3f irq:10 memory:d0808000-d080ffff memory:400000000-5ffffffff uhhh i think its bad

also for 5 days straight ive tried relentlessy to get roblox working but it has NEVER worked it would mean da world to me if someone would figure dis out :)

**Comment by poopsockman** [comment]
also im trying to do this using chrome on chrome os not any linux operating system, but i think it can still work

**Comment by apprehensions** [comment]
Previous issues indicate this problem is solved by using the Flatpak, which has a special version of wine which makes Roblox run without issues.

**Comment by poopsockman** [comment]
uhh what do you mean? also im new to linux after my school unblocked it

**Comment by poopsockman** [comment]
also i did use the flatpak, it dosent work for me :(

**Comment by poopsockman** [comment]
oh wait i didnt try vinegar Alone

**Comment by poopsockman** [comment]
i try

**Comment by poopsockman** [comment]
still dosent work :(

**Comment by MatheusMA678** [comment]
I'm having the same bug using flatpak version

OS: Fedora 39
WM: Gnome 45.1

**Comment by poopsockman** [comment]
yea it dont work i think cuz like i have enough memory but i think it dont work because roblox dosent like wine, and even with the stuff people recommended it legit did the same exact error :(

**Comment by poopsockman** [comment]
i found a video but idk if it works its from 2 weeks ago https://www.youtube.com/watch?v=kH1C-BUa-tg&ab_channel=Deep-Sea

**Comment by poopsockman** [comment]
ohhh vinegar dosen't work cuz vinegar having problems rn for some reason

**Comment by apprehensions** [comment]
@poopsockman @MatheusMA678 Please share the output of `vinegar sysinfo`. Replace the command with the flatpak equivalent as necessary, as the original issue creator has not supplied it.

**Comment by MatheusMA678** [comment]
> @poopsockman @MatheusMA678 Please share the output of `vinegar sysinfo`. Replace the command with the flatpak equivalent as necessary, as the original issue creator has not supplied it.

## System information
* Distro: Freedesktop.org SDK 23.08 (Flatpak runtime) 23.08
* Processor: Pentium(R) Dual-Core CPU       T4300  @ 2.10GHz
  * Supports AVX: false
* Kernel: 6.5.11-300.fc39.x86_64
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: i915 /sys/class/drm/card0

**Comment by poopsockman** [comment]
uhh mine says vinegar command not found even though i have it installed

**Comment by poopsockman** [comment]
wait lemme try smth

**Comment by poopsockman** [comment]
yea that command dosent work for me but i have both apps and im on a chrome os chromebook

**Comment by apprehensions** [comment]
We do not support chromebooks.

@MatheusMA678 Unfortunately, your machine cannot run Roblox, as it lacks AVX.

**Comment by poopsockman** [comment]
does grapejuice support chromebook?

**Comment by apprehensions** [comment]
No

**Comment by poopsockman** [comment]
NOOOo

**Comment by poopsockman** [comment]
oh welp okay thx now i can end this sisyphus quest

**Comment by MatheusMA678** [comment]
> We do not support chromebooks.
> 
> @MatheusMA678 Unfortunately, your machine cannot run Roblox, as it lacks AVX.

i'm don't have a chromebook, is a notebook. Roblox runs normally on Windows, but on Linux with Vinegar, doesn't run.

**Comment by apprehensions** [comment]
Yes, this is due to the lack of AVX, which gives us a good idea of which machines can and cant run roblox.

I don't know what exactly is the reason, but it is a common factor.

**Comment by poopsockman** [comment]
do u guys know any bootstrappers that can install roblox for me cuz im using the linux terminal and flathub and stuff

**Comment by poopsockman** [comment]
i cant install the linux operating systems because i dont have a bootable usb

**Comment by MatheusMA678** [comment]
> Yes, this is due to the lack of AVX, which gives us a good idea of which machines can and cant run roblox.
> 
> I don't know what exactly is the reason, but it is a common factor.

Ok, thanks for the help.

**Comment by apprehensions** [comment]
@poopsockman Please continue discussion on the VinegarHQ discord server.
