### ISSUE TITLE
Error when starting Roblox Studio

### ISSUE THREAD

**Issue by KevDevCaita** [vinegarhq/vinegar#280]
Roblox Studio opens the logo, but like after 15 seconds, crashes

### Logs
[Studio-2023-11-22T16:00:57-05:00.log](https://github.com/vinegarhq/vinegar/files/13444479/Studio-2023-11-22T16.00.57-05.00.log)

### System information
* Distro: Freedesktop.org SDK 23.08 (Flatpak runtime) 23.08 or Linux Mint
* Processor: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  * Supports AVX: true
* Kernel: 6.5.11-x64v3-xanmod1
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: i915 /sys/class/drm/card0

**Comment by Cristiandis** [comment]
What renderer and wine are you using

**Comment by KevDevCaita** [comment]
> What renderer and wine are you using
Wine: v8.18 (Staging)
I'm using default renderer, i just installed vinegar and started Roblox Studio

**Comment by Cristiandis** [comment]
> > What renderer and wine are you using
> 
> Wine: v8.18 (Staging) I'm using default renderer, i just installed vinegar and started Roblox Studio

Sorry for late response.
The default for studio i believe is d3d11 ehich requires a special wine patch called "childwindow" to work, you can get it by building tkg, or you could change renderers to opengl

**Comment by Cristiandis** [comment]
You're not using flatpak?

**Comment by KevDevCaita** [comment]
> > > What renderer and wine are you using
> > 
> > 
> > Wine: v8.18 (Staging) I'm using default renderer, i just installed vinegar and started Roblox Studio
> 
> Sorry for late response. The default for studio i believe is d3d11 which requires a special wine patch called "childwindow" to work, you can get it by building tkg, or you could change renderer to opengl

How do i change to opengl?

**Comment by KevDevCaita** [comment]
> You're not using flatpak?

yeah

**Comment by Noted-Jrelvas** [comment]
> The default for studio i believe is d3d11 which requires a special wine patch called "childwindow" to work, you can get it by building tkg, or you could change renderer to opengl

@Cristiandis Using the OpenGL is really not recommended due to its overwhelming amount of bugs and instability issues.

**Comment by KevDevCaita** [comment]
> > The default for studio i believe is d3d11 which requires a special wine patch called "childwindow" to work, you can get it by building tkg, or you could change renderer to opengl
> 
> @Cristiandis Using the OpenGL renderer in studio is really not recommended due to its overwhelming amount of bugs and instability issues. To the point where you might be better off using lvmmpipe.

Thanks! But idk how to change and install it?

**Comment by Cristiandis** [comment]
> > > The default for studio i believe is d3d11 which requires a special wine patch called "childwindow" to work, you can get it by building tkg, or you could change renderer to opengl
> > 
> > 
> > @Cristiandis Using the OpenGL renderer in studio is really not recommended due to its overwhelming amount of bugs and instability issues. To the point where you might be better off using lvmmpipe.
> 
> Thanks! But idk how to change and install it?

Easy way is to install flatpak version, hard way is to compile wine-tkg

**Comment by KevDevCaita** [comment]
> > > > The default for studio i believe is d3d11 which requires a special wine patch called "childwindow" to work, you can get it by building tkg, or you could change renderer to opengl
> > > 
> > > 
> > > @Cristiandis Using the OpenGL renderer in studio is really not recommended due to its overwhelming amount of bugs and instability issues. To the point where you might be better off using lvmmpipe.
> > 
> > 
> > Thanks! But idk how to change and install it?
> 
> Easy way is to install flatpak version, hard way is to compile wine-tkg

I'm using flatpak version, but where's the render file?

**Comment by Noted-Jrelvas** [comment]
> Easy way is to install flatpak version, hard way is to compile wine-tkg
@Cristiandis 

User is on Vinegar's flatpak, as shown by sysinfo.

> Thanks! But idk how to change and install it?

We should try figuring out what's causing the crash first. Could you run the following command `flatpak run io.github.vinegarhq.Vinegar winecfg` and check if your DPI is 96? If it is, try changing it to another value, like 97, and check if the crash still occurs.

![imagem](https://github.com/vinegarhq/vinegar/assets/55360900/8cf5edd3-1d16-4029-86f3-f9c41ac7e5af)

**Comment by KevDevCaita** [comment]
> > Easy way is to install flatpak version, hard way is to compile wine-tkg
> > @Cristiandis
> 
> User is on Vinegar's flatpak, as shown by sysinfo.
> 
> > Thanks! But idk how to change and install it?
> 
> We should try figuring out what's causing the crash first. Could you run the following command `flatpak run io.github.vinegarhq.Vinegar exec winecfg` and check if your DPI is 96? If it is, try changing it to another value, like 97, and check if the crash still occurs.
> 
> ![imagem](https://user-images.githubusercontent.com/55360900/285482065-8cf5edd3-1d16-4029-86f3-f9c41ac7e5af.png)

It worked, Thanks.

**Comment by Noted-Jrelvas** [comment]
@apprehensions @lunarlettuce Looks like we still need to set DPI to 97 for now. Any potential clues for why OP didn't get their DPI set right?
