### ISSUE TITLE
Add system notifications

### ISSUE THREAD

**Issue by Florennum** [vinegarhq/vinegar#283]
#### I want this because
i have balkan quality network and notifying me about roblox's status would be a nice addition because sometimes i forget that i have launched vinegar /s
(a picture of me updating the extra repo on arch with pacman with local mirrors)
![image](https://github.com/vinegarhq/vinegar/assets/95132822/4be0cf1f-2f96-4ab3-828f-32d8ffdbbdeb)

#### System notifications would be a nice addition
The system notifications may occur when roblox fails to launch and stuff
(concept using notify-send)
![image](https://github.com/vinegarhq/vinegar/assets/95132822/d959d0c4-c2bc-4208-a16f-235a3239935b)

### Config additions
with this new addition it would be nice to introduce a boolean key in the config called notify or something so it can be toggleable

### btw
yall can use[ beeep](https://github.com/gen2brain/beeep) for that

**Comment by apprehensions** [comment]
splash screen

**Comment by Florennum** [comment]
yes but the what if splash not focused?

**Comment by Noted-Jrelvas** [comment]
@apprehensions For the record, the bus package I'm introducing with the gamemode PR makes implementing notifications trivial. (You could probably count the amount of lines with your fingers [and maybe toes])

I think there's some maneuver room here. Please reopen this so OP has a chance to clarify their usecases.
