### ISSUE TITLE
Crash after ~4.5 hours of gamplay on the same server

### ISSUE THREAD

**Issue by Yeyito777** [vinegarhq/vinegar#285]
#### Describe the bug
Roblox crashes for no apparent reason and with no apparent warning after several hours of gameplay on the same server. (~4.5 hours)
After checking logs it appears to be a memory issue as suggested by the lines:
performanceControlCallback (level:1)
handleLowMemoryWarning - Free mem: <address>

This is consistent across multiple crashes and 
performanceControlCallback (level:1) can be seen getting all the way to level 4.

The game always crashes after this message.

#### To Reproduce
Log into a roblox server and play for about 5 hours WITHOUT leaving the server you're in. Roblox should have a high chance of crashing unexpectedly.

### Logs
<Check attachment
[Player-2023-11-25T12:31:10-05:00.log](https://github.com/vinegarhq/vinegar/files/13466001/Player-2023-11-25T12.31.10-05.00.log)
>

### System information
OS: Arch Linux

* Distro: Freedesktop.org SDK 23.08 (Flatpak runtime) 23.08
* Processor: AMD Ryzen 5 3600XT 6-Core Processor
  * Supports AVX: true
* Kernel: 6.6.1-arch1-1
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: amdgpu /sys/class/drm/card1

#### Additional context
This is normally not an issue since being on the same server for 5+ hours is not common, although sometimes I do want to leave my PC grinding overnight, only then does it become an issue.

**This is also consistent across other runners like Cork** which implies a bigger problem.

I was also fortunate enough to witness one of the crashes myself, there's no way to tell it's going to crash, it just happens spontaneously.

**Comment by Yeyito777** [comment]
Our best bet is just to wait for a roblox update then?

**Comment by Noted-Jrelvas** [comment]
Yeah, not much we can do about it. To be fair though, 4.5 hours is a long time, so just rejoin every four hours so. Shouldn't be a big deal.

**Comment by Yeyito777** [comment]
I researched more on this bug, and got the following information:

1. The memory leak happens on "UntrackedMemory" portion of the F9 menu
2. It steadily goes up until Vinegar is exited, it doesn't matter if you leave the server you're in, it appears to be a memory leak with roblox itself. This will keep going until your entire RAM is used up and inevitably roblox crashes.

**Comment by EsusQuitGames** [comment]
I have a memory leak as well, I have 16 gb of ram. 8gb free when it has just opened and it lasts mabe 4 hours.

**Comment by personman102** [comment]
should you even be on a server for 4.5 hours?

**Comment by apprehensions** [comment]
A true dedicated robloxian.
