### ISSUE TITLE
Error when using on Chromebook Debian Linux

### ISSUE THREAD

**Issue by H644b** [vinegarhq/vinegar#291]
#### Describe the bug
It says missing ntlm_auth problems may occur. Right after that roblox crashes saying Roblox has encountered an error.

#### To Reproduce
Use linux developer mode on chromebook and try to run the player.

### Logs
2023/12/06 12:05:54 version.go:45: Fetching latest version of WindowsPlayer for channel live
2023/12/06 12:05:54 api.go:22: Performing Roblox API GET clientsettings request on v2/client-version/WindowsPlayer/channel/live
2023/12/06 12:05:54 version.go:52: Fetched WindowsPlayer canonical version 0.604.0.6040509
2023/12/06 12:05:54 version.go:31: Got WindowsPlayer version version-07c83728577248bd with channel live
2023/12/06 12:05:54 binary.go:241: WindowsPlayer is up to date (version-07c83728577248bd)
2023/12/06 12:05:54 fflags.go:30: Applying custom FFlags
2023/12/06 12:05:54 dxvk.go:20: Enabling WINE DXVK DLL overrides
2023/12/06 12:05:54 discordrpc.go:16: Authenticating Discord RPC
2023/12/06 12:05:54 binary.go:80: WARNING: Could not initialize Discord RPC: dial unix /run/user/1000/discord-ipc-0: connect: no such file or directory, disabling...
2023/12/06 12:05:54 binary.go:122: Launching WindowsPlayer
2023/12/06 12:05:54 cmd.go:74: Starting command: /app/bin/wine /home/floppysloppy/.var/app/org.vinegarhq.Vinegar/data/vinegar/prefix/vinegar/versions/version-07c83728577248bd/RobloxPlayerBeta.exe
002c:fixme:winediag:loader_init wine-staging 8.18 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0110:fixme:ntdll:NtRaiseHardError c0000005 stub
0110:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0110:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0110:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
0110:fixme:dbghelp:elf_search_auxv can't find symbol in module
2023/12/06 12:06:11 vinegar.go:162: splash: window closed
2023/12/06 12:06:11 binary.go:110: Killing Roblox
2023/12/06 12:06:12 prefix.go:34: Killing wineprefix
2023/12/06 12:06:12 cmd.go:74: Starting command: /app/bin/wineserver -k
2023/12/06 12:06:12 vinegar.go:174: roblox process: signal: killed

* Installation method: Flathub

## System information
* Distro: Freedesktop SDK 23.08 (Flatpak runtime) 23.08
* Processor: Intel(R) Celeron(R) N4120 CPU @ 1.10GHz
  * Supports AVX: false
* Kernel: 5.15.103-17409-g07029265d738
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: virtio_gpu /sys/class/drm/card0

**Comment by apprehensions** [comment]
Your machine does not support AVX and is unable to run Roblox.
