### ISSUE TITLE
Is there any way to make two Roblox players run simultaneously?

### ISSUE THREAD

**Issue by SamuelEzequiasPlays** [vinegarhq/vinegar#292]
I've been trying to open two Roblox at the same time but it always gives an error, I don't know if this has to do with the wineservers or something else

I already tried to change esync but it didn't work either, as well as roblox studio and roblox player don't open at the same time

I know that issues is not the right place for this but I'm just starting out on github and haven't found a "questions and answers" place

**Comment by apprehensions** [comment]
https://vinegarhq.org/Configuration/index.html#configuration-values
