### ISSUE TITLE
Roblox Studio physically not usable opengl error

### ISSUE THREAD

**Issue by LukeDevsE** [vinegarhq/vinegar#293]
![image](https://github.com/vinegarhq/vinegar/assets/108841495/31b46dc1-9104-430e-a849-523679f932ac)

#### Describe the bug
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported

When I open Roblox Studio it loads fine showing the roblox studio logo thing,
then when it gets to the main studio, it just shows that image.
The error fails to create an opengl context, it asks me to install a driver for opengl 2.0 or higher, ive tryed changing it to d3d11 using config, but that didnt work either, and i have my NVIDIA driver installed aswell.
When I originally had Windows 10, before switching to Ubuntu, roblox studio worked completely fine (aswell roblox player works fine for both, Windows, and Vinegar)
#### To Reproduce
just open roblox studio (im authed, im logged in with roblox player)

### Logs
[Studio-2023-12-08T21:00:23-07:00.log](https://github.com/vinegarhq/vinegar/files/13622641/Studio-2023-12-08T21.00.23-07.00.log)

### System information
* Distro: Freedesktop SDK 23.08 (Flatpak runtime) 23.08
* Processor: AMD A10-6700 APU with Radeon(tm) HD Graphics
  * Supports AVX: true
* Kernel: 6.5.0-14-generic
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: nvidia /sys/class/drm/card0

**Comment by LukeDevsE** [comment]
also im using the GTX 780 graphics card

**Comment by LukeDevsE** [comment]
it still says same error after yesterday

**Comment by lunarlettuce** [comment]
What error do you get under the D3D11 renderer?

**Comment by LukeDevsE** [comment]
> What error do you get under the D3D11 renderer?

like my graphics driver or vinegar?
cause i cant really find it
im really new to linux

**Comment by LukeDevsE** [comment]
i fixed it by adding this to the config
```
[studio]
renderer = "OpenGL"
dxvk = false
```
it gives a program crash error but just close it and it works

**Comment by LukeDevsE** [comment]
nvm theres still a issue where every popup window, toolbox, manage collaboraters,
just flashes on the left and is not in the window

**Comment by Noted-Jrelvas** [comment]
This is a known issue with the opengl renderer. This is why vulkan is considered a minimum requirement.

**Comment by LukeDevsE** [comment]
and it just randomly broke now i cant run roblox studio
