### ISSUE TITLE
Roblox lags after update v1.5.9

### ISSUE THREAD

**Issue by RackYican** [vinegarhq/vinegar#295]
Idk why this happens, is under 20fps, while it was 60fps in v1.5.8

**Comment by PolarKitsune** [comment]
I too am experiencing the same issue. I installed vinegar through the flatpak during v1.5.8 and in Deepwoken I was able to average 120+ framerate usually at max graphics, no other programs open. After this current update to v1.5.9 I also am having frame rate issues with my frame rate dropping down to about 40~ fps compared to the previous release. Thank you!

**Comment by lunarlettuce** [comment]
Curious, I haven't changed the wine build at all. If you are using an external wineroot, I recommend you to remove it for your config just to test.

**Comment by RackYican** [comment]
> Curious, I haven't changed the wine build at all. If you are using an external wineroot, I recommend you to remove it for your config just to test.

I'm not :/

**Comment by PolarKitsune** [comment]
> Curious, I haven't changed the wine build at all. If you are using an external wineroot, I recommend you to remove it for your config just to test.
I'm not the most knowledgeable yet with Linux things but I know that I'm using the base install, configurations and after my fps dropped by about 100 after the update.

**Comment by lunarlettuce** [comment]
> > Curious, I haven't changed the wine build at all. If you are using an external wineroot, I recommend you to remove it for your config just to test.
> 
> I'm not :/ One thing to have clear is when i updated it showed a uninstalling DXVK message, did that affect?

That's definitely peculiar, would you mind sending your config?

**Comment by TherionRO** [comment]
Can confirm I am experiencing the same issue,didnt saw the DXVK message for me as I did a fresh arch install and the I had the 1.5.8 before. Anyone has a fix for this or did someone tried downgrading to see if it fixes the issue?

**Comment by lunarlettuce** [comment]
out of curiosity, I would like for all of you to try
`flatpak uninstall org.vinegarhq.Vinegar --delete-data`
`enter y at the prompt`
`flatpak install org.vinegarhq.Vinegar`

**Comment by lunarlettuce** [comment]
One more thing of note, please check that you have no pending driver updates through `flatpak update`. I have experienced moments where the flatpak NVIDIA driver is mismatched with your system drivers, causing major slowdown.

**Comment by RackYican** [comment]
> out of curiosity, I would like for all of you to try `flatpak uninstall org.vinegarhq.Vinegar --delete-data` `enter y at the prompt` `flatpak install org.vinegarhq.Vinegar`

Sorry for the late response.
Currently I don't have access to my computer, so I can't help.

**Comment by TherionRO** [comment]
> out of curiosity, I would like for all of you to try `flatpak uninstall org.vinegarhq.Vinegar --delete-data` `enter y at the prompt` `flatpak install org.vinegarhq.Vinegar`

Can confirm the issue and lag is still there after uninstalling vinegar and clearing the data,no issues with the drivers or other packages it seems like the issue is related to vinegar or a dependency of it maybe?

**Comment by PolarKitsune** [comment]
> out of curiosity, I would like for all of you to try `flatpak uninstall org.vinegarhq.Vinegar --delete-data` `enter y at the prompt` `flatpak install org.vinegarhq.Vinegar`

Sorry for the late reply but I have indeed tried re-installing it, aswell as installing it on my laptop to test and I'm suffering the same loss of performance.

**Comment by lunarlettuce** [comment]
@TherionRO  @PolarKitsune  Can both of you send the output of `flatpak run org.vinegarhq.Vinegar sysinfo`? It's extremely strange that even a reinstall didn't fix this, since no Wine changes were made. 

The sysinfo command should tell me more information about your setup.

**Comment by PolarKitsune** [comment]
* Vinegar: v1.5.9 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Ryzen 5 3600 6-Core Processor
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.1.0-14-amd64
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: nvidia 0000:09:00.0 /sys/class/drm/card0

@lunarlettuce

**Comment by lunarlettuce** [comment]
Your kernel version is a bit old; do you happen to be using Debian?

**Comment by TherionRO** [comment]
2023/12/15 12:15:09 config.go:64: Using default configuration
* Vinegar: v1.5.9 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.7-zen1-1-zen
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: simple-framebuffer simple-framebuffer.0 /sys/class/drm/card0
  * Card 1: nvidia 0000:01:00.0 /sys/class/drm/card1

I didnt change the vinegar config at all,its the default one.

@lunarlettuce

**Comment by Noted-Jrelvas** [comment]
Your system is fucked.

**Comment by RackYican** [comment]
> @TherionRO @PolarKitsune Can both of you send the output of `flatpak run org.vinegarhq.Vinegar sysinfo`? It's extremely strange that even a reinstall didn't fix this, since no Wine changes were made.
> 
> The sysinfo command should tell me more information about your setup.

Hello again, i can share my system as i have acces to my pc again, here is:

2023/12/15 16:11:48 config.go:64: Using default configuration
* Vinegar: v1.5.9 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.7-x64v2-xanmod1-1
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card0

**Comment by Zeldaman259** [comment]
I'm on Steam Deck and can't pull above 30 fps on lowest settings in any game

**Comment by lunarlettuce** [comment]
Okay, unfortunately I can't see any similarities between your systems. I will try to bugtest wine-9.0rc2 soon, or use wine-9.0 release, which should come out in a week or so. I don't have any recommendations other than giving me a bit to upgrade the wine version entirely. Sorry!

**Comment by PolarKitsune** [comment]
> Your kernel version is a bit old; do you happen to be using Debian?

Yes, I am using Debian. I’m sorry for the late reply I’ve forgotten to check the thread. Also thank you, I’ll wait for next week.

**Comment by 65942** [comment]
I put this in my config and my performance was a lot better
```
[global]
dxvk = false
renderer = "Vulkan"
```

**Comment by RackYican** [comment]
> I put this in my config and my performance was a lot better
> 
> ```
> [global]
> dxvk = false
> renderer = "Vulkan"
> ```

Thank you, worked for me, i will not close this issue as i need everyone try this.

**Comment by RackYican** [comment]
@lunarlettuce @Noted-Jrelvas @TherionRO @Zeldaman259 Everyone try `flatpak run org.vinegarhq.Vinegar edit` then put this:

[global]
dxvk = false
renderer = "Vulkan"

**Comment by TherionRO** [comment]
> @lunarlettuce @Noted-Jrelvas @TherionRO @Zeldaman259 @PolarKitsune Everyone try `flatpak run org.vinegarhq.Vinegar edit` then put this:
> 
> [global] dxvk = false renderer = "Vulkan"

Wonderful it fixes the issue for me,atleast for now. I was sure it used opengl as a default for some reason,but never tried changing it from the config. Thank you for this quick fix!

**Comment by PolarKitsune** [comment]
> @lunarlettuce @Noted-Jrelvas @TherionRO @Zeldaman259 @PolarKitsune Everyone try `flatpak run org.vinegarhq.Vinegar edit` then put this:
> 
> [global] dxvk = false renderer = "Vulkan"

I tried, and for now it seems to restores my games performance to just about what it was before. I'm sorry for my late reply.

**Comment by lunarlettuce** [comment]
Okay, that's very curious, we haven't changed anything related to renderers. Maybe something is broken with upstream DXVK. I'm very glad that you've found a solution!

**Comment by RackYican** [comment]
I'm closing this issue as we found the fix.
Thank you all for supporting, especially for @65942 for finding the solution.

**Comment by myagizmaktav** [comment]
If still not passed Install graphic card driver and prompt terminal   `sysctl -w kernel.split_lock_mitigate=0`
