### ISSUE TITLE
Not opening either studio or app

### ISSUE THREAD

**Issue by bajrangCoder** [vinegarhq/vinegar#297]
I have installed wine and installed vinegar from it source and when i try to start from application menu it doesn't opens, so i have tried it from terminal using : `vinegar player` but it gives following logs and failed

```
2023/12/10 19:30:44 logs.go:27: Logging to file: /home/bajrangcoder/.cache/vinegar/logs/Player-2023-12-10T19:30:44+05:30.log
2023/12/10 19:30:44 version.go:37: Fetching latest version of WindowsPlayer for channel live
2023/12/10 19:30:44 api.go:22: Performing Roblox API GET clientsettings request on v2/client-version/WindowsPlayer/channel/live
xkbcommon: ERROR: couldn't find a Compose file for locale "en_IN" (mapped to "en_IN.ISO8859-1")
xkbcommon: ERROR: couldn't find a Compose file for locale "en_IN" (mapped to "en_IN.ISO8859-1")
2023/12/10 19:30:44 vinegar.go:181: splash: wayland: newXKB: xkb_compose_table_new_from_locale failed
```

my device specs:

System:
  Kernel: 6.6.5-zen1-1-zen arch: x86_64 bits: 64 compiler: gcc v: 13.2.1 clocksource: tsc
  Desktop: KDE Plasma v: 5.27.10 tk: Qt v: 5.15.11 wm: kwin_x11 vt: 2 dm: SDDM

CPU:
  Info: model: Intel Xeon E3-1225 v5 bits: 64 type: MCP arch: Skylake-S level: v3 note: check
    built: 2015 process: Intel 14nm family: 6 model-id: 0x5E (94) stepping: 3 microcode: 0xF0
  Topology: cpus: 1x cores: 4 smt: <unsupported> cache: L1: 256 KiB desc: d-4x32 KiB; i-4x32 KiB

**Comment by lunarlettuce** [comment]
Seems like your X setup is misconfigured. Try disabling splash in the config.

**Comment by bajrangCoder** [comment]
Thanks it's worked but only from terminal command(`vinegar player`) , not from app launcher

**Comment by lunarlettuce** [comment]
what is the error you get from launching from roblox.com?

**Comment by bajrangCoder** [comment]
here is the logs:

```
2023/12/12 16:24:22 version.go:37: Fetching latest version of WindowsPlayer for channel live
2023/12/12 16:24:22 api.go:22: Performing Roblox API GET clientsettings request on v2/client-version/WindowsPlayer/channel/live
2023/12/12 16:24:24 version.go:44: Fetched WindowsPlayer canonical version 0.605.3.6050660
2023/12/12 16:24:24 version.go:23: Got WindowsPlayer version version-48a28da848b7420d with channel live
2023/12/12 16:24:24 binary.go:257: WindowsPlayer is up to date (version-48a28da848b7420d)
2023/12/12 16:24:24 fflags.go:27: Applying custom FFlags
2023/12/12 16:24:24 dxvk.go:20: Enabling WINE DXVK DLL overrides
2023/12/12 16:24:24 dxvk.go:28: Downloading DXVK 2.3 (https://github.com/doitsujin/dxvk/releases/download/v2.3/dxvk-2.3.tar.gz as /home/bajrangcoder/.var/app/org.vinegarhq.Vinegar/cache/vinegar/dxvk-2.3.tar.gz)
```

After this nothing happens.... 😭

> [!NOTE]
> Now I have downloaded vinegar from flatpak because I get memory dump error

**Comment by bajrangCoder** [comment]
here is the logs:

```
2023/12/12 16:24:22 version.go:37: Fetching latest version of WindowsPlayer for channel live
2023/12/12 16:24:22 api.go:22: Performing Roblox API GET clientsettings request on v2/client-version/WindowsPlayer/channel/live
2023/12/12 16:24:24 version.go:44: Fetched WindowsPlayer canonical version 0.605.3.6050660
2023/12/12 16:24:24 version.go:23: Got WindowsPlayer version version-48a28da848b7420d with channel live
2023/12/12 16:24:24 binary.go:257: WindowsPlayer is up to date (version-48a28da848b7420d)
2023/12/12 16:24:24 fflags.go:27: Applying custom FFlags
2023/12/12 16:24:24 dxvk.go:20: Enabling WINE DXVK DLL overrides
2023/12/12 16:24:24 dxvk.go:28: Downloading DXVK 2.3 (https://github.com/doitsujin/dxvk/releases/download/v2.3/dxvk-2.3.tar.gz as /home/bajrangcoder/.var/app/org.vinegarhq.Vinegar/cache/vinegar/dxvk-2.3.tar.gz)
```

After this nothing happens.... 😭

> [!NOTE]
> Now I have downloaded vinegar from flatpak because I get memory dump error

**Comment by AniketsCode** [comment]
> Seems like your X setup is misconfigured. Try disabling splash in the config.
Good day Sir/mam
please tell how to do that as i am newbie in Linux

**Comment by apprehensions** [comment]
https://vinegarhq.org/Configuration/index.html

**Comment by bajrangCoder** [comment]
> > Seems like your X setup is misconfigured. Try disabling splash in the config.
> > Good day Sir/mam
> > please tell how to do that as i am newbie in Linux

Already done but it worked for once , after that again it's not working

**Comment by lunarlettuce** [comment]
This is a bug with KDE systems. You will need to override your locale with LC_ALL=C.
