### ISSUE TITLE
Roblox Studio does not work

### ISSUE THREAD

**Issue by thevibingcat** [vinegarhq/vinegar#298]
#### Describe the bug
I'm trying to help my friend develop a game he's making, however when i try to open roblox studio it gives me an error
When i open it, it shows an error saying "An unexpected error occurred and Roblox needs to quit. We're sorry!"

#### To Reproduce
Open roblox studio.

### Logs
https://pastebin.com/f4UHqr59
Here is a link to all of the text in `Studio-2023-23-10T16:52:17-05:00.log`

### System information

```
2023/12/10 16:58:06 config.go:63: Using default configuration
## System information
* Distro: Freedesktop.org SDK 23.08 (Flatpak runtime) 23.08
* Processor: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  * Supports AVX: true
* Kernel: 6.1.0-13-amd64
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: i915 /sys/class/drm/card0
```

#### Additional context
Normal roblox works. roblox studio doesn't work.

**Comment by itsaerosphere** [comment]
Hey, I'm having the same issue with very similar logs.

Here are my specs for comparison
```
* Vinegar: v1.5.9 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Ryzen 9 5900X 12-Core Processor
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.1.66-1-lts
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: amdgpu 0000:08:00.0 /sys/class/drm/card0
```

**Comment by brotherman123** [comment]
have you tried: flatpak run org.vinegarhq.Vinegar delete
If that doesnt work use this: rm .var/app/org.vinegarhq.Vinegar/data/vinegar/state.json

**Comment by apprehensions** [comment]
Closed due to OP inactivity
