### ISSUE TITLE
Flatpak version does not have a desktop icon

### ISSUE THREAD

**Issue by expoodo** [vinegarhq/vinegar#301]
There is no icon displayed for the running Roblox application, instead the default icon for apps without a set icon is used. I've tried installing vinegar as both a system-wide and per-user flatpak. There is only an icon when I install using the AUR package, however that seems to be broken for me as it crashes. The vinegar provided icons are in my system and the desktop files are pointing to them, and $XDG_DATA_DIRS is set.

* Vinegar: v1.5.9 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD FX(tm)-6100 Six-Core Processor
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.6-arch1-1
* Wine: wine-8.0-2786-g3061bb04122 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: amdgpu 0000:01:00.0 /sys/class/drm/card1

**Comment by lunarlettuce** [comment]
I believe this has to do with a missing permission in arch linux. I recall another installation not having the correct permissions to a certain folder for flatpak to place its .desktops in, but I cannot recall the message atm.

**Comment by angrypig555** [comment]
Same for me. Just create a .desktop file

**Comment by angrypig555** [comment]
Just started on my computer. also i didnt bother creating a desktop file for studio. Now there are icons

**Comment by lunarlettuce** [comment]
Solved by latest flatpak desktop fix
