### ISSUE TITLE
Can't compile from source on Debian 12 - "package slices is not in GOROOT"

### ISSUE THREAD

**Issue by ading2210** [vinegarhq/vinegar#303]
#### Describe the bug
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported
- [x] I have read the [minimum requirements](https://vinegarhq.org/Requirements/index.html).

Attempting to compile Vinegar on Debian 12 results in an error once `make` is run.

#### To Reproduce
Steps to reproduce the behavior.
- Install golang: `sudo apt install golang`
- Install dependencies: `sudo apt install gnutls-dev gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev`
- Clone the Vinegar repo and run `make`, which results in the following output:
```
user@debian:~/Downloads/vinegar$ make
go build --tags nowayland,novulkan   -ldflags="-s -w -X main.BinPrefix=/usr/libexec/vinegar -X main.Version=v1.5.9 -X github.com/vinegarhq/vinegar/config.LogoPath=/usr/share/icons/hicolor/64x64/apps/org.vinegarhq.Vinegar.png" ./cmd/vinegar
go: downloading github.com/altfoxie/drpc v0.0.0-20231214171500-0a4e3a3b1c53
go: downloading github.com/godbus/dbus/v5 v5.1.0
go: downloading golang.org/x/sync v0.5.0
go: downloading gioui.org v0.4.1
go: downloading golang.org/x/sys v0.15.0
go: downloading github.com/google/uuid v1.5.0
go: downloading golang.org/x/image v0.14.0
go: downloading github.com/go-text/typesetting v0.0.0-20231206174126-ce41cc83e028
go: downloading golang.org/x/exp v0.0.0-20231206192017-f3f8817b8deb
go: downloading golang.org/x/text v0.14.0
go: downloading golang.org/x/exp/shiny v0.0.0-20231206192017-f3f8817b8deb
util/paths.go:6:2: package slices is not in GOROOT (/usr/lib/go-1.19/src/slices)
make: *** [Makefile:32: vinegar] Error 1
```

### Logs
Reference log file contents, which are usually located in `~/.cache/vinegar/logs` or `~/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/` for Flatpak, of a run reproducing the bug

Neither of these directories exist because Vinegar can't be compiled in the first place.

### System information

* Installation method: From source 

`vinegar sysinfo` can't be run since I can't compile the program in the first place. Here's the output of `neofetch --stdout` instead.
```
user@debian 
----------- 
OS: Debian GNU/Linux 12 (bookworm) on Chrome OS x86_64 
Host: Drawcia rev7 
Kernel: 5.4.85-22138-ga9994f5cad40 
Uptime: 5 hours, 19 mins 
Packages: 1929 (dpkg) 
Shell: bash 5.2.15 
Resolution: 1366x768 
DE: Xfce 4.18 
WM: Xfwm4 
WM Theme: Default 
Theme: Adwaita-dark [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: xfce4-terminal 
Terminal Font: Monospace 12 
CPU: Intel Celeron N4500 (2) @ 2.800GHz 
GPU: Intel JasperLake [UHD Graphics] 
Memory: 2791MiB / 3791MiB 
```

#### Additional context
I have tried to follow the instructions on https://vinegarhq.org/Installation/guides/source.html.

I have installed Wine from the official WineHQ repos. `wine --version` gives `wine-9.0-rc1 (Staging)`

**Comment by apprehensions** [comment]
You need go 1.21, Update debian to something that has Go up to date.
