### ISSUE TITLE
NoSound Driver

### ISSUE THREAD

**Issue by AYnonyme971** [vinegarhq/vinegar#304]
#### Describe the bug
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported
- [x] I have read the [minimum requirements](https://vinegarhq.org/Requirements/index.html).

There is no sound in-game, and it says on the Output "NoSound Driver"

#### To Reproduce
Launch Vinegar
Play a game
Check the settings, and sounds (I think it's just something wrong with me)

### Logs
I think it's not needed

### System information

* Installation method: snap
2023/12/16 12:49:59 config.go:57: Using default configuration
## System information
* Distro: Ubuntu Core 22 22
* Processor: Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz
  * Supports AVX: true
* Kernel: 6.1.0-13-amd64
* Wine: wine-8.18 (Staging)
* Cards:
  * Card 0: i915 /sys/class/drm/card0

#### Additional context
Just there is no sound on the games and I just wanted to know if I can have sound, thanks for reading :)

**Comment by apprehensions** [comment]
The snap is unmaintained, please use the Flatpak.

**Comment by AYnonyme971** [comment]
ok, thanks
