### ISSUE TITLE
Roblox encounter an unexpected error.

### ISSUE THREAD

**Issue by Loganavter** [vinegarhq/vinegar#305]
#### Describe the bug
Roblox encounter an unexpected error.
#### To Reproduce
I tried to launch a roblox game through a button on the website. Vinegar started running the roblox player and the announcer filled up completely because a prompt appeared saying that "Roblox has encountered an unexpected error." Click the 'OK' button ... And then in the vinegar launch window itself it was reported "failed to launch Roblox on" 
And as a result, roblox did not start.

### Logs
2023/12/17 11:59:51 version.go:37: Fetching latest version of WindowsPlayer for channel live
2023/12/17 11:59:51 api.go:22: Performing Roblox API GET clientsettings request on v2/client-version/WindowsPlayer/channel/live
2023/12/17 11:59:52 version.go:44: Fetched WindowsPlayer canonical version 0.605.3.6050660
2023/12/17 11:59:52 version.go:23: Got WindowsPlayer version version-48a28da848b7420d with channel live
2023/12/17 11:59:52 binary.go:257: WindowsPlayer is up to date (version-48a28da848b7420d)
2023/12/17 11:59:52 fflags.go:27: Applying custom FFlags
2023/12/17 11:59:52 dxvk.go:34: Deleting all overridden DXVK DLLs
2023/12/17 11:59:52 dxvk.go:40: Removing DXVK DLL: /home/jorj/.local/share/vinegar/prefix/drive_c/windows/syswow64/d3d9.dll
2023/12/17 11:59:52 dxvk.go:40: Removing DXVK DLL: /home/jorj/.local/share/vinegar/prefix/drive_c/windows/syswow64/d3d10core.dll
2023/12/17 11:59:52 dxvk.go:40: Removing DXVK DLL: /home/jorj/.local/share/vinegar/prefix/drive_c/windows/syswow64/d3d11.dll
2023/12/17 11:59:52 dxvk.go:40: Removing DXVK DLL: /home/jorj/.local/share/vinegar/prefix/drive_c/windows/syswow64/dxgi.dll
2023/12/17 11:59:52 dxvk.go:40: Removing DXVK DLL: /home/jorj/.local/share/vinegar/prefix/drive_c/windows/system32/d3d9.dll
2023/12/17 11:59:52 dxvk.go:40: Removing DXVK DLL: /home/jorj/.local/share/vinegar/prefix/drive_c/windows/system32/d3d10core.dll
2023/12/17 11:59:52 dxvk.go:40: Removing DXVK DLL: /home/jorj/.local/share/vinegar/prefix/drive_c/windows/system32/d3d11.dll
2023/12/17 11:59:52 dxvk.go:40: Removing DXVK DLL: /home/jorj/.local/share/vinegar/prefix/drive_c/windows/system32/dxgi.dll
2023/12/17 11:59:52 dxvk.go:48: Restoring Wineprefix DLLs
2023/12/17 11:59:52 cmd.go:74: Starting command: /usr/bin/wine wineboot -u
wine: configuration in L"/home/jorj/.local/share/vinegar/prefix" has been updated.
2023/12/17 11:59:55 state.go:92: Saving installed DXVK State
2023/12/17 11:59:55 discordrpc.go:16: Authenticating Discord RPC
2023/12/17 11:59:55 binary.go:86: WARNING: Could not initialize Discord RPC: dial unix /run/user/1000/discord-ipc-0: connect: no such file or directory, disabling...
2023/12/17 11:59:55 binary.go:128: Launching WindowsPlayer
2023/12/17 11:59:55 cmd.go:74: Starting command: /usr/bin/wine /home/jorj/.local/share/vinegar/prefix/vinegar/versions/version-48a28da848b7420d/RobloxPlayerBeta.exe roblox-player:1+launchmode:play+gameinfo:DSDTFNjBIaqCbR_o5DrVyG0TMQaqcOV6RwVhuOKV4szSZPV0LHRaNgVDkckGbqx3u5Qkyc3tFSRzlVFVu6fIVTcmf5KCFnkkbAK-nLmlvteqlwyT0-9V6G9j97vgxYFaU_9U_8cHjAo0bSC6pUldLBlwprR_qU3cEd9F4thSagX4VDbl9-1kfmXs7xSN4PHE-q-PBLU9a9D5zHYefRLPBg+launchtime:1702803590648+placelauncherurl:https%3A%2F%2Fassetgame.roblox.com%2Fgame%2FPlaceLauncher.ashx%3Frequest%3DRequestGame%26browserTrackerId%3D162398343449%26placeId%3D292439477%26isPlayTogetherGame%3Dfalse%26joinAttemptId%3De1f23bca-c35d-4488-839e-cab5e572797b%26joinAttemptOrigin%3DPlayButton+browsertrackerid:162398343449+robloxLocale:en_us+gameLocale:en_us+channel:
0190:fixme:ntdll:NtRaiseHardError c0000005 stub
2023/12/17 11:59:58 binary.go:161: Another Roblox instance is already running, not killing wineprefix
2023/12/17 11:59:58 vinegar.go:196: roblox process: exit status 4
2023/12/17 11:59:59 splash.go:141: Opening log file: /home/jorj/.cache/vinegar/logs/Player-2023-12-17T11:59:51+03:00.log

### System information
Arch linux
Ryzen 5 5600
RX 6600
32 Gb RAM
1 Tb ssd

* Installation method:
yay -S vinegar

* Vinegar: v1.5.9 (ce1ba3bf12cf3a327481a494cbe60067e4d9c358)
* Distro: EndeavourOS
* Processor: AMD Ryzen 5 5600 6-Core Processor
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.4-zen1-1-zen
* Wine: wine-8.21 (Staging)
* Cards:
  * Card 0: amdgpu 0000:09:00.0 /sys/class/drm/card1

**Comment by lunarlettuce** [comment]
Wine-8.21 requires the segment register revert patch to function. I recommend using the flatpak for now.
