### ISSUE TITLE
`xkb_compose_table_new_from_locale` failure

### ISSUE THREAD

**Issue by angrypig555** [vinegarhq/vinegar#306]
#### Describe the bug
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported
- [x] I have read the [minimum requirements](https://vinegarhq.org/Requirements/index.html).

When opening vinegar it immidiaetly crashes because xkbcommon: ERROR: /usr/share/X11/locale/iso8859-2/Compose:38:25: string literal is not a valid UTF-8 string

#### To Reproduce
Open vinegar player via the command line

### Logs
Reference log file contents, which are usually located in `~/.cache/vinegar/logs` or `~/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/` for Flatpak, of a run reproducing the bug

2023/12/17 11:52:45 vinegar.go:205: Initializing wineprefix at /home/brny/.var/app/org.vinegarhq.Vinegar/data/vinegar/prefix
2023/12/17 11:52:45 cmd.go:74: Starting command: /app/bin/wine reg add HKEY_CURRENT_USER\Control Panel\Desktop /v LogPixels /t REG_DWORD /d 97 /f
2023/12/17 11:52:45 vinegar.go:181: splash: x11: newXKB: xkb_compose_table_new_from_locale failed

### System information

* Installation method:
2023/12/17 11:59:09 config.go:64: Using default configuration
* Vinegar: v1.5.9 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Genuine Intel(R) CPU @ 2.00GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.7-arch1-1
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: simple-framebuffer simple-framebuffer.0 /sys/class/drm/card0
  * Card 1: nvidia 0000:01:00.0 /sys/class/drm/card1

#### Additional context
It is installed on arch. Idk if that could help.

**Comment by apprehensions** [comment]
Can you run `env | grep LC`?

**Comment by angrypig555** [comment]
Returned the following:
LANGUAGE=hu:en_US
LANG=hu

**Comment by apprehensions** [comment]
What distribution are you running?

**Comment by angrypig555** [comment]
Arch, just installed it  today

**Comment by apprehensions** [comment]
You need to set up your locale for xkbcommon aka Vinegar.

https://wiki.archlinux.org/title/locale#Generating_locales
`locale-gen`

**Comment by angrypig555** [comment]
Same problem, i also did a reboot

**Comment by apprehensions** [comment]
Unfortunately, as the cause of this issue is unknown (currently sent issue report to Gio), you will have to set your locale to english `en_US`.

**Comment by angrypig555** [comment]
Ok , ill try it but then my whole keyboard would break

**Comment by angrypig555** [comment]
Did a reinstall because i corrupted whole fs. oops. Now it works.
m
a
g
i
c
