### ISSUE TITLE
Cursor view glitch

### ISSUE THREAD

**Issue by angrypig555** [vinegarhq/vinegar#308]
#### Describe the bug
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported
- [x] I have read the [minimum requirements](https://vinegarhq.org/Requirements/index.html).
So, i play this game entry point. It is a FPS game. But when i equip a gun a small portion of the screen is put into the middle with diagonal llines. Also the cursor was hidden on windows. Know that because i tested it on a laptop

#### To Reproduce
1. Play entry point
2. Equip a weapon.

### Logs
[Player-2023-12-19T06:33:55+01:00.log](https://github.com/vinegarhq/vinegar/files/13711653/Player-2023-12-19T06.33.55%2B01.00.log)

### System information

* Installation method:
2023/12/19 06:49:02 config.go:64: Using default configuration
* Vinegar: v1.5.9 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Genuine Intel(R) CPU @ 2.00GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.7-arch1-1
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: simple-framebuffer simple-framebuffer.0 /sys/class/drm/card0
  * Card 1: nvidia 0000:01:00.0 /sys/class/drm/card1

#### Additional context
I have gotten broken XRandr warnings before. Also the logs contain that the animationclip provider cant load something.

Dont know if this is a game error or a vinegar because the cursor is not hidden here

**Comment by lunarlettuce** [comment]
Hmm, this may be a recent bug on Roblox. Try wayland.

**Comment by angrypig555** [comment]
um you dont want to see how broken my desktop looks and performs with wayland.

**Comment by Realswitzer** [comment]
Bug has occurred for a few months from what I can remember, and problem occurs both in Xorg and Wayland.

**Comment by wawashish** [comment]
has to be something to do with nvidia.
have you considered using the Nouveau driver instead

**Comment by gameskip** [comment]
I have the same issue here

**Comment by furdiburd** [comment]
Same issue here. Amd rx 6700 xt with x11

**Comment by lunarlettuce** [comment]
I'm more interested about your processor, now that I am coming back to read this. `Processor: Genuine Intel(R) CPU @ 2.00GHz ` doesn't sound like a valid CPU.

**Comment by angrypig555** [comment]
It is an engineering prototype. It is old but it was a very good for its time

**Comment by secretknowledge** [comment]
I am having the same issue on a new processor, can confirm it is not processor related

**Comment by Memez145** [comment]
> Hmm, this may be a recent bug on Roblox. Try wayland.

I've been having the same issue- when I switch to Wayland the mouse isn't captured by the screen and it becomes this... thing. 
(https://github.com/vinegarhq/vinegar/assets/102411440/f189da66-516c-4590-ac73-c2f5c95d9b30)

(GPU: GTX 1060 3GB, CPU: Intel i5-3450)   

> um you dont want to see how broken my desktop looks and performs with wayland.

Same, haha. Game went from like 120 FPS on X11 to 15FPS with constant screen tearing on Wayland.

**Comment by angrypig555** [comment]
Some package update was pushed so i have -1 fps. Also 32 bit opengl libraries now dont work.

**Comment by Memez145** [comment]
update, same thing happened to me while playing Randomizer. Only with some weapons that use static crosshairs though. Let me try turning off my crosshair in Entry Point.
![image](https://github.com/vinegarhq/vinegar/assets/102411440/259e46f0-2524-44b5-8b4a-8d29d2782ae5)

**Comment by dvdoll** [comment]
Just came across this in The Mimic. Arch Linux, RTX 3070, installed via aur using wine-ge as root. Behavior is odd, it takes whatevers behind the decal im assuming and continues displaying it, gets reset if you press ESC but then instantly happens again. Another thing that might be important to note regarding its behavior, it does **not** get captured in obs while using obs-vkcapture.

**Comment by jrelvas-ipc** [comment]
Please don't run wine as root.

**Comment by dvdoll** [comment]
Haha, sorry for confusion. I meant wine-ge as wineroot. 😅

**Comment by lunarlettuce** [comment]
Seems to be entry point specific. Perhaps contact the developer? Not much we can do on our end...

**Comment by secretknowledge** [comment]
I have also been able to replicate in The Mimic so it seems to be across multiple games.

**Comment by furdiburd** [comment]
> I have also been able to replicate in The Mimic so it seems to be across multiple games.

So at least we know its an issue with vinegar. Does someone know a way to see what trigger this?

**Comment by apprehensions** [comment]
This is not a problem with Vinegar. this is a problem with Wine and Roblox.

**Comment by secretknowledge** [comment]
If so, does anybody know a working wine version for this?

**Comment by dvdoll** [comment]
I believe this is an issue with NVIDIA and NVIDIA drivers. On my laptop, an Intel with integrated graphics, same exact config & installation as my desktop, the problem does not persist.

**Comment by furdiburd** [comment]
> I believe this is an issue with NVIDIA and NVIDIA drivers. On my laptop, an Intel with integrated graphics, same exact config & installation as my desktop, the problem does not persist.

I use amd gpu and have the bug. So if i got it right this happens on NVIDIA and AMD cards but not on intel?

**Comment by secretknowledge** [comment]
I believe someone earlier was able to reproduce on an AMD card, so maybe something related to the processor?

**Comment by jrelvas-ipc** [comment]
For everyone who has posted here, please follow the instructions I've given here: https://github.com/vinegarhq/vinegar/issues/228#issuecomment-1879221960

**Comment by jrelvas-ipc** [comment]
@lunarlettuce 
> Seems to be entry point specific. Perhaps contact the developer? Not much we can do on our end...

Definitely not. Developers can't just copy parts of the screen like that with Roblox's API. This is either an X11 bug (no one has reported this on Wayland) or a Roblox one.

**Comment by Memez145** [comment]
> @lunarlettuce
> 
> > Seems to be entry point specific. Perhaps contact the developer? Not much we can do on our end...
> 
> Definitely not. Developers can't just copy parts of the screen like that with Roblox's API. This is either an X11 bug (no one has reported this on Wayland) or a Roblox one.

A similar bug happens on Wayland for me, where the cursor isn't caught by Roblox and the weird artifact follows the cursor instead of being in the centre of the screen.

**Comment by Memez145** [comment]
ALRIGHT the bug just stopped for me when I tested it today on X11. Can other people check to see if it's stopped for them as well?

**Comment by Memez145** [comment]
> Definitely not fixed. @Memez145 , do you mind telling us anything that you may have done to fix it?

I reinstalled Vinegar recently, but otherwise I don't remember doing anything.
