### ISSUE TITLE
I couldn't run vinegar on Ubuntu

### ISSUE THREAD

**Issue by thatOneGuyWifi** [vinegarhq/vinegar#310]
I installed Vinegar from Flathub on Ubuntu Running KDE (don't ask me why I installed KDE on Ubuntu when Kubuntu exist)
 and when I ran the command `flatpak run org.vinegarhq.Vinegar player` and it showed this

```
2023/12/20 01:08:12 config.go:64: Using default configuration
2023/12/20 01:08:12 logs.go:27: Logging to file: /home/thatoneguywifi/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/Player-2023-12-20T01:08:12+05:30.log
2023/12/20 01:08:12 version.go:37: Fetching latest version of WindowsPlayer for channel live
2023/12/20 01:08:12 api.go:22: Performing Roblox API GET clientsettings request on v2/client-version/WindowsPlayer/channel/live
xkbcommon: ERROR: couldn't find a Compose file for locale "en_IN" (mapped to "en_IN.ISO8859-1")
2023/12/20 01:08:12 vinegar.go:181: splash: x11: newXKB: xkb_compose_table_new_from_locale failed
```

thankfully I was able to fix this from a redditor on [r/linux_gaming](https://www.reddit.com/r/linux_gaming/) And the redditor said to report this problem

[my reddit post](https://www.reddit.com/r/linux_gaming/comments/18m9tbb/i_cant_run_vinegar_on_ubuntu_i_think/)

**Comment by lunarlettuce** [comment]
I believe you are missing some library files in your installation.

**Comment by thatOneGuyWifi** [comment]
> I believe you are missing some library files in your installation; this isn't a bug in vinegar.

could you give me some name of those libraries?

**Comment by lunarlettuce** [comment]
Hmm, I've had a look at this [forum post](https://forum.endeavouros.com/t/kwin-xkbcommon-xkb-couldnt-find-a-compose-file-for-locale-en-in-mapped-to-en-in-iso8859-1/41943/3). Is en_in not supported on KDE?

**Comment by thatOneGuyWifi** [comment]
> Hmm, I've had a look at this [forum post](https://forum.endeavouros.com/t/kwin-xkbcommon-xkb-couldnt-find-a-compose-file-for-locale-en-in-mapped-to-en-in-iso8859-1/41943/3). Is en_in not supported on KDE?

it doesn't looks like so
