### ISSUE TITLE
Cant set wineroot to custom wine

### ISSUE THREAD

**Issue by Flowcheer** [vinegarhq/vinegar#313]
#### Describe the bug
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported
anytime i try to set a custom wineroot with the `flatpak run org.vinegarhq.Vinegar edit` command i get this error. 
![imagen](https://github.com/vinegarhq/vinegar/assets/79985497/7b9ab7c9-87e9-4b78-aa09-191284d6ed07)

Sysinfo: Vinegar: v1.6.0 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Ryzen 3 3200G with Radeon Vega Graphics
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.1.0-15-amd64
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: amdgpu 0000:08:00.0 /sys/class/drm/card0

It says that the wine executable doesnt exist though it does exist
![imagen](https://github.com/vinegarhq/vinegar/assets/79985497/2caa20e8-5858-41ba-a5c3-b1e4f62a3cdc)

**Comment by wawashish** [comment]
If you're using the Flatpak, ensure that the path of the wineroot configuration option is allowed access from the Flatpak, as if it is a path outside of ~/.var/app/org.vinegarhq.Vinegar Vinegar won't be able to access the directory: `flatpak override --user --filesystem=/path/to/wineroot`

**Comment by apprehensions** [comment]
https://vinegarhq.org/Configuration/index.html#configuration-values
