### ISSUE TITLE
Texture Loading Bug In Arsenal

### ISSUE THREAD

**Issue by shadowprower** [vinegarhq/vinegar#315]
I have installed Vinegar HQ using Flatpak. When attempting to play Roblox Arsenal, I encounter graphical glitches caused by textures not loading properly. This issue only occurs with Arsenal; other games such as Jailbreak, Counter Blox, and others work perfectly fine with Vinegar.

My system information is as follows: Intel i3-1005G1, Intel Iris Plus Graphics. I am running Fedora 38 with XFCE.

I have attached footage of the game, and the snappiness you observe is due to my lack of configuration in OBS Studio. My internet connection is stable, and I am only facing this issue with Arsenal.

https://github.com/vinegarhq/vinegar/assets/142143957/409be67f-cd28-4ee3-808a-9305955fa34b

**Comment by MrDraco97** [comment]
If you are using the vulkan renderer, that is most definitely the issue.

**Comment by shadowprower** [comment]
> If you are using the vulkan renderer, that is most definitely the issue.

how do i change the render ? i installed vinegar using flatpak

**Comment by apprehensions** [comment]
Re

**Comment by apprehensions** [comment]
ad the documentation

**Comment by shadowprower** [comment]
> ad the documentation 

what just happend?

**Comment by apprehensions** [comment]
Re
ad the documentation
