### ISSUE TITLE
Vinegar won't open

### ISSUE THREAD

**Issue by tutyt23c** [vinegarhq/vinegar#316]
#### Describe the bug
- I have searched open and closed issues to make sure that the bug has not yet been reported
- I have read the [minimum requirements](https://vinegarhq.org/Requirements/index.html).

When i open vinegar, it says Launching Player, and once that is done, I get an error stating "Roblox encountered an unexpected error. Click 'Ok' to create a memory dump, then please share it on our support site: https://roblox.com/support". After i press ok, nothing happens, if i press cancel (on the error message), another vinegar error pops up saying "Vinegar experienced an arror: roblox: exit status 4"

#### To Reproduce
Open vinegar

### Logs
2023/12/26 11:54:27 deployment.go:41: Fetching latest version of WindowsPlayer for channel LIVE
2023/12/26 11:54:28 deployment.go:48: Fetched WindowsPlayer canonical version 0.605.3.6050660
2023/12/26 11:54:28 binary.go:281: WindowsPlayer is up to date (version-48a28da848b7420d)
2023/12/26 11:54:28 binary.go:286: Using Renderer: D3D11
2023/12/26 11:54:28 fflags.go:34: Applying custom FFlags: /home/skid/.local/share/vinegar/prefix/vinegar/versions/version-48a28da848b7420d/ClientSettings/ClientAppSettings.json
2023/12/26 11:54:28 dxvk.go:24: Enabling WINE DXVK DLL overrides
2023/12/26 11:54:28 discordrpc.go:16: Connecting to Discord RPC
2023/12/26 11:54:28 binary.go:140: Launching WindowsPlayer (/usr/bin/wine /home/skid/.local/share/vinegar/prefix/vinegar/versions/version-48a28da848b7420d/RobloxPlayerBeta.exe -app)
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00d4:fixme:ntdll:NtRaiseHardError c0000005 stub
00d4:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
00d4:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
2023/12/26 11:54:31 wine.go:56: Killing wineprefix
2023/12/26 11:54:31 discordrpc.go:22: Closing Discord RPC
2023/12/26 11:54:31 vinegar.go:219: roblox: exit status 4

### System information

* Installation method:
* Vinegar: v1.6.0 (c3160de6f3be45b8581b8131e0353e275e4e0c75)
* Distro: Arch Linux
* Processor: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.7-zen1-1-zen
* Wine: wine-8.21
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card1 -->

#### Additional context

**Comment by apprehensions** [comment]
Interesting

**Comment by apprehensions** [comment]
Read the minimum requirements.

You need a custom wine version that supports Roblox, see Wine GE.
