### ISSUE TITLE
Roblox Player freezes after start

### ISSUE THREAD

**Issue by gtsrhythm** [vinegarhq/vinegar#317]
#### To Reproduce
Run `roblox player`.

### Logs
2023-12-26T23:07:35.898Z,4.898144,01b0,6 [FLog::Output] ESGamePerfMonitor GPU: DedicatedVidMem 1073741824 DedicatedSysMem 0 SharedSystemMemory 3403153408

01b0:fixme:dbghelp:elf_search_auxv can't find symbol in module

01b0:fixme:dbghelp:elf_search_auxv can't find symbol in module
...

### System information

* Installation method: Flatpak
* Vinegar: v1.6.0 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: 12th Gen Intel(R) Core(TM) i3-1215U
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.1.64-08953-ge15d57a188a7
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: virtio-pci 0000:00:02.0 /sys/class/drm/card0

#### Additional context
When running roblox player, the game  simply freezes and quits shortly after.

**Comment by Noted-Jrelvas** [comment]
You're running Roblox on a VM.

**Comment by gtsrhythm** [comment]
Is there no way to get it to work on a vm? I'm using a Chromebook and installing a distro directly onto the drive isn't a viable option since its school provided.

**Comment by Noted-Jrelvas** [comment]
Roblox Player has some checks in place which attempt to prevent use in a VM. Under certain conditions, these checks don't work and it doesn't block use, but these conditions are currently unknown. 

Vinegar is powerless to fix this; these checks also fire up on Windows VMs (though it might be worth giving a Windows VM a try just to see if results are any different).

**Comment by gtsrhythm** [comment]
Alright, Thank you.
