### ISSUE TITLE
black screen appearing when launching from roblox website.

### ISSUE THREAD

**Issue by ChillFlameX** [vinegarhq/vinegar#319]
when running roblox from the website i just get a black screen but i can still hear the game perfectly 

 how i produced: i downloaded vinegar and then went to roblox.com and tried loading a game and then i got an texture error of some type so i just tried again and that time it actually loaded except it it was just a completly black screen.

lol pls help me im new to linux, is there any other way to launch?

also in the making of this the black screen turned white

**Comment by apprehensions** [comment]
Troubleshooting docs

**Comment by ChillFlameX** [comment]
which one do i choose for debian 11
