### ISSUE TITLE
Embedded websites will not work - "White screen on login"

### ISSUE THREAD

**Issue by apprehensions** [vinegarhq/vinegar#32]
**Launching the Roblox Player in app mode and doing actions that require websites will not work (Such as attempting to login, its reccomended to use Quick login.), and so will Studio fail to bring up a login page; as the WineHQ team has yet to make a better implementation of the mshtml engine.**

**Comment by angrypig555** [comment]
but then isnt it a wine problem if webview doesnt work?

**Comment by apprehensions** [comment]
Made more obvious with 04121c28316e01092921a01c8326a16a98515716

**Comment by jojommeke** [comment]
Have you tried `flatpak update` ? it did work for me if Roblox just showed a white screen.

**Comment by dnkmmr69420** [comment]
this really needs to be fixed and it is a much bigger problem for steam deck users

**Comment by apprehensions** [comment]
Not much can be done to solve this problem other than having patience for WebView to support Wine or Wine to support WebView.

**Comment by brotherman123** [comment]
Might have found a solution. use command `flatpak run org.vinegarhq.Vinegar` delete to delete prefix.

**Comment by apprehensions** [comment]
WebView2 installer has been implemented in vinegar HEAD.

**Comment by brotherman123** [comment]
hey how to download webview? i need to authenticate studio

**Comment by apprehensions** [comment]
It will be done automatically

**Comment by snail5120** [comment]
well thats a lie because it never downloaded for me

**Comment by sewnie** [comment]
Because its broken on Flatpak (what i presume you're using)
