### ISSUE TITLE
Infinite login loop with studio

### ISSUE THREAD

**Issue by FoxesChooseJiff** [vinegarhq/vinegar#320]
#### Describe the bug
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported
- [x] I have read the [minimum requirements](https://vinegarhq.org/Requirements/index.html).

When studio fails to login and asks you to login via browser, clicking the open link with app dialog in firefox instantly throws the "failed to launch studio" error in the bootstrapper and makes logging in impossible.

#### To Reproduce
Launch studio, click on login via browser, click the continue button, click the open with app dialog.

### Logs

```2023/12/28 16:59:38 version.go:37: Fetching latest version of WindowsStudio64 for channel live
2023/12/28 16:59:38 api.go:22: Performing Roblox API GET clientsettings request on v2/client-version/WindowsStudio64/channel/live
2023/12/28 16:59:38 version.go:44: Fetched WindowsStudio64 canonical version 0.605.3.6050660
2023/12/28 16:59:38 version.go:23: Got WindowsStudio64 version version-e06dda850cf14c6c with channel live
2023/12/28 16:59:38 binary.go:257: WindowsStudio64 is up to date (version-e06dda850cf14c6c)
2023/12/28 16:59:38 fflags.go:27: Applying custom FFlags
2023/12/28 16:59:38 dxvk.go:20: Enabling WINE DXVK DLL overrides
2023/12/28 16:59:38 binary.go:128: Launching WindowsStudio64
2023/12/28 16:59:38 cmd.go:74: Starting command: /app/bin/wine /home/drift/.var/app/org.vinegarhq.Vinegar/data/vinegar/prefix/vinegar/versions/version-e06dda850cf14c6c/RobloxStudioBeta.exe roblox-studio-auth:/?code=[REDACTED]
0320:err:esync:esync_init Failed to open esync shared memory file; make sure no stale wineserver instances are running without WINEESYNC.
2023/12/28 16:59:39 prefix.go:34: Killing wineprefix
2023/12/28 16:59:39 cmd.go:74: Starting command: /app/bin/wineserver -k
2023/12/28 16:59:39 vinegar.go:196: roblox process: exit status 1
2023/12/28 16:59:49 splash.go:141: Opening log file: /home/drift/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/Studio-2023-12-28T16:59:38-05:00.log
```

### System information

* Installation method:
Installed via the flatpak org.vinegarhq.Vinegar package

* Vinegar: v1.5.9 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Ryzen 7 6800H with Radeon Graphics
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.6-76060606-generic
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: amdgpu 0000:34:00.0 /sys/class/drm/card0
  * Card 1: nvidia 0000:01:00.0 /sys/class/drm/card1

#### Additional context
No issues using studio until today. Roblox player works without issues.

**Comment by FoxesChooseJiff** [comment]
Anything?

**Comment by Valentin3832** [comment]
i got the same issue tho, tried everything i could

**Comment by TherionRO** [comment]
Same issue here,any fixes?

**Comment by realtica** [comment]
Same here, I can't login anymore :(

**Comment by apprehensions** [comment]
In the new v1.7.4 release, a new WebView installer has been officially introduced, which only gets activated on first run, to install it on Studio (change to `player` if necessary):
```
vinegar -firstrun studio run
```
