### ISSUE TITLE
Failed to symlink overlay files if it already exists 

### ISSUE THREAD

**Issue by starzation** [vinegarhq/vinegar#321]
#### Describe the bug
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported
- [X] I have read the [minimum requirements](https://vinegarhq.org/Requirements/index.html).

When vinegar is copying overlay files if there already file exists in dest folder it will throw symlink error "file exists"

#### To Reproduce
- Add files to vinegar overlay
- Launcher vinegar player

### Logs
```
2023/12/30 16:16:59 deployment.go:41: Fetching latest version of WindowsPlayer for channel ZFlag
2023/12/30 16:16:59 deployment.go:48: Fetched WindowsPlayer canonical version 0.605.3.6050660
2023/12/30 16:16:59 binary.go:281: WindowsPlayer is up to date (version-48a28da848b7420d)
2023/12/30 16:16:59 binary.go:286: Using Renderer: D3D11
2023/12/30 16:16:59 fflags.go:34: Applying custom FFlags: /home/starzation/.local/share/vinegar/prefix/vinegar/versions/version-48a28da848b7420d/ClientSettings/ClientAppSettings.json
2023/12/30 16:16:59 copy.go:19: Copying Overlay directory's files
2023/12/30 16:16:59 vinegar.go:219: symlink /nix/store/g5szcwdfsbjznm9fqad69hwf7v0nlr4g-home-manager-files/.config/vinegar/overlay/content/sounds/action_footsteps_plastic.mp3 /home/starzation/.local/share/vinegar/prefix/vinegar/versions/version-48a28da848b7420d/content/sounds/action_footsteps_plastic.mp3: file exists
```

### System information

* Installation method: Installed from source

* Vinegar: v1.6.0 
* Distro: NixOS 24.05 (Uakari) 24.05
* Processor: Intel(R) Core(TM) i3-10105F CPU @ 3.70GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.1.67
* Wine: wine-9.0-rc1 (Staging)
* Cards:
  * Card 0: amdgpu 0000:01:00.0 /sys/class/drm/card0

#### Additional context
It will only cause if it already have file exists in dest folder which can cause by install roblox or vinegar copy overlay file successfully

**Comment by apprehensions** [comment]
Fixed in https://github.com/otiai10/copy/pull/145
