### ISSUE TITLE
Wineprefix is not killed after closing the App

### ISSUE THREAD

**Issue by Tunahan-Uysal** [vinegarhq/vinegar#323]
#### Describe the bug
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported
- [x] I have read the [minimum requirements](https://vinegarhq.org/Requirements/index.html).

Closing the app at any points leads to it not actually killing wineprefix, meaning that the game still runs but only in the background. To kill it, you have to kill the process itself.

#### To Reproduce
1. Close via alt+f4 or via the close or leave button.

### Logs

[Player-2023-12-30T23:25:40+03:00.log](https://github.com/vinegarhq/vinegar/files/13799148/Player-2023-12-30T23.25.40%2B03.00.log)

### System information

* Installation method: Flatpak (Up-to-Date)

* Vinegar: v1.6.0 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Ryzen 5 3500 6-Core Processor
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.4.0-060400-generic
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: nvidia 0000:09:00.0 /sys/class/drm/card0

#### Additional context
I found a similar instance, where it was fixed by updating the Flatpak. unfortunately, it has not changed anything.

**Comment by Znimator** [comment]
Having same problem on Fedora 39 (Flatpak)

**Comment by Petally** [comment]
Having this issue on roblox studio
