### ISSUE TITLE
Nothing happens when trying to launch Roblox from the website

### ISSUE THREAD

**Issue by gameskip** [vinegarhq/vinegar#328]
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported
- [x] I have read the [minimum requirements](https://vinegarhq.org/Requirements/index.html).

Whenever trying to launch a game from the Roblox website, nothing happens - not even a log file is created by Vinegar.

#### To Reproduce
Install Vinegar from flathub
Attempt to play a Roblox game through the website

### Logs
None created

### System information

* Installation method: Flatpak, through flathub
```
* Vinegar: v1.6.0 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Ryzen 9 3900X 12-Core Processor
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.5.0-10-generic
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: nvidia 0000:0a:00.0 /sys/class/drm/card0
```
* Distro is Kubuntu 23.10 (Mantic Minotaur)
* Kernel version is 6.5.0-10-generic
* GPU is an NVIDIA RTX 3060 Ti
* X.org display server

#### Additional context
It's my first time installing Vinegar after Grapejuice stopped working, I've tried reinstalling Vinegar and that's about it, since I'm not experienced with these sorts of things. Additionally, running `flatpak run org.vinegarhq.Vinegar player` works, even the log-in works, however many other things like joining friends or joining private servers do not.

**Comment by apprehensions** [comment]
Vinegar is working as intended. Please fix your browser, which is unable to associate Vinegar with roblox-player, or reinstall Vinegar from flatpak to re-initialize MIME associations.

**Comment by apprehensions** [comment]
Check your `~/.config/mimeapps.list`, and check Default Applcations in browser. I am using Chromium and Flatpak works fine.

**Comment by gameskip** [comment]
Checking mimeapps.list, the only entries related to roblox in Default Applications are:
```
application/x-roblox-rbxl=roblox-studio.desktop
application/x-roblox-rbxlx=roblox-studio.desktop
```
and
```
x-scheme-handler/roblox-player=roblox-player.desktop
x-scheme-handler/roblox-studio=roblox-studio.desktop
```
I, of course, am not sure if that is what it's supposed to be. I am also using a Chromium-based browser.

**Comment by apprehensions** [comment]
Thats not vinegar...

**Comment by gameskip** [comment]
Yep! Manually editing those entries to Vinegar solved the issue, huge thanks!
