### ISSUE TITLE
esync_init Failed to open esync shared memory file

### ISSUE THREAD

**Issue by PatoSalvaje** [vinegarhq/vinegar#329]
#### Describe the bug
- [ x] I have searched open and closed issues to make sure that the bug has not yet been reported
- [x ] I have read the [minimum requirements](https://vinegarhq.org/Requirements/index.html).

I've been running Roblox with vinegar Flatpak without issues for a coupple of months but a few days ago Roblox crash after a few seconds every time I start a game.
To Reproduce:
Open a game, start playing... after a few seconds Roblox crashes with "Roblox exit: Status 1"

Log:

> 2024/01/06 15:53:10 deployment.go:41: Fetching latest version of WindowsPlayer for channel LIVE
2024/01/06 15:53:10 deployment.go:48: Fetched WindowsPlayer canonical version 0.605.3.6050660
2024/01/06 15:53:10 binary.go:281: WindowsPlayer is up to date (version-48a28da848b7420d)
2024/01/06 15:53:10 binary.go:286: Using Renderer: Vulkan
2024/01/06 15:53:10 fflags.go:34: Applying custom FFlags: /home/ines/.var/app/org.vinegarhq.Vinegar/data/vinegar/prefix/vinegar/versions/version-48a28da848b7420d/ClientSettings/ClientAppSettings.json
2024/01/06 15:53:10 discordrpc.go:16: Connecting to Discord RPC
2024/01/06 15:53:10 binary.go:100: WARNING: Could not initialize Discord RPC: drpc: discord is not running, disabling...
2024/01/06 15:53:10 binary.go:140: Launching WindowsPlayer (/app/bin/wine /home/user/.var/app/org.vinegarhq.Vinegar/data/vinegar/prefix/vinegar/versions/version-48a28da848b7420d/RobloxPlayerBeta.exe roblox-player:1+launchmode:play+gameinfo:OVnhWYknFW7vQ6BhG7L1A1sbjfWL9MbUk7X-AHVfCe5EmBhJlGmj3p0lCT15VRzXHSchBpYxO9SWZTsyHiWNKP-NzptHL0WAyvh2bCE8LmF0F2Uh9HdV9j--d7KlW_94WaQgYiz7orAtaq86xtMFKuO06Ksc3Gv0QpOk6Vdhkc_fpJmW_ZaZSh1MVN50rcVkDV7560rTCXbvdjn7V1Sb48T2FuHpEMObdtf4bo3RSYw+launchtime:1704552788918+placelauncherurl:https%3A%2F%2Fassetgame.roblox.com%2Fgame%2FPlaceLauncher.ashx%3Frequest%3DRequestFollowUser%26browserTrackerId%3D187460831737%26userId%3D3676913628+browsertrackerid:187460831737+robloxLocale:es_es+gameLocale:es_es+channel:)
03dc:err:esync:esync_init Failed to open esync shared memory file; make sure no stale wineserver instances are running without WINEESYNC.
2024/01/06 15:53:10 wine.go:56: Killing wineprefix
2024/01/06 15:53:10 vinegar.go:219: roblox: exit status 1
2024/01/06 15:53:32 splash.go:189: Opening log file: /home/ines/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/Player-2024-01-06T15:53:10+01:00.log

### System information
OS: Ubuntu 22.04 jammy
Kernel: x86_64 Linux 6.2.0-39-generic
DE: GNOME 41.7
CPU: AMD Ryzen 5 2600X Six-Core @ 12x 3,6
GPU: AMD Radeon RX 6600 (radeonsi, navi23, LLVM 15.0.7, DRM 3.49, 6.2.0-39-generic)
RAM: 4913MiB / 7855MiB

* Installation method:
Vinegar: v1.6.0 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Ryzen 5 2600X Six-Core Processor
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.2.0-39-generic
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: amdgpu 0000:0a:00.0 /sys/class/drm/card0

**Comment by apprehensions** [comment]
Kill the wineserver..
