### ISSUE TITLE
It's time to support NVK.

### ISSUE THREAD

**Issue by GlitchPhoenix98** [vinegarhq/vinegar#330]
NVK has been in development for over a year and is more than capable to be used on modern Linux systems.
We need to take the steps forward to provide support to users of this driver.
I have tried NVK and have gotten above 60 FPS on max graphics, proof in the link below.
https://youtu.be/8c2AbwLv6BY

#### Describe the solution you'd like
Provide help to users using the nouveau driver, with some exceptions being:

Must have GTX 16XX video cards or above

Use Linux version 6.7 or above; due to [power management patches](https://www.phoronix.com/news/Nouveau-GSP-Merged-Linux-6.7)

Having `nouveau.config=NvGspRm=1` in their kernel command line if using 30XX video cards or below.

#### Additional context
Video of NVK running Roblox at a stable framerate (60 or above):
https://youtu.be/8c2AbwLv6BY

**Comment by TeknosQuet** [comment]
What exactly are you asking for?

**Comment by apprehensions** [comment]
> Provide help to users using the nouveau driver

Consider making a patch to the documentation.
