### ISSUE TITLE
error 403

### ISSUE THREAD

**Issue by sunryse-uxu** [vinegarhq/vinegar#332]
Hello its my first time doing a bug report but mi issue i install vinegar a two or 3 days ago so my bus is my vinegar i try to open says 

![Captura de pantalla de 2024-01-10 14-46-50](https://github.com/vinegarhq/vinegar/assets/155909101/c49f1a0d-2a17-49f5-8d50-b17819e98ecd)
024/01/10 14:44:29 deployment.go:41: Fetching latest version of WindowsPlayer for channel live
2024/01/10 14:44:29 deployment.go:48: Fetched WindowsPlayer canonical version 0.607.0.6070550
2024/01/10 14:44:29 binary.go:275: Installing WindowsPlayer (version-48a28da848b7420d -> version-88cfc23f4e7d4e4b)
2024/01/10 14:44:29 cdn.go:23: Finding an accessible Roblox deploy mirror
2024/01/10 14:44:30 cdn.go:35: Found deploy mirror: https://setup.rbxcdn.com
2024/01/10 14:44:30 pkg_manifest.go:48: Fetching manifest for version-88cfc23f4e7d4e4b (https://setup.rbxcdn.com/channel/live/version-88cfc23f4e7d4e4b-rbxPkgManifest.txt)
2024/01/10 14:44:31 vinegar.go:219: fetch version-88cfc23f4e7d4e4b package manifest: bad status: 403 Forbidden
2024/01/10 14:44:33 splash.go:189: Opening log file: /home/~/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/Player-2024-01-10T14:44:29-05:00.log

**Comment by apprehensions** [comment]
Don't set the channel. Set it to nothing. the documentation explicitly says to not touch it.
