### ISSUE TITLE
I can't run roblox studio

### ISSUE THREAD

**Issue by brotherman123** [vinegarhq/vinegar#335]
When opening roblox studio it opens up 2 windows one saying: The program RobloxStudioBeta.exe has encountered a serious problem and needs to close. We are sorry for the inconvenience. And then it opens a wine debbuger window that i can't write on or edit. Deleting the wine debugger ends up in it crashing. Deleting the error window causes the wine debbuger to say 
![image](https://github.com/vinegarhq/vinegar/assets/156553255/d6cd8396-71ff-46af-97be-1bc9cda95053)
and then crashing. I cant fix it can someone help me?

**Comment by brotherman123** [comment]
I also forgot to say i use fedora 39

**Comment by lunarlettuce** [comment]
Please use `vinegar sysinfo` so that we can see your system information

**Comment by brotherman123** [comment]
> 1. Are you using the flatpak or the fedora package? (or did you build from source?)
> 2. If the answer to the above isn't flatpak, what wine version are you using?

Umm i am using wine 8.0.2 and i downloaded from fedora on discovery bcus i can't really like use the .flatpakref files cuz i am new with flatpak just not linux

**Comment by brotherman123** [comment]
and also i used sysinfo got this 
* Vinegar: v1.6.0 
* Distro: Fedora Linux 39 (Thirty Nine)
* Processor: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.9-200.fc39.x86_64
* Wine: wine-8.0.2
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card0
  * Card 1: nvidia 0000:01:00.0 /sys/class/drm/card1

**Comment by lunarlettuce** [comment]
Unfortunately, you aren't using the Flatpak. Seems like you have an existing package installation. However, your wine is also extremely outdated, so you should switch to using the Flatpak, which is on Wine 8.20

**Comment by brotherman123** [comment]
How do i do that idk how to get wine 8.20 if you could point me in a direction i would be greatful :D

**Comment by brotherman123** [comment]
I got it but roblox studio crashes upon trying to open games

**Comment by lunarlettuce** [comment]
@brotherman123 
See https://flathub.org/apps/org.vinegarhq.Vinegar, there should be an install button. 

Otherwise, look on flathub for installation instructions specific to your distro. If you need additional help, come to our Discord server, where we can communicate in real-time to get the problem fixed.

Closing because this is not a Vinegar bug
