### ISSUE TITLE
Roblox error. [PLAYER]

### ISSUE THREAD

**Issue by cooldudeseven7Dev** [vinegarhq/vinegar#336]
#### To Reproduce
Install Arch Linux
Install Vinegar (aur git)
Install Player
- Try to launch.

### Logs
They are attached here:
[Player-2024-01-16T05:39:29Z.log](https://github.com/vinegarhq/vinegar/files/13946084/Player-2024-01-16T05.39.29Z.log)
[Player-2024-01-16T05:40:13Z.log](https://github.com/vinegarhq/vinegar/files/13946085/Player-2024-01-16T05.40.13Z.log)
[Player-2024-01-16T05:41:33Z.log](https://github.com/vinegarhq/vinegar/files/13946086/Player-2024-01-16T05.41.33Z.log)
[Studio-2024-01-16T05:33:46Z.log](https://github.com/vinegarhq/vinegar/files/13946087/Studio-2024-01-16T05.33.46Z.log)
[Studio-2024-01-16T05:34:33Z.log](https://github.com/vinegarhq/vinegar/files/13946088/Studio-2024-01-16T05.34.33Z.log)
[Studio-2024-01-16T05:38:29Z.log](https://github.com/vinegarhq/vinegar/files/13946089/Studio-2024-01-16T05.38.29Z.log)

### System information

-------------------------------
* Vinegar: v1.6.0 (2abcbe54f64c7483d13a48679e11b772a548d97b)
* Distro: Arch Linux
* Processor: Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.10-arch1-1
* Wine: wine-8.21
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card1
*** I DO MEET THE REQUIREMENTS ***
```
* Vinegar: v1.6.0 (2abcbe54f64c7483d13a48679e11b772a548d97b)
* Distro: Arch Linux
* Processor: Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.10-arch1-1
* Wine: wine-8.21
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card1
```

**Comment by lunarlettuce** [comment]
I'm not clear what "no ./cache" means

**Comment by cooldudeseven7Dev** [comment]
> I'm not clear what "no ./cache" means, please clarify

> Can you post full logs

Heres the logs! I forgot! they are attached.
[Player-2024-01-16T05:39:29Z.log](https://github.com/vinegarhq/vinegar/files/13946068/Player-2024-01-16T05.39.29Z.log)
[Player-2024-01-16T05:40:13Z.log](https://github.com/vinegarhq/vinegar/files/13946069/Player-2024-01-16T05.40.13Z.log)
[Player-2024-01-16T05:41:33Z.log](https://github.com/vinegarhq/vinegar/files/13946070/Player-2024-01-16T05.41.33Z.log)
[Studio-2024-01-16T05:33:46Z.log](https://github.com/vinegarhq/vinegar/files/13946071/Studio-2024-01-16T05.33.46Z.log)
[Studio-2024-01-16T05:34:33Z.log](https://github.com/vinegarhq/vinegar/files/13946072/Studio-2024-01-16T05.34.33Z.log)
[Studio-2024-01-16T05:38:29Z.log](https://github.com/vinegarhq/vinegar/files/13946073/Studio-2024-01-16T05.38.29Z.log)

**Comment by lunarlettuce** [comment]
Where are you getting `No ./cache directory found.` from?

**Comment by cooldudeseven7Dev** [comment]
> Where are you getting `No ./cache directory found.` from?

dont worry, I found it. See this:

> > I'm not clear what "no ./cache" means, please clarify
> 
> > Can you post full logs
> 
> Heres the logs! I forgot! they are attached. [Player-2024-01-16T05:39:29Z.log](https://github.com/vinegarhq/vinegar/files/13946068/Player-2024-01-16T05.39.29Z.log) [Player-2024-01-16T05:40:13Z.log](https://github.com/vinegarhq/vinegar/files/13946069/Player-2024-01-16T05.40.13Z.log) [Player-2024-01-16T05:41:33Z.log](https://github.com/vinegarhq/vinegar/files/13946070/Player-2024-01-16T05.41.33Z.log) [Studio-2024-01-16T05:33:46Z.log](https://github.com/vinegarhq/vinegar/files/13946071/Studio-2024-01-16T05.33.46Z.log) [Studio-2024-01-16T05:34:33Z.log](https://github.com/vinegarhq/vinegar/files/13946072/Studio-2024-01-16T05.34.33Z.log) [Studio-2024-01-16T05:38:29Z.log](https://github.com/vinegarhq/vinegar/files/13946073/Studio-2024-01-16T05.38.29Z.log)

**Comment by lunarlettuce** [comment]
Try using the Flatpak, it generally resolves most issues. It's also difficult to debug source/package installations, so we should begin with the easiest step first.

**Comment by cooldudeseven7Dev** [comment]
> Try using the Flatpak, it generally resolves most issues. It's also difficult to debug source/package installations, so we should begin with the easiest step first.

Alright, How Do I uninstall the source version? I installed the git one
and ran `makepkg -si`.

**Comment by cooldudeseven7Dev** [comment]
> Try using the Flatpak, it generally resolves most issues. It's also difficult to debug source/package installations, so we should begin with the easiest step first.

Also, It might take me a while to respond to your next post. I will be back in ~15 mins. Thanks for all of your help

**Comment by Cristiandis** [comment]
> > Try using the Flatpak, it generally resolves most issues. It's also difficult to debug source/package installations, so we should begin with the easiest step first.
> 
> Alright, How Do I uninstall the source version? I installed the git one and ran `makepkg -si`.

If you made makepkg you should be able to uninstall it with pacman

**Comment by Cristiandis** [comment]
sudo pacman -Rs vinegar

**Comment by cooldudeseven7Dev** [comment]
> sudo pacman -Rs vinegar

Thanks! Anyways, Im installing the Flatpak!

**Comment by cooldudeseven7Dev** [comment]
### UPDATE!
I found this in the vinegar hq.
![image](https://github.com/vinegarhq/vinegar/assets/100153927/2d3157a3-a577-4048-acd8-e64a1df78ad8)
#### The error is this! Now all I need to learn is how to do this patch. Do you guys know how? Thanks for all of your support.

**Comment by Cristiandis** [comment]
> ### UPDATE!
> I found this in the vinegar hq. ![image](https://private-user-images.githubusercontent.com/100153927/296958006-2d3157a3-a577-4048-acd8-e64a1df78ad8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODk3NzAsIm5iZiI6MTcwNTM4OTQ3MCwicGF0aCI6Ii8xMDAxNTM5MjcvMjk2OTU4MDA2LTJkMzE1N2EzLWE1NzctNDA0OC1hY2Q4LWU2NGExZGY3OGFkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwNzE3NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjQ1MTkwZTMyMjkzOTM0MzFhNzM1ZGY5M2U3NTY5NzI2MDNmODc0NmYyMjMwZDljMDViZmRkZmQyYmE1YWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lOannVUyJ0lWOjZepm2PEl0oXP3LISBFQJLjAPDVmNA)
> 
> #### The error is this! Now all I need to learn is how to do this patch. Do you guys know how? Thanks for all of your support.

The flatpak wine is already patched to work

**Comment by apprehensions** [comment]
Bruh.

**Comment by apprehensions** [comment]
User does not meet minimum requirements nor has used flatpak despite it being reccomended.

**Comment by cooldudeseven7Dev** [comment]
Ah yes. Sorry. I will begin to read the documentations!

[what actually is wrong with me]
