### ISSUE TITLE
Different Wine For Player and Studio

### ISSUE THREAD

**Issue by krakow10** [vinegarhq/vinegar#338]
#### Is your feature request related to a problem? Please describe.
I have found that using wine-ge works great with Roblox Player and using wine-tkg with vulkan child window patch works great on studio.

#### Describe the solution you'd like
I would like to be able to have multiple wine versions installed and specify which one to use for Player and Studio by config.

#### Describe alternatives you've considered
Installing and uninstalling wine packages and editing configs every time I switch between studio and player.

**Comment by apprehensions** [comment]
Implemented in f58e955beeebd28ee644565d2ea03f9c59b1360b
