### ISSUE TITLE
Sorry for being back here :( Problem with flatpak

### ISSUE THREAD

**Issue by brotherman123** [vinegarhq/vinegar#339]
I tried flatpak no work :(

`vinegar sysinfo`

* Vinegar: v1.6.0 
* Distro: Fedora Linux 39 (Thirty Nine)
* Processor: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.9-200.fc39.x86_64
* Wine: wine-8.0.2
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card0
  * Card 1: nvidia 0000:01:00.0 /sys/class/drm/card1

So I have been experiencing some issues with flatpak version. At first Roblox studio opened... Twice, once I opened it first time it crashed when clicking on my experiences button the text was scrambled. After I could click the my experiences button crashes upon clicking game probably due to an error with a file. Then it never opened again. I restarted it no luck... waited 30 mins no luck. I am doing  `sudo dnf update` to see if a new vinegar update is out seems to be updating something to do with kernel. I don't know if 3 years of Linux is enough to be considered not a beginner but I am not new.

**Comment by lunarlettuce** [comment]
You're still not running the Flatpak.

**Comment by Noted-Jrelvas** [comment]
The Flatpak.

**Comment by brotherman123** [comment]
I did `flatpak install vinegar`

**Comment by lunarlettuce** [comment]
Do `flatpak install org.vinegarhq.Vinegar`, and make sure your native installation is removed.

**Comment by brotherman123** [comment]
I don;t know how to delete it still not that good :(

**Comment by brotherman123** [comment]
OMG ITS WORKING

**Comment by Florennum** [comment]
⚠️ user does not have 3 years of experience ⚠️

**Comment by Noted-Jrelvas** [comment]
Flatpak once again triumphs.

**Comment by brotherman123** [comment]
Wait
no without flat

**Comment by brotherman123** [comment]
but infinite loading

**Comment by Noted-Jrelvas** [comment]
![guess-ill-die-meme-template-5pors](https://github.com/vinegarhq/vinegar/assets/55360900/41dc4617-4f70-42ec-9ac1-f172ee8a89c4)

**Comment by brotherman123** [comment]
I still have not removed it the native one flatpak already installed

**Comment by Noted-Jrelvas** [comment]
`sudo dnf remove vinegar `
`flatpak run org.vinegarhq.Vinegar`

**Comment by brotherman123** [comment]
thank you

**Comment by brotherman123** [comment]
help
![image](https://github.com/vinegarhq/vinegar/assets/156553255/0db69cb4-4943-471c-981c-6710cb473100)

**Comment by reflexran** [comment]
did you run player and studio at the same time?

**Comment by brotherman123** [comment]
No tkg i think broke it

**Comment by Noted-Jrelvas** [comment]
Hmm that's new. Have you tried resetting the prefix? (`flatpak run org.vinegarhq. Vinegar kill`)

**Comment by reflexran** [comment]
delete that space

**Comment by brotherman123** [comment]
idk how

**Comment by reflexran** [comment]
open a terminal and type `htop` then press f3 and search for wine

**Comment by brotherman123** [comment]
Invalid id when resseting prefiz

**Comment by brotherman123** [comment]
htop closest top

**Comment by reflexran** [comment]
wait did it just stop working casually or did you change something?

**Comment by reflexran** [comment]
> htop closest top

is there any process called wineserver?

**Comment by brotherman123** [comment]
wine-tkg change it did (updating blah blah)

**Comment by brotherman123** [comment]
no

**Comment by reflexran** [comment]
then type this in `flatpak run org.vinegarhq.Vinegar delete`

**Comment by Noted-Jrelvas** [comment]
Hmm, I'm having a hard time following this... Join our Discord server so we can try to help you better and not clutter this issue up: https://discord.com/invite/ssDfQvdSbj

**Comment by Cristiandis** [comment]
> Hmm, I'm having a hard time following this... Join our Discord server so we can try to help you better and not clutter this issue up: https://discord.com/invite/ssDfQvdSbj

![remix-d138b77d-d7b7-4076-9327-775e82fec6a4](https://github.com/vinegarhq/vinegar/assets/112336919/4014eb92-fc02-4722-a60e-5e8647f51eb8)

**Comment by reflexran** [comment]
> no

join the discord and open a post in the helpdesk

**Comment by brotherman123** [comment]
I am so sorry i don't have discord it is blocked on my coputer i only 11

**Comment by KornPlays** [comment]
you need to be 13 on github too lol

**Comment by reflexran** [comment]
> I am so sorry i don't have discord it is blocked on my coputer i only 11

so you've been using linux since you were 9?

**Comment by reflexran** [comment]
you said 3 years of experience

**Comment by brotherman123** [comment]
ye

**Comment by Cristiandis** [comment]
@KornPlays why are you here

**Comment by Cristiandis** [comment]
Stop lurking like a creep

**Comment by brotherman123** [comment]
ok i have to leave if you can find any way to uninstall kpg help

**Comment by Noted-Jrelvas** [comment]
Okay. I can certainly respect the effort. Let's try to keep things here on-topic.

Could you run `flatpak run org.vinegarhq.Vinegar ` again and share the output please?

**Comment by brotherman123** [comment]
yes 
* Vinegar: v1.6.0 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.11-200.fc39.x86_64
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card0
  * Card 1: nvidia 0000:01:00.0 /sys/class/drm/card1

**Comment by lunarlettuce** [comment]
Looks like you're on the Flatpak now

**Comment by brotherman123** [comment]
wine 9.0-rc5

**Comment by brotherman123** [comment]
wine-kpg

**Comment by lunarlettuce** [comment]
...what?

**Comment by Noted-Jrelvas** [comment]
???

**Comment by Cristiandis** [comment]
Do not use custom wine's on flatpak

> wine-kpg

Also wtf is wine-kpg

**Comment by brotherman123** [comment]
ye idk either 
![image](https://github.com/vinegarhq/vinegar/assets/156553255/f3114ebd-482b-4562-a0fc-3345533413f5)

**Comment by reflexran** [comment]
ok please could you try to use the default flatpak wine

**Comment by brotherman123** [comment]
i don;t know how to

**Comment by reflexran** [comment]
> ye idk either ![image](https://private-user-images.githubusercontent.com/156553255/297207821-f3114ebd-482b-4562-a0fc-3345533413f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NDQ4NTcsIm5iZiI6MTcwNTQ0NDU1NywicGF0aCI6Ii8xNTY1NTMyNTUvMjk3MjA3ODIxLWYzMTE0ZWJkLTQ4MmItNDU2Mi1hMGZjLTMzNDU1MzM0MTNmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQyMjM1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTU1Y2E0YWY1YTUxYjA0YTRmNjI4NDYxMDM5OTJlMWMyODI4N2U4N2JmYzA0ODg2ZjVjMWE1MjU5ZTlkZmM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xEyCbXSHHdCBqNziqRFngd6YHqQ27hs_zTQnP38jwRQ)

that's an rc release it's unstable

**Comment by Cristiandis** [comment]
> ye idk either ![image](https://private-user-images.githubusercontent.com/156553255/297207821-f3114ebd-482b-4562-a0fc-3345533413f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NDQ4NTcsIm5iZiI6MTcwNTQ0NDU1NywicGF0aCI6Ii8xNTY1NTMyNTUvMjk3MjA3ODIxLWYzMTE0ZWJkLTQ4MmItNDU2Mi1hMGZjLTMzNDU1MzM0MTNmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQyMjM1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTU1Y2E0YWY1YTUxYjA0YTRmNjI4NDYxMDM5OTJlMWMyODI4N2U4N2JmYzA0ODg2ZjVjMWE1MjU5ZTlkZmM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xEyCbXSHHdCBqNziqRFngd6YHqQ27hs_zTQnP38jwRQ)

Are you just running wine, like the wine command

**Comment by brotherman123** [comment]
`winecfg`

**Comment by Cristiandis** [comment]
💀

**Comment by lunarlettuce** [comment]
Okay yeah, you're accessing your system's wine, not the Flatpak.

**Comment by reflexran** [comment]
> i don;t know how to

`flatpak run org.vinegarhq.Vinegar edit` then delete everything in there

**Comment by brotherman123** [comment]
i never installed flatpak wine it was compiled by me

**Comment by reflexran** [comment]
you should also run `flatpak run org.vinegarhq.Vinegar delete` after that

**Comment by Cristiandis** [comment]
> `winecfg`

You need to run `flatpak run org.vinegarhq.Vinegar exec winecfg` to access vinegar's winecfg

**Comment by reflexran** [comment]
> i never installed flatpak wine it was compiled by me

it comes pre-installed with flatpak

**Comment by Noted-Jrelvas** [comment]
Vinegar's Flatpak includes a Wine build patched to fix several issues with Roblox.

**Comment by brotherman123** [comment]
Ok i'll go reinstall from flat

**Comment by reflexran** [comment]
> Ok i'll go reinstall from flat

why?

**Comment by brotherman123** [comment]
becuase my wine is messed up

**Comment by reflexran** [comment]
> becuase my wine is messed up

you mean the flatpak wine?

**Comment by brotherman123** [comment]
![image](https://github.com/vinegarhq/vinegar/assets/156553255/176f6a47-5a19-442e-864a-3140875e8784)

**Comment by brotherman123** [comment]
which one

**Comment by reflexran** [comment]
> ![image](https://private-user-images.githubusercontent.com/156553255/297208587-176f6a47-5a19-442e-864a-3140875e8784.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NDUxMjgsIm5iZiI6MTcwNTQ0NDgyOCwicGF0aCI6Ii8xNTY1NTMyNTUvMjk3MjA4NTg3LTE3NmY2YTQ3LTVhMTktNDQyZS04NjRhLTMxNDA4NzVlODc4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQyMjQwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTkyZTY3NGM0NWIxMjUxYTdhNWI2NDkzN2M5ZTYyNWNkZjIxNjFiMjU4NTEzNTA4ZWI0OWU1ZTYwN2UxYmI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K0bPKCRxHgrOLTGtFMGU0o7-K4pHmYsiBzVA3skfxXg)

????????????????????????

**Comment by brotherman123** [comment]
wine flatpak

**Comment by Cristiandis** [comment]
> which one

None vinegar comes with its own

**Comment by brotherman123** [comment]
alr i did installl vinegar from flatpak

**Comment by reflexran** [comment]
> alr i did installl vinegar from flatpak

stop for a second

**Comment by Cristiandis** [comment]
> alr i did installl vinegar from flatpak

Have you removed the source package

**Comment by brotherman123** [comment]
idk how to

**Comment by reflexran** [comment]
> 3 years of experience

**Comment by Cristiandis** [comment]
> idk how to

How did you originally install vinegar

**Comment by Cristiandis** [comment]
`dnf install vinegar?`

**Comment by brotherman123** [comment]
with discover

**Comment by reflexran** [comment]
> with discover

alr listen

**Comment by brotherman123** [comment]
i deleted that one discover one

**Comment by reflexran** [comment]
run `flatpak run org.vinegarhq.Vinegar edit` and screenshot it

**Comment by reflexran** [comment]
> i deleted that one discover one

they're literally the same

**Comment by brotherman123** [comment]
no flatpak worked faster+better and could comprehend 2 seconds of studio

**Comment by brotherman123** [comment]
![image](https://github.com/vinegarhq/vinegar/assets/156553255/ab00ff85-f5a7-4dbb-b14f-56e1102beeea)

**Comment by Cristiandis** [comment]
So why are we continuing if flatpak works

**Comment by reflexran** [comment]
> ![image](https://private-user-images.githubusercontent.com/156553255/297209384-ab00ff85-f5a7-4dbb-b14f-56e1102beeea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NDU0MDQsIm5iZiI6MTcwNTQ0NTEwNCwicGF0aCI6Ii8xNTY1NTMyNTUvMjk3MjA5Mzg0LWFiMDBmZjg1LWY1YTctNGRiYi1iMTRmLTU2ZTExMDJiZWVlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQyMjQ1MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGU3MGFhMDcwNmM1NTMwODU4OWFlN2Q0NGEzYTlkYmExZGMzMTU1YTE0Mzk3MzAwMzZhYzhkYzI4NjJiMzAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gJPEo5gC9gJV0uRJc3zeckin68f91ftVzm0cITJQMMM)

that should be fine

**Comment by reflexran** [comment]
are you still having issues?

**Comment by Cristiandis** [comment]
Listen @brotherman123 does roblox work correctly

**Comment by brotherman123** [comment]
![image](https://github.com/vinegarhq/vinegar/assets/156553255/fffe6b92-6084-468c-a206-7299f59efcc5)

**Comment by Cristiandis** [comment]
> ![image](https://private-user-images.githubusercontent.com/156553255/297209587-fffe6b92-6084-468c-a206-7299f59efcc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NDU0NzYsIm5iZiI6MTcwNTQ0NTE3NiwicGF0aCI6Ii8xNTY1NTMyNTUvMjk3MjA5NTg3LWZmZmU2YjkyLTYwODQtNDY4Yy1hMjA2LTcyOTlmNTllZmNjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQyMjQ2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDUwMTkyMjY5YjZmODI3OTQ0YWUyNDhmZDYyN2UwYjIyZDY3Mjk2YmQyZTVlMmNiYzQ4NzIzYmYyZDFjODBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GUE3VGMxmONyeyIe8tIcpPvX46hw8u7RnCvPVHTKwbA)

How are you running this

**Comment by reflexran** [comment]
> ![image](https://private-user-images.githubusercontent.com/156553255/297209587-fffe6b92-6084-468c-a206-7299f59efcc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NDU0NzUsIm5iZiI6MTcwNTQ0NTE3NSwicGF0aCI6Ii8xNTY1NTMyNTUvMjk3MjA5NTg3LWZmZmU2YjkyLTYwODQtNDY4Yy1hMjA2LTcyOTlmNTllZmNjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQyMjQ2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTA4YzljMTYyNzRjNzBhZDNkMzlhN2JhZDI4MmFhY2JlMzZiNTM1YTJlYzZlM2FlMzEzZDUwNzg2ZDc4NWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mGsjNq_eFBD_Vb4eft_8a47RwrZcxZOZUQ_67DgikZ0)

run `flatpak run org.vinegarhq.Vinegar studio` and send logs

**Comment by brotherman123** [comment]
no this is regular roblox

**Comment by brotherman123** [comment]
studio gives same error

**Comment by reflexran** [comment]
> no this is regular roblox

???????

**Comment by brotherman123** [comment]
like just roblox no studio

**Comment by reflexran** [comment]
> like just roblox no studio

run `flatpak run org.vinegarhq.Vinegar player` and send logs

**Comment by brotherman123** [comment]
![image](https://github.com/vinegarhq/vinegar/assets/156553255/1c9d7965-3e5e-4888-9239-6b95741dec27)

**Comment by brotherman123** [comment]
![image](https://github.com/vinegarhq/vinegar/assets/156553255/d6e81216-7c13-4c74-be4f-7dc4d946dbda)

**Comment by reflexran** [comment]
> ![image](https://private-user-images.githubusercontent.com/156553255/297210130-d6e81216-7c13-4c74-be4f-7dc4d946dbda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NDU2ODAsIm5iZiI6MTcwNTQ0NTM4MCwicGF0aCI6Ii8xNTY1NTMyNTUvMjk3MjEwMTMwLWQ2ZTgxMjE2LTdjMTMtNGM3NC1iZTRmLTdkYzRkOTQ2ZGJkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQyMjQ5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWQyNmUxOTY5OTVlMjRhZTJhMjNjNWI3ZmQ5YmVlZTg0MjVhYzVlODg2YjM0YTlhZThkYThhYjc3NDBjNTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GTcAn-Jl32F0gHNFeZxmzlyCDFwjzInjE0UzshDeK2U)

what distro are you using

**Comment by brotherman123** [comment]
fedora 39

**Comment by reflexran** [comment]
> fedora 39

are you using the rpmfusion nvidia driver?

**Comment by brotherman123** [comment]
i donot no

**Comment by reflexran** [comment]
so you're using nouveau

**Comment by lunarlettuce** [comment]
Sorry, it seems like we're having a bit of a language barrier here. Are you comfortable continuing in English, or is there another language you are comfortable with?

**Comment by brotherman123** [comment]
no im fine woith english

**Comment by brotherman123** [comment]
it was slang sry mispell

**Comment by reflexran** [comment]
> it was slang sry mispell

did you install your nvidia drivers?

**Comment by brotherman123** [comment]
idk how to

**Comment by brotherman123** [comment]
too risky

**Comment by brotherman123** [comment]
i am not root of my computer

**Comment by brotherman123** [comment]
here some logs for help
[RobloxPlayerLauncher_d3d11.log](https://github.com/vinegarhq/vinegar/files/13956473/RobloxPlayerLauncher_d3d11.log)

**Comment by brotherman123** [comment]
I just recently updated to 39 from 38

**Comment by reflexran** [comment]
> I just recently updated to 39 from 38

do only your parents have root to your pc?

**Comment by brotherman123** [comment]
I hope the logs help

**Comment by brotherman123** [comment]
ye i will soon be root on the weekend

**Comment by brotherman123** [comment]
becuase this is an old work pc soon it will be mine just has to take the stuff of theirs out

**Comment by Noted-Jrelvas** [comment]
I recommend asking them for help. They're probably have the knowledge necessary to get you setup.

**Comment by brotherman123** [comment]
they don't understand wine and new stuff like openGL to well

**Comment by brotherman123** [comment]
old sysinfo bcus vinegar sysinfo not working 
Vinegar: v1.6.0
Distro: Fedora Linux 39 (Thirty Nine)
Processor: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
Supports AVX: true
Supports split lock detection: false
Kernel: 6.6.9-200.fc39.x86_64
Wine: wine-8.0.2
Cards:
Card 0: i915 0000:00:02.0 /sys/class/drm/card0
Card 1: nvidia 0000:01:00.0 /sys/class/drm/card1

**Comment by brotherman123** [comment]
![image](https://github.com/vinegarhq/vinegar/assets/156553255/6b3cbfb8-aa1a-4649-8680-ad908431126a)
should i delete wine mono windows support???

**Comment by brotherman123** [comment]
wait that is wine i wont do it

**Comment by reflexran** [comment]
> wait that is wine i wont do it

ok listen, you should talk about this with your parents, they have root access to your system so they are the only ones who can fix this issue

**Comment by brotherman123** [comment]
ok

**Comment by Noted-Jrelvas** [comment]
Well... There's not a lot we can do to help you if you already have a non-flatpak version of Vinegar installed in your system but don't have the permission to remove it, or if the drivers aren't configured.

Your parents are more than welcome to participate in this issue, we'll walk them through the process of Vinegar getting setup. There's something highly unusual with your system and I'm afraid we're powerless to fix it without the help of the system's admin. Sorry, there's just no other way we can help I'm afraid.

**Comment by brotherman123** [comment]
No i deleted that a loooong time ago

**Comment by brotherman123** [comment]
i use flatpak now

**Comment by Alxhr0** [comment]
Are you sure?

**Comment by brotherman123** [comment]
yes 100%

**Comment by brotherman123** [comment]
but i need to uninstall wine-kpg

**Comment by brotherman123** [comment]
plus configured drivers

**Comment by brotherman123** [comment]
I am good

**Comment by brotherman123** [comment]
> Well... There's not a lot we can do to help you if you already have a non-flatpak version of Vinegar installed in your system but don't have the permission to remove it, or if the drivers aren't configured.
> 
> Your parents are more than welcome to participate in this issue, we'll walk them through the process of Vinegar getting setup. There's something highly unusual with your system and I'm afraid we're powerless to fix it without the help of the system's admin. Sorry, there's just no other way we can help I'm afraid.

I have switched to flatpak and configured drivers i am now good but wine-kpg still installed

**Comment by Noted-Jrelvas** [comment]
> but i need to uninstall wine-kpg
Do you mean tkg?

**Comment by brotherman123** [comment]
yes

**Comment by brotherman123** [comment]
only problem plus some logs @
[RobloxPlayerLauncher_d3d11.log](https://github.com/vinegarhq/vinegar/files/13956656/RobloxPlayerLauncher_d3d11.log)

**Comment by Noted-Jrelvas** [comment]
Okay, so Vinegar Flatpak shouldn't be using wine-tkg, even if it's installed in your system. It uses a wine binary bundled inside of itself.

**Comment by brotherman123** [comment]
I need to uninstall it but I don't know how i tried using wine uninstaller but would not give me the option.

**Comment by Noted-Jrelvas** [comment]
Did you install wine-tkg via dnf/rpm?

**Comment by brotherman123** [comment]
dnf

**Comment by Noted-Jrelvas** [comment]
Alright, try uninstalling with `sudo dnf remove wine-tkg`.

**Comment by brotherman123** [comment]
ok

**Comment by brotherman123** [comment]
here
![image](https://github.com/vinegarhq/vinegar/assets/156553255/9e10bcab-1d55-4846-a602-d965f3451796)

**Comment by brotherman123** [comment]
i used this website https://copr.fedorainfracloud.org/coprs/patrickl/wine-tkg/

**Comment by Noted-Jrelvas** [comment]
Apologies, I'm not familiar with fedora wine packaging. Looking at the copr docs, try this instead: `sudo dnf remove wine wine-mono mingw32-wine-gecko mingw64-wine-gecko wine-dxvk* winetricks yabridge libcurl-gnutls`

**Comment by brotherman123** [comment]
That deletes wine

**Comment by Noted-Jrelvas** [comment]
Yes, but the wine it deletes is the wine sourced from the wine-tkg COPR.

**Comment by brotherman123** [comment]
oh ok

**Comment by brotherman123** [comment]
did it and tested it on a game that requires proton

**Comment by brotherman123** [comment]
It worked

**Comment by brotherman123** [comment]
I have to go

**Comment by brotherman123** [comment]
Hello I have finally got roblox studio and roblox to open thank you to everyone who helped

**Comment by brotherman123** [comment]
![image](https://github.com/vinegarhq/vinegar/assets/156553255/f2dfd835-e2d4-4b36-a982-5c7c29586bbe)

**Comment by brotherman123** [comment]
1 problem is you have to plug the `flatpak run org.vinegarhq.Vinegar studio` into konsole to run rblx studio

**Comment by lunarlettuce** [comment]
run roblox studio from the browser.

**Comment by TeknosQuet** [comment]
Not related to the issue, but a good suggestion is to formulate (construct) your comments in a way where you have only one big comment instead of several smaller ones. It's annoying to contributors and people who participate in issues to receive several notifications every time one of them comments.

**Comment by RushingAlien** [comment]
![gambar](https://github.com/vinegarhq/vinegar/assets/80886145/a9f17815-553c-42ad-84ec-6426adea9208)
or even just use the desktop shortcut provided

**Comment by brotherman123** [comment]
Oh yeah my bad
