### ISSUE TITLE
Remove all mentions of Roblox and images of the Roblox branding

### ISSUE THREAD

**Issue by apprehensions** [vinegarhq/vinegar#34]
> The use of the Roblox name (and any name similar to Roblox), badge, logo, and other trademarks including “Classic Roblox Avatars” (R6 and R15 Avatars as defined in our Terms of Use) is **not permitted on physical products or commercial content and may not be tied to the development, distribution or sale of any products or services** (including, but not limited to, physical products, packaging, retail displays, services, NFTs, film, TV, books, stage shows or amusement parks) without a Roblox licensing agreement.

> **Don't use the Roblox name, logos, badge, or “Classic Roblox Avatars”** in commercial uses including physical products , packaging, retail displays, NFTs, film, TV, books, stage shows or amusement parks without authorization and a licensing agreement from Roblox. Please note that we do not grant unsolicited requests for commercial use.

source: https://en.help.roblox.com/hc/en-us/articles/115001708126

**Comment by Thelolguy1** [comment]
We have decided not to take this approach, as Vinegar is not a commercial product (and grapejuice has no problem using Roblox logos).
