### ISSUE TITLE
Player suddenly started crashing while Studio still works fine? - Error 5

### ISSUE THREAD

**Issue by itsaerosphere** [vinegarhq/vinegar#342]
#### Describe the bug
I have no idea what happened, but up until about 30 mins ago, the player was working just fine. Then, out of the blue, it started crashing on launch. Studio doesn't seem to have the same issue.

I'm not sure if it's related to an update Roblox pushed today,  because I didn't notice Vinegar installing an update for the player, but I did notice it installing an update for Studio.

#### To Reproduce
Update Roblox to version-75acb088f43843cf.
Attempt to run Roblox Player by any regular means.

### Logs
[Player-2024-01-18T21:47:43-05:00.log](https://github.com/vinegarhq/vinegar/files/13983691/Player-2024-01-18T21.47.43-05.00.log)

### System information

* Installation method:
```* Vinegar: v1.6.0 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Ryzen 9 5900X 12-Core Processor
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.7.0-arch3-1
* Wine: v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: amdgpu 0000:08:00.0 /sys/class/drm/card1
```

**Comment by itsaerosphere** [comment]
After a bit of digging, I eventually found out that yes, Roblox did update their player.

For anyone else having this issue, I recommend doing the following:
Add `forced_version = "version-88cfc23f4e7d4e4b"` to [player] in your config for the time being.

Gotta credit kekemail on the Vinegar Discord for that tip.

**Comment by SylvKT** [comment]
If this is closed, does this mean this issue won't be fixed?

**Comment by apprehensions** [comment]
The solution is there, and the cause is due to a roblox update.

**Comment by jackyard86** [comment]
> The solution is there, and the cause is due to a roblox update.

Some games tries to verify client version and in that case I can't play the game. I don't know the detail of this, but here's one of those games: https://www.roblox.com/games/583507031/Papers-Please-Border-Simulator

**Comment by Noted-Jrelvas** [comment]
![Uploading guess-ill-die-meme-template-5pors.jpg…]()

**Comment by Noted-Jrelvas** [comment]
> Some games try to verify client version, and I can't play the game if that's the case. While I don't know much details on this, one example of such a game that checks the client version is this: https://www.roblox.com/games/583507031/Papers-Please-Border-Simulator

![guess-ill-die-meme-template-5pors](https://github.com/vinegarhq/vinegar/assets/55360900/8bfd9d82-f4c7-42d3-a01e-c4265a28c4c0)

**Comment by KelpJerky** [comment]
I tried switching to wine versions and it worked temporarily then crashed every time.

**Comment by jackyard86** [comment]
Well, I don't really know anything about programming, and I just shared my experience to see if that does any help.

Sorry if my comment didn't help.

**Comment by SylvKT** [comment]
> The solution is there, and the cause is due to a roblox update.

This "solution" won't work forever. This is just a workaround.

**Comment by SylvKT** [comment]
Aaaand it seems like it doesn't work anymore. I'm stuck on infinitely Joining Server
