### ISSUE TITLE
Is it working? Im getting and error on pc, tried on laptop and also stops working. Both have Flatpak's

### ISSUE THREAD

**Issue by wotikama** [vinegarhq/vinegar#344]
#### Describe the bug
- [ ] I have searched open and closed issues to make sure that the bug has not yet been reported
- [ ] I have read the [minimum requirements](https://vinegarhq.org/Requirements/index.html).

#### To Reproduce
Steps to reproduce the behavior.

### Logs
Reference log file contents, which are usually located in `~/.cache/vinegar/logs` or `~/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/` for Flatpak, of a run reproducing the bug

### System information

* Installation method:

**Comment by apprehensions** [comment]
Read the issue template.
