### ISSUE TITLE
Update flatpak

### ISSUE THREAD

**Issue by account183892** [vinegarhq/vinegar#345]
Flatpak version is 1.6, newest version of Vinegar is 1.6.1. I believe the issues such as #348 are related due to lack of patches needed to make Roblox run.

**Comment by lunarlettuce** [comment]
Yeah, this is gonna take a while...

**Comment by reflexran** [comment]
> Yeah, this is gonna take a while...

actually curious, what patch/es is/are causing wine not to compile?

**Comment by lunarlettuce** [comment]
segment register revert, childwindow patch, and the wayland mouselock patch

**Comment by apprehensions** [comment]
Just rebase smh ain't hard

**Comment by apprehensions** [comment]
https://github.com/flathub/org.vinegarhq.Vinegar/pull/14
