### ISSUE TITLE
add to arch user repository

### ISSUE THREAD

**Issue by Exponential-Workload** [vinegarhq/vinegar#35]
afaik, currently, it's not on the [arch user repository](https://aur.archlinux.org/) (AUR) - adding it there would make it easier for arch users to install it like any other 3rd-part community-maintained application

**Comment by apprehensions** [comment]
I'm not sure if the AUR will except making Go AUR packages with `make`, and i think they would much prefer to use `go build` by hand. I suppose for someone that handles the AUR packages @tacheometry should handle it; unless you want to.

**Comment by tacheometry** [comment]
Per the [submission guidelines](https://wiki.archlinux.org/title/AUR_submission_guidelines), what's inside an Arch PKGBUILD doesn't really matter. It's just a place for install scripts.

**Comment by tacheometry** [comment]
- [ ] Make PKGBUILD
- [ ] Add to AUR

**Comment by Nullmatic** [comment]
I made up a quick basic PKGBUILD for the AUR. Any feedback would be helpful since it is my first time doing this.

```
# Maintainer: Nullmatic <schullo.alex@pm.me>

pkgname=vinegar-git
pkgver=2.3.4.r1.g79d2d78
pkgrel=1
pkgdesc="A transparent wrapper for Roblox Player and Roblox Studio"
arch=(x86_64)
url="https://github.com/vinegarhq/vinegar"
license=('GPL3')
depends=('go')
makedepends=('git')

provides=('vinegar')
conflicts=('vinegar')

install=
source=("${pkgname}::git+https://github.com/vinegarhq/vinegar.git")
md5sums=('SKIP')

pkgver() {
    cd ${pkgname}
    git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g;s/^v//'
}

build() {
	cd "$pkgname"
	make
}

package() {
	cd "$pkgname"
	make DESTDIR="$pkgdir/" install
    make mime
}
```

**Comment by orowith2os** [comment]
Copied from the Discord:

I'd like to point out that there might not be really any benefit to doing so. The flatpak works on Arch just as well as it does on Fedora or Ubuntu or any other distro. And an AUR package would involve dealing with arch-specific fuckery, like library versioning.

Not from the Discord:

There's nothing wrong with having an AUR package, but there's already a better alternative that benefits everyone and is easier to maintain and support, as it's a more stable environment.

**Comment by Thelolguy1** [comment]
I agree. There's no problem with having an AUR package and I think it's implied based on the fact that it's a user supported repository that it may be unstable. It still would be nice to have another distribution method.

**Comment by apprehensions** [comment]
https://aur.archlinux.org/packages/vinegar

Thanks to @thecomputerguy96
