### ISSUE TITLE
Roblox opens but Vinegar stuck on "Launching Player"

### ISSUE THREAD

**Issue by yegetshalaay** [vinegarhq/vinegar#353]
#### Describe the bug
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported
- [ ] I have read the [minimum requirements](https://vinegarhq.org/Requirements/index.html). Returns with 404.

Roblox can run without problems but Vinegar stuck on "Launching Player" state. Closing or cancelling it kills Roblox. Closing Roblox kills Vinegar message after a while. It also didn't give warning after opening something that requires browser (notifications, settings, etc.).

#### To Reproduce
Steps to reproduce the behavior.
1. Open Vinegar
2. Wait for Roblox homepage to open

### Logs
Reference log file contents, which are usually located in `~/.cache/vinegar/logs` or `~/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/` for Flatpak, of a run reproducing the bug
[Player-2024-02-02T00:12:43+03:00.log](https://github.com/vinegarhq/vinegar/files/14131097/Player-2024-02-02T00.12.43%2B03.00.log)

### System information

* Installation method: vinegar-git package from AUR using AUR helper paru

* Vinegar: v1.6.1 (e7386f4dd869db1a05dc40e85b9df4138bbfbac5)
* Distro: Arch Linux
* Processor: AMD Ryzen 5 1600 Six-Core Processor
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.7.2-zen1-2-zen
* Wine: wine-8.0-1630-g66cd5c1c1f1
* Cards:
  * Card 0: amdgpu 0000:09:00.0 /sys/class/drm/card1

#### Additional context
It happened after system update.
![resim](https://github.com/vinegarhq/vinegar/assets/91019435/4805c710-1d2a-467e-92e1-6130b85df378)

**Comment by apprehensions** [comment]
Thanks for reporting.

**Comment by yegetshalaay** [comment]
Seems to be fixed with AUR package `vinegar-git` version `1.6.1.r24.g254fed4-1`

**Comment by apprehensions** [comment]
This error was not actually completed. The error was due to our Roblox log directory fsnotify watcher returning early due to not existing.
