### ISSUE TITLE
roblox encountered a error

### ISSUE THREAD

**Issue by SFYMMIK** [vinegarhq/vinegar#358]
i was just trying to play roblox and this happened
![image](https://github.com/vinegarhq/vinegar/assets/84783879/2ec9b536-7f56-4b2f-ab65-caf9940e276f)

**Comment by jrelvas-ipc** [comment]
Need more information. Please follow the template and provide the output of `sysinfo `.

**Comment by SFYMMIK** [comment]
so the issue is only on arch (i think)
