### ISSUE TITLE
White screen with custom wineroot (pls close)

### ISSUE THREAD

**Issue by KonoKore** [vinegarhq/vinegar#360]
#### Describe the bug
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported
- [x] I have read the [minimum requirements](https://vinegarhq.org/Installation/index.html#requirements).

#### To Reproduce
1. set wineroot
2. flashbang

### Logs
[Player-2024-02-13T20:30:26-06:00.log](https://github.com/vinegarhq/vinegar/files/14274625/Player-2024-02-13T20.30.26-06.00.log)

### System information
Linux Mint 21.3
Kernel 5.15.0-91-generic
i5-10300H
RTX 3050 Mobile
Cinnamon + Mutter

* Installation method:
* Vinegar: v1.7.2 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 5.15.0-91-generic
* Wine (Player): wine-8.0-3001-g39021e609a2 (Staging)
* Wine (Studio): v8.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card0
  * Card 1: nvidia 0000:01:00.0 /sys/class/drm/card1

**Comment by KonoKore** [comment]
![Screenshot from 2024-02-13 21-45-50](https://github.com/vinegarhq/vinegar/assets/128200152/09ff4536-b34d-4dfe-a6ab-d41cbfdcafe7)
no flameshot moment

**Comment by apprehensions** [comment]
Read the documentation.

**Comment by apprehensions** [comment]
Wine GE is not required on flatpak.

**Comment by KonoKore** [comment]
> Wine GE is not required on flatpak.

Wine GE has worked on every build except for this one

**Comment by KonoKore** [comment]
turns out dxvk broke
