### ISSUE TITLE
White screen and loading popup not going away

### ISSUE THREAD

**Issue by A-childs-encyclopedia** [vinegarhq/vinegar#363]
#### Describe the bug
- [*] I have searched open and closed issues to make sure that the bug has not yet been reported
- [*] I have read the [minimum requirements](https://vinegarhq.org/Installation/index.html#requirements).

Whenever I open the roblox player it just gives me a white screen and the launching player popup doesn't go away.

#### To Reproduce
open roblox player

### Logs
2024/02/17 13:21:33 INFO Logging to file path=/home/abugenius/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/Player-2024-02-17T13:21:33+05:30.log
2024/02/17 13:21:33 INFO Fetching Binary Deployment name=WindowsPlayer channel=""
libEGL warning: egl: failed to create dri2 screen
libEGL warning: failed to get driver name for fd -1

libEGL warning: MESA-LOADER: failed to retrieve device information

libEGL warning: failed to get driver name for fd -1

2024/02/17 13:21:34 INFO Binary is up to date! name=WindowsPlayer guid=version-85c66b72a4fe4a74
2024/02/17 13:21:34 INFO Enabling WINE DXVK DLL overrides
2024/02/17 13:21:34 INFO Connecting to Discord RPC
2024/02/17 13:21:34 ERROR Could not connect to Discord RPC error="drpc: discord is not running"
2024/02/17 13:21:34 INFO Running Binary name=WindowsPlayer cmd="/app/bin/wine64 /home/abugenius/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-85c66b72a4fe4a74/RobloxPlayerBeta.exe"
esync: up and running.
002c:fixme:winediag:loader_init wine-staging 9.2 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: Haswell Vulkan support is incomplete
011c:fixme:ntdll:NtRaiseHardError c0000005 stub
2024/02/17 13:21:40 ERROR Failed to find Roblox log file error="roblox log file not found after 6s"
011c:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0144:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000000CA6FF50
011c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
011c:fixme:keyboard:LoadKeyboardLayoutW name L"00000409", flags 2, semi-stub!
MESA-INTEL: warning: Haswell Vulkan support is incomplete
warn:  Skipping Vulkan 1.2 adapter: NVIDIA GeForce GT 730M
warn:  DXVK: No adapters found. Please check your device filter settings and Vulkan setup. A Vulkan 1.3 capable driver is required.
warn:  DXGI: Found monitors not associated with any adapter, using fallback
Error [GENERAL |  | OpenXR-Loader] : RuntimeManifestFile::FindManifestFiles - failed to find active runtime file in registry
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - unknown error
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - failed to load a runtime
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed to find default runtime with RuntimeInterface::LoadRuntime()
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed querying extension properties
warn:  D3D11CreateDevice: Unsupported driver type
warn:  DXGI: Found monitors not associated with any adapter, using fallback
err:   D3D11CreateDevice: No default adapter available
warn:  DXGI: Found monitors not associated with any adapter, using fallback
Error [GENERAL |  | OpenXR-Loader] : RuntimeManifestFile::FindManifestFiles - failed to find active runtime file in registry
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - unknown error
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - failed to load a runtime
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed to find default runtime with RuntimeInterface::LoadRuntime()
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed querying extension properties
warn:  D3D11CreateDevice: Unsupported driver type
warn:  DXGI: Found monitors not associated with any adapter, using fallback
err:   D3D11CreateDevice: No default adapter available

### System information

* Vinegar: v1.7.3 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.10-76060610-generic
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card0
  * Card 1: nvidia 0000:01:00.0 /sys/class/drm/card1

**Comment by apprehensions** [comment]
The error is in the logs.

**Comment by A-childs-encyclopedia** [comment]
should i install ntlm_auth?

**Comment by apprehensions** [comment]
# ~~Are you blind?~~
```
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: Haswell Vulkan support is incomplete
```
```
libEGL warning: egl: failed to create dri2 screen
libEGL warning: failed to get driver name for fd -1
```
```
warn: D3D11CreateDevice: Unsupported driver type
warn: DXGI: Found monitors not associated with any adapter, using fallback
err: D3D11CreateDevice: No default adapter available
```

Please change your renderer to OpenGL.

**Comment by A-childs-encyclopedia** [comment]
oh thanks

**Comment by A-childs-encyclopedia** [comment]
i added renderer = OpenGL and dxvk = false under [player] but now im getting a new error

**Comment by apprehensions** [comment]
What is the error?

**Comment by A-childs-encyclopedia** [comment]
2024/02/17 15:22:56 INFO Logging to file path=/home/abugenius/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/Player-2024-02-17T15:22:56+05:30.log
2024/02/17 15:22:56 INFO Fetching Binary Deployment name=WindowsPlayer channel=""
libEGL warning: egl: failed to create dri2 screen
libEGL warning: failed to get driver name for fd -1

libEGL warning: MESA-LOADER: failed to retrieve device information

libEGL warning: failed to get driver name for fd -1

2024/02/17 15:22:57 INFO Binary is up to date! name=WindowsPlayer guid=version-85c66b72a4fe4a74
2024/02/17 15:22:57 INFO Connecting to Discord RPC
2024/02/17 15:22:57 ERROR Could not connect to Discord RPC error="drpc: discord is not running"
2024/02/17 15:22:57 INFO Running Binary name=WindowsPlayer cmd="/app/bin/wine64 /home/abugenius/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-85c66b72a4fe4a74/RobloxPlayerBeta.exe"
esync: up and running.
002c:fixme:winediag:loader_init wine-staging 9.2 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: Haswell Vulkan support is incomplete
011c:fixme:ntdll:NtRaiseHardError c0000005 stub
011c:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0144:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000000CA6FF50
011c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
011c:fixme:keyboard:LoadKeyboardLayoutW name L"00000409", flags 2, semi-stub!
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  156 (NV-GLX)
  Minor opcode of failed request:  6 ()
  Value in failed request:  0x0
  Serial number of failed request:  244
  Current serial number in output stream:  244
2024/02/17 15:23:03 INFO Goodbye

**Comment by A-childs-encyclopedia** [comment]
btw vinegar was working without any errors on the previous version I was using (1.6.0)

**Comment by apprehensions** [comment]
I'm not exactly sure why this error occurs. It seems to be related to your graphics card.

**Comment by apprehensions** [comment]
You can try the `gpu` configuration variable to change between discrete and integrated.

**Comment by A-childs-encyclopedia** [comment]
thanks. setting it to integrated worked

**Comment by A-childs-encyclopedia** [comment]
![image](https://github.com/vinegarhq/vinegar/assets/84061672/1b7c81c9-c873-4339-92c3-0469f8a7d67c)
