### ISSUE TITLE
Ummmmmmm?

### ISSUE THREAD

**Issue by brotherman123** [vinegarhq/vinegar#364]
1.7.3 just broke studio and player (I use flatpak)

logs:

studio log:
file:///home/mohamed/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/Player-2024-01-16T18:23:34-05:00.log

player data dump couldn't open

**Comment by apprehensions** [comment]
Follow the Issue template.
Run:
```
flatpak run org.vinegarhq.Vinegar delete
```

**Comment by apprehensions** [comment]
Set your renderer to Vulkan.

**Comment by brotherman123** [comment]
card doesnt support vulcan

**Comment by apprehensions** [comment]
then use opengl.

**Comment by brotherman123** [comment]
I'll just use grapejuice till next stable update comes out

**Comment by EDLLT** [comment]
> I'll just use grapejuice till next stable update comes out

No grape juice
cm'ere over discord in the [#helpdesk-freeform](https://discord.com/channels/1069506340973707304/1162962714713399397) channel and I could try to help

U need to join the discord server if you haven't already
[https://discord.gg/vinegarhq](https://discord.gg/vinegarhq)

**Comment by brotherman123** [comment]
ok
