### ISSUE TITLE
cant run

### ISSUE THREAD

**Issue by subnerf** [vinegarhq/vinegar#365]
2024/02/17 12:15:46 INFO Fetching Binary Deployment name=WindowsPlayer channel=""
2024/02/17 12:15:46 INFO Binary is up to date! name=WindowsPlayer guid=version-85c66b72a4fe4a74
2024/02/17 12:15:46 INFO Enabling WINE DXVK DLL overrides
2024/02/17 12:15:46 INFO Connecting to Discord RPC
2024/02/17 12:15:46 ERROR Could not connect to Discord RPC error="drpc: discord is not running"
2024/02/17 12:15:46 INFO Running Binary name=WindowsPlayer cmd="/app/bin/wine64 /home/ll/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-85c66b72a4fe4a74/RobloxPlayerBeta.exe -app"
0128:err:esync:esync_init Failed to open esync shared memory file; make sure no stale wineserver instances are running without WINEESYNC.

**Comment by apprehensions** [comment]
Read the issue template. Restart your machine.
