### ISSUE TITLE
[Help/Xwayland] Making programs interact with Roblox under a rootful Xwayland window

### ISSUE THREAD

**Issue by Atemo-C** [vinegarhq/vinegar#366]
## Introduction
Greetings. This not a bug report as much as it is a call for help.
I do not know if this is the best place to post this, so please redirect me elsewhere or close this issue if you find this irrelevant in any significant way.

## Relevant issue
[This open issue](https://github.com/vinegarhq/vinegar/issues/263) that "Investigates the integration of Xwayland rootful mode for improved Wayland functionality" is relevant to what I am trying to achieve.

---

## Context and how I run Roblox
My computer has been running under Wayland with the [Hyprland](https://github.com/hyprwm/Hyprland) window manager for a few months now, and I have an NVIDIA GPU *(GTX 1660 Super)*. Both combined really do not play well with Roblox, as one would naturally expect. However, thanks to the above-mentioned issue, I have been successfully able to run Roblox using a rootful Xwayland window, without any major issues with the following set of command in my custom program launcher:
```shell
Xwayland -fullscreen -geometry 1920x1080 -decorate -host-grab :12 & sleep 1 && DISPLAY=:12 org.vinegarhq.Vinegar player run
```
• `Xwayland -fullscreen` creates a full-screen, rootful Xwayland window.
• `-geometry 1920x1080` specifies the geometry of said window.
• `-decorate` adds decorations to the rootful Xwayland window.
• `-host-grab` helps with keyboard and mouse input grabbing, properly locking the cursor as well.
• `:12` specifies the "display" that the rootful Xwayland window will identify as.
• `& sleep 1 &&` is really just here to add a small delay to let the rootful Xwayland window open fully before trying to start Roblox.
• `DISPLAY=:12 org.vinegarhq.Vinegar player un` launches the Roblox player under display ":12", which is the rootful Xwayland window that was just created.

### Small issues
The game works fine like this. The cursor locks properly, and things generally work as one would expect them to.
However, there are still limitations if one is not running a window manager inside the rootful Xwayland window, such as:
• Lack of Roblox window resizing *(but it does not matter to me as I only run Roblox in full-screen, and one can resize the Xwayland window itself anyway).*
• Lack of clipboard sharing *(I noticed that when I tried inputting emojis).*
• Sometimes, though admittedly very rarely, the cursor will stop locking. Simply refocusing the rootful Xwayland window or pressing Escape in Roblox makes the cursor properly lock again.
• Other meaningless shenanigans.

#### Other potential limitations
I only play games such as Phantom Forces, and I have no idea how third-person cursor locking/unlocking and general movement and use work, but it works perfectly fine for my use-case.

All of these limitations are not something that prevents me from playing, and I honestly do not care about them. But I have something I want to do with this. Sorry that it took so long into the report just to get to the point, but I thought the above context was necessary.

---

## What I want to achieve
Ah, there we go, then. I have a simple goal: Under this rootful Xwayland, I wish to run programs that can interact with the Roblox window. For this example, we will take a [simple X auto-clicker](https://github.com/robiot/xclicker), as an auto-clicker is a pretty common tool used in Roblox. Note, however, that this applies to basically any other application, and is not specific to this example.

### How I can *kind of* achieve this
I can simply run the auto-clicker like this:
```shell
DISPLAY=:12 xyz.xclicker.xclicker
```
This will launch the auto-clicker inside the rootful Xwayland window that has already been created for Roblox, and it interacts properly with Roblox itself. However, as no window manager is running under that rootful Xwayland window, I cannot move the auto-clicker around, nor any of the basic things one would expect.
The thing is that I am trying as best as I can *not* to have to use another window manager inside mine, even the lightest one.

### How I would achieve this if I was not stubborn
I do not want to use a window manager inside the rootful Xwayland window. ***But***, if I really **have** to, I could run a full window manager inside of it, and have it manage the Roblox window, virtual desktops, and the programs which I want to interact with Roblox. But this is not ideal, and not something I want to do, especially when I know for a fact that what I want to achieve used to work just fine.

---

## What could help properly achieve this
I have seen people that have been able to run a program that thinks it is in the selected "display" *(here, :12)*, but that is still managed by the main window manager. One of these people, believe it or not, was me! But, this was a long while ago, and I forgot how to achieve this result. I tried searching online for a while, but to no avail, as basically no one seems to be seriously discussing this kind of thing.

I have not stumbled around anything that would achieve the result wanted *(running a program that can interact with Roblox when Roblox is running inside a rootful Xwayland window, whilst the program in question is still managed by the user's window manager)*, besides some environment variables, that unfortunately do not seem to change anything for me.

---

## Call for help
I have read a lot of Xwayland documentation as well as many posts online to find a solution to my problem, a solution or a mix of solutions that I had to have found somehow in the past to make this work.

Does anyone know how to achieve this goal? Is it even possible anymore? *(Because maybe this was something that "just worked" before, but that was changed by Xwayland, but no changelog shows this anywhere that I can find, but maybe I am blind, I sure do hope so.)*

I hope that the solution is, once again, simple and in front of my eyes, but I fear it might not be. Thanks in advance!

**Comment by apprehensions** [comment]
Wayland Wine is supported. Please use that, alongside the [mouselock](https://raw.githubusercontent.com/flathub/org.vinegarhq.Vinegar/master/patches/wine/mouselock.patch) patch.

**Comment by Atemo-C** [comment]
This might be a stupid question, but how does one make Vinegar run Wine under Wayland using the Vinegar flatpak? Vinegar (as a Flatpak) does not seem to, by default, have the Wayland windowing system enabled in it, and I am not sure if there is anything else I need to do in order to achieve this. Once I find how to do this, I will happily close this issue as completed.

**Comment by apprehensions** [comment]
If you are in the VinegarHQ discord, there has been an announcement made a few days ago on how to do that:
> `flatpak run org.vinegarhq.Vinegar player exec reg add HKCU\\Software\\Wine\\Drivers /v Graphics /d x11,wayland /f`
and then set the renderer to "Vulkan".

**Comment by apprehensions** [comment]
Thank you for the incredible writing by the way, very discriptive ~~i didn't read any of it, but the length is astonishing~~

**Comment by Atemo-C** [comment]
Haha, yeah, sorry, I tend to be overly verbose in my writing. I will try to shorten things next time, if there is one!

And thank you for your quick answer. It would be nice to have this in the official documentation sometimes soon, or perhaps have it implemented as an option.
> flatpak run org.vinegarhq.Vinegar player exec reg add HKCU\\Software\\Wine\\Drivers /v Graphics /d x11,wayland /f
I should probably join the server, then!

Thanks for the help! Closing as completed.

**Comment by Atemo-C** [comment]
## Small update
*Is this necro-posting? Perhaps, but it is very likely the last comment I make here.*

---

I no longer need to use Xwayland thanks to Wine under Wayland working just fine for me (apart from Wine deciding it would be a good idea to force its own title bar and window borders to appear at all times, but this should be a separate issue, and probably not one on this repository), but I kept experimenting nonetheless to find out what in the world I did a few months back to get the behavior I described earlier to work.

Well, I have found out that some programs work the way I want out of the box, whilst others simply do not. It also seems as though most of the ones that do not work the way I want are Flatpaks, but it also happens with some native programs.

---

## Auto-clicker: Flatpak and Native
This is the best example of this strange behavior. Still using [the same auto-clicker program](https://github.com/robiot/xclicker) as an example, but installed both as a Flatpak and running as an AppImage. I will demonstrate here what happens.

### How to
It is, in fact, as easy as running the program in question in the same rootful Xwayland "display". So, for example, if Roblox is running under a rootful Xwayland window on "display" `:12`, then this is the command one would execute to have a program interacting with it:
```shell
DISPLAY=:12 command-here
```
Now, let us see how this actually works.

### Flatpak
Running this command:
```shell
DISPLAY=:12 xyz.xclicker.xclicker
```
This results in the window appearing on top of the Roblox window *(or behind, if Roblox is launched after it)*, and is managed by whichever window manager is running inside the rootful Xwayland window *(in this case, none)*. This is not the desired behavior, even if it kind-of-works-but-not-really.

### AppImage
Running this command (as I am on NixOS):
```shell
DISPLAY=:12 appimage-run $HOME/Programs/AppImages/xclicker*
```
This results in the window appearing on the active desktop of my actual window manager, and is controlled by it. I can move it around, interact with it, hide it, close it, and all of that fun stuff. Even whilst outside the rootful Xwayland window itself, it still interacts with it, and thus, works perfectly this way.

---

### More things for me to learn
I guess that I will have to search the depths of the web to see what in the world is happening that makes the Flatpak not work as expected whilst the AppImage runs the expected way; And why some native programs run inside or outside the rootful Xwayland window.
