### ISSUE TITLE
Authentication launch doesnt work (studio)

### ISSUE THREAD

**Issue by brotherman123** [vinegarhq/vinegar#373]
* Vinegar: v1.7.3 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.11-200.fc39.x86_64
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card0
  * Card 1: nvidia 0000:01:00.0 /sys/class/drm/card1

When authenticating puts loading window on my screen. Then the roblox studio indicator. Then it never launches. trying to launch it after doesn't work and says that i havent authenticated. Authentication is working as usual just never launching.

**Comment by apprehensions** [comment]
delete the wineprefix

**Comment by brotherman123** [comment]
I did. It didn't work

**Comment by apprehensions** [comment]
ok dk then

**Comment by brotherman123** [comment]
I'll just use grapejuice in the meantime. Vinegar runs smoother in my opinion

**Comment by cubusXD** [comment]
Try deleting the directory data in /home/USER/.var/app/org.vinegarhq.Vinegar/, that worked for me

**Comment by lunarlettuce** [comment]
Use `flatpak run org.vinegarhq.Vinegar delete` instead

**Comment by brotherman123** [comment]
then again it did the same thing i just said didn't work.

**Comment by naviderglol** [comment]
try running `rm .var/app/org.vinegarhq.Vinegar/data/vinegar/state.json `

**Comment by brotherman123** [comment]
YES IT WORKED. For roblox. Studio still not authenticated sadly

**Comment by brotherman123** [comment]
umm i ran `flatpak run org.vinegarhq.Vinegar delete` and now it aint working again when i tried doing it again it says
`bash: rm.var/app/org.vinegarhq.Vinegar/data/vinegar/state.json: No such file or directory`

**Comment by brotherman123** [comment]
lol just fixed it!

**Comment by brotherman123** [comment]
@
