### ISSUE TITLE
After the update, I can't launch roblox player or studio. This is probably related to 32 bit support. 

### ISSUE THREAD

**Issue by Abdulsarhan** [vinegarhq/vinegar#375]
#### Describe the bug
- [ yes] I have searched open and closed issues to make sure that the bug has not yet been reported
- [ yes] I have read the [minimum requirements](https://vinegarhq.org/Installation/index.html#requirements).

I can't launch roblox player or studio. I suspect that this is due to a recent update relating to 32 bit support. 

#### To Reproduce
Update your system. 
Run vinegar player. 

### Logs

~/.cache/vinegar/logs 

2024/02/07 15:24:54 INFO Initializing wineprefix dir=/home/abdul/.local/share/vinegar/prefixes/player
002c:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
004c:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0054:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0054:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0054:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0054:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0054:err:ole:start_rpcss Failed to open RpcSs service
004c:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
004c:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
004c:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0090:fixme:file:NtLockFile I/O completion on lock not implemented yet
0090:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0098:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
0098:err:winediag:process_attach failed to load libgnutls, no support for pfx import/export
0090:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
0090:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
00f0:fixme:msg:pack_message msg 14 (WM_ERASEBKGND) not supported yet
00f0:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
00f0:err:winediag:process_attach failed to load libgnutls, no support for pfx import/export
wine: configuration in L"/home/abdul/.local/share/vinegar/prefixes/player" has been updated.
004c:err:ole:start_rpcss Failed to start RpcSs service
0164:err:rpc:I_RpcReceive we got fault packet with status 0x1c010003
0158:fixme:service:scmdatabase_autostart_services Auto-start service L"MountMgr" failed to start: 1053
0158:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1115
0158:fixme:service:scmdatabase_autostart_services Auto-start service L"winebus" failed to start: 1115
0158:fixme:service:scmdatabase_autostart_services Auto-start service L"PlugPlay" failed to start: 1115
0158:fixme:service:scmdatabase_autostart_services Auto-start service L"Eventlog" failed to start: 1115
0158:fixme:service:scmdatabase_autostart_services Auto-start service L"nsiproxy" failed to start: 1115
0158:fixme:service:scmdatabase_autostart_services Auto-start service L"NDIS" failed to start: 1115
2024/02/07 15:25:05 INFO Fetching Binary Deployment name=WindowsPlayer channel=LIVE
2024/02/07 15:25:06 INFO Installing Binary name=WindowsPlayer old_guid="" new_guid=version-17f2f3d7fcfc48f5
2024/02/07 15:25:06 INFO Finding an accessible deploy mirror
2024/02/07 15:25:06 INFO Found deploy mirror mirror=https://setup.rbxcdn.com
2024/02/07 15:25:06 INFO Fetching Package Manifest url=https://setup.rbxcdn.com/version-17f2f3d7fcfc48f5-rbxPkgManifest.txt
2024/02/07 15:25:06 INFO Downloading Packages guid=version-17f2f3d7fcfc48f5 count=19
2024/02/07 15:25:06 INFO Verifying Package name=WebView2.zip path=/home/abdul/.cache/vinegar/downloads/e08ecba38c337ebf57bbae5a2915e24a
2024/02/07 15:25:06 INFO Verifying Package name=content-models.zip path=/home/abdul/.cache/vinegar/downloads/6db8ca907c81a0973fbe69a3c6ebbe04
2024/02/07 15:25:06 INFO Verifying Package name=content-configs.zip path=/home/abdul/.cache/vinegar/downloads/06b99f24b3c50193a7127cb843a64d27
2024/02/07 15:25:06 INFO Verifying Package name=content-sounds.zip path=/home/abdul/.cache/vinegar/downloads/cd77e0e77d698260809f8ae8b3993740
2024/02/07 15:25:06 INFO Verifying Package name=extracontent-textures.zip path=/home/abdul/.cache/vinegar/downloads/5021d03be744373cc1a181cd8b31e200
2024/02/07 15:25:06 INFO Verifying Package name=content-terrain.zip path=/home/abdul/.cache/vinegar/downloads/834036d8093b692d6f51fc92001656f9
2024/02/07 15:25:06 INFO Verifying Package name=shaders.zip path=/home/abdul/.cache/vinegar/downloads/7f50e4d44b49ffdad08b75b571c7cf4e
2024/02/07 15:25:06 INFO Verifying Package name=RobloxApp.zip path=/home/abdul/.cache/vinegar/downloads/93e0858176d64801f5f34764771bb375
2024/02/07 15:25:06 INFO Package is already downloaded name=content-configs.zip file=/home/abdul/.cache/vinegar/downloads/06b99f24b3c50193a7127cb843a64d27
2024/02/07 15:25:06 INFO Verifying Package name=extracontent-translations.zip path=/home/abdul/.cache/vinegar/downloads/c4a720a0b368fceda8f41e3bd7ba7ca8
2024/02/07 15:25:06 INFO Verifying Package name=content-platform-fonts.zip path=/home/abdul/.cache/vinegar/downloads/8f379ec2b22ff106b837d79f7fdbf0d8
2024/02/07 15:25:06 INFO Package is already downloaded name=WebView2.zip file=/home/abdul/.cache/vinegar/downloads/e08ecba38c337ebf57bbae5a2915e24a
2024/02/07 15:25:06 INFO Verifying Package name=content-sky.zip path=/home/abdul/.cache/vinegar/downloads/1d0390337d1a4a58e5514be1a9481ad6
2024/02/07 15:25:06 INFO Verifying Package name=content-avatar.zip path=/home/abdul/.cache/vinegar/downloads/a1500b285dbf5bedd6457f4ae588e12c
2024/02/07 15:25:06 INFO Package is already downloaded name=content-sounds.zip file=/home/abdul/.cache/vinegar/downloads/cd77e0e77d698260809f8ae8b3993740
2024/02/07 15:25:06 INFO Package is already downloaded name=extracontent-translations.zip file=/home/abdul/.cache/vinegar/downloads/c4a720a0b368fceda8f41e3bd7ba7ca8
2024/02/07 15:25:06 INFO Verifying Package name=extracontent-luapackages.zip path=/home/abdul/.cache/vinegar/downloads/f7e4e2faf3ec808a49f8dae0a13443e5
2024/02/07 15:25:06 INFO Package is already downloaded name=content-models.zip file=/home/abdul/.cache/vinegar/downloads/6db8ca907c81a0973fbe69a3c6ebbe04
2024/02/07 15:25:06 INFO Verifying Package name=content-fonts.zip path=/home/abdul/.cache/vinegar/downloads/68fbee40d488d787111f36ca649aff6e
2024/02/07 15:25:06 INFO Verifying Package name=content-textures2.zip path=/home/abdul/.cache/vinegar/downloads/4dd5b95ceeecd52da615f665f77e6989
2024/02/07 15:25:06 INFO Package is already downloaded name=content-avatar.zip file=/home/abdul/.cache/vinegar/downloads/a1500b285dbf5bedd6457f4ae588e12c
2024/02/07 15:25:06 INFO Verifying Package name=extracontent-places.zip path=/home/abdul/.cache/vinegar/downloads/762ad24e70de41575e4c399723423556
2024/02/07 15:25:06 INFO Package is already downloaded name=extracontent-places.zip file=/home/abdul/.cache/vinegar/downloads/762ad24e70de41575e4c399723423556
2024/02/07 15:25:06 INFO Verifying Package name=extracontent-models.zip path=/home/abdul/.cache/vinegar/downloads/a4bdebb4d373b60afa47136544028ed7
2024/02/07 15:25:06 INFO Verifying Package name=ssl.zip path=/home/abdul/.cache/vinegar/downloads/cb04a98a01fed3e8ccd2fcc06c3bb957
2024/02/07 15:25:06 INFO Package is already downloaded name=ssl.zip file=/home/abdul/.cache/vinegar/downloads/cb04a98a01fed3e8ccd2fcc06c3bb957
2024/02/07 15:25:06 INFO Verifying Package name=content-textures3.zip path=/home/abdul/.cache/vinegar/downloads/7ad5a15cb63aca299d9dd35cd6c9a50f
2024/02/07 15:25:06 INFO Package is already downloaded name=content-sky.zip file=/home/abdul/.cache/vinegar/downloads/1d0390337d1a4a58e5514be1a9481ad6
2024/02/07 15:25:06 INFO Package is already downloaded name=shaders.zip file=/home/abdul/.cache/vinegar/downloads/7f50e4d44b49ffdad08b75b571c7cf4e
2024/02/07 15:25:06 INFO Package is already downloaded name=content-fonts.zip file=/home/abdul/.cache/vinegar/downloads/68fbee40d488d787111f36ca649aff6e
2024/02/07 15:25:06 INFO Package is already downloaded name=extracontent-luapackages.zip file=/home/abdul/.cache/vinegar/downloads/f7e4e2faf3ec808a49f8dae0a13443e5
2024/02/07 15:25:06 INFO Package is already downloaded name=content-textures2.zip file=/home/abdul/.cache/vinegar/downloads/4dd5b95ceeecd52da615f665f77e6989
2024/02/07 15:25:06 INFO Package is already downloaded name=extracontent-models.zip file=/home/abdul/.cache/vinegar/downloads/a4bdebb4d373b60afa47136544028ed7
2024/02/07 15:25:06 INFO Package is already downloaded name=extracontent-textures.zip file=/home/abdul/.cache/vinegar/downloads/5021d03be744373cc1a181cd8b31e200
2024/02/07 15:25:06 INFO Package is already downloaded name=content-platform-fonts.zip file=/home/abdul/.cache/vinegar/downloads/8f379ec2b22ff106b837d79f7fdbf0d8
2024/02/07 15:25:06 INFO Package is already downloaded name=content-terrain.zip file=/home/abdul/.cache/vinegar/downloads/834036d8093b692d6f51fc92001656f9
2024/02/07 15:25:06 INFO Package is already downloaded name=content-textures3.zip file=/home/abdul/.cache/vinegar/downloads/7ad5a15cb63aca299d9dd35cd6c9a50f
2024/02/07 15:25:06 INFO Package is already downloaded name=RobloxApp.zip file=/home/abdul/.cache/vinegar/downloads/93e0858176d64801f5f34764771bb375
2024/02/07 15:25:06 INFO Extracting Packages guid=version-17f2f3d7fcfc48f5 count=19
2024/02/07 15:25:06 INFO Extracted package name=WebView2.zip path=/home/abdul/.cache/vinegar/downloads/e08ecba38c337ebf57bbae5a2915e24a dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5
2024/02/07 15:25:06 INFO Extracted package name=content-configs.zip path=/home/abdul/.cache/vinegar/downloads/06b99f24b3c50193a7127cb843a64d27 dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/content/configs
2024/02/07 15:25:06 INFO Extracted package name=ssl.zip path=/home/abdul/.cache/vinegar/downloads/cb04a98a01fed3e8ccd2fcc06c3bb957 dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/ssl
2024/02/07 15:25:06 INFO Extracted package name=content-sounds.zip path=/home/abdul/.cache/vinegar/downloads/cd77e0e77d698260809f8ae8b3993740 dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/content/sounds
2024/02/07 15:25:06 INFO Extracted package name=extracontent-translations.zip path=/home/abdul/.cache/vinegar/downloads/c4a720a0b368fceda8f41e3bd7ba7ca8 dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/ExtraContent/translations
2024/02/07 15:25:06 INFO Extracted package name=content-models.zip path=/home/abdul/.cache/vinegar/downloads/6db8ca907c81a0973fbe69a3c6ebbe04 dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/content/models
2024/02/07 15:25:06 INFO Extracted package name=content-avatar.zip path=/home/abdul/.cache/vinegar/downloads/a1500b285dbf5bedd6457f4ae588e12c dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/content/avatar
2024/02/07 15:25:06 INFO Extracted package name=extracontent-models.zip path=/home/abdul/.cache/vinegar/downloads/a4bdebb4d373b60afa47136544028ed7 dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/ExtraContent/models
2024/02/07 15:25:06 INFO Extracted package name=extracontent-places.zip path=/home/abdul/.cache/vinegar/downloads/762ad24e70de41575e4c399723423556 dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/ExtraContent/places
2024/02/07 15:25:06 INFO Extracted package name=content-sky.zip path=/home/abdul/.cache/vinegar/downloads/1d0390337d1a4a58e5514be1a9481ad6 dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/content/sky
2024/02/07 15:25:06 INFO Extracted package name=extracontent-luapackages.zip path=/home/abdul/.cache/vinegar/downloads/f7e4e2faf3ec808a49f8dae0a13443e5 dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/ExtraContent/LuaPackages
2024/02/07 15:25:06 INFO Extracted package name=shaders.zip path=/home/abdul/.cache/vinegar/downloads/7f50e4d44b49ffdad08b75b571c7cf4e dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/shaders
2024/02/07 15:25:06 INFO Extracted package name=extracontent-textures.zip path=/home/abdul/.cache/vinegar/downloads/5021d03be744373cc1a181cd8b31e200 dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/ExtraContent/textures
2024/02/07 15:25:06 INFO Extracted package name=content-fonts.zip path=/home/abdul/.cache/vinegar/downloads/68fbee40d488d787111f36ca649aff6e dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/content/fonts
2024/02/07 15:25:06 INFO Extracted package name=content-textures2.zip path=/home/abdul/.cache/vinegar/downloads/4dd5b95ceeecd52da615f665f77e6989 dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/content/textures
2024/02/07 15:25:06 INFO Extracted package name=content-platform-fonts.zip path=/home/abdul/.cache/vinegar/downloads/8f379ec2b22ff106b837d79f7fdbf0d8 dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/PlatformContent/pc/fonts
2024/02/07 15:25:06 INFO Extracted package name=content-terrain.zip path=/home/abdul/.cache/vinegar/downloads/834036d8093b692d6f51fc92001656f9 dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/PlatformContent/pc/terrain
2024/02/07 15:25:06 INFO Extracted package name=content-textures3.zip path=/home/abdul/.cache/vinegar/downloads/7ad5a15cb63aca299d9dd35cd6c9a50f dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/PlatformContent/pc/textures
2024/02/07 15:25:06 INFO Extracted package name=RobloxApp.zip path=/home/abdul/.cache/vinegar/downloads/93e0858176d64801f5f34764771bb375 dest=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5
2024/02/07 15:25:06 INFO Writing AppSettings.xml path=/home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/AppSettings.xml
2024/02/07 15:25:06 INFO Enabling WINE DXVK DLL overrides
2024/02/07 15:25:06 INFO Downloading DXVK tarball url=https://github.com/doitsujin/dxvk/releases/download/v2.3/dxvk-2.3.tar.gz path=/tmp/dxvktarball.3778753923.tar.gz
2024/02/07 15:25:07 INFO Extracting DXVK file=/tmp/dxvktarball.3778753923.tar.gz pfx=/home/abdul/.local/share/vinegar/prefixes/player
2024/02/07 15:25:07 INFO Extracting DXVK DLL path=/home/abdul/.local/share/vinegar/prefixes/player/drive_c/windows/syswow64/d3d9.dll
2024/02/07 15:25:07 INFO Extracting DXVK DLL path=/home/abdul/.local/share/vinegar/prefixes/player/drive_c/windows/syswow64/d3d11.dll
2024/02/07 15:25:07 INFO Extracting DXVK DLL path=/home/abdul/.local/share/vinegar/prefixes/player/drive_c/windows/syswow64/d3d10core.dll
2024/02/07 15:25:07 INFO Extracting DXVK DLL path=/home/abdul/.local/share/vinegar/prefixes/player/drive_c/windows/syswow64/dxgi.dll
2024/02/07 15:25:07 INFO Extracting DXVK DLL path=/home/abdul/.local/share/vinegar/prefixes/player/drive_c/windows/system32/d3d9.dll
2024/02/07 15:25:07 INFO Extracting DXVK DLL path=/home/abdul/.local/share/vinegar/prefixes/player/drive_c/windows/system32/d3d11.dll
2024/02/07 15:25:07 INFO Extracting DXVK DLL path=/home/abdul/.local/share/vinegar/prefixes/player/drive_c/windows/system32/d3d10core.dll
2024/02/07 15:25:07 INFO Extracting DXVK DLL path=/home/abdul/.local/share/vinegar/prefixes/player/drive_c/windows/system32/dxgi.dll
2024/02/07 15:25:07 INFO Deleting DXVK tarball path=/tmp/dxvktarball.3778753923.tar.gz
2024/02/07 15:25:07 INFO Connecting to Discord RPC
2024/02/07 15:25:07 INFO Running Binary name=WindowsPlayer cmd="/usr/bin/wine64 /home/abdul/.local/share/vinegar/versions/version-17f2f3d7fcfc48f5/RobloxPlayerBeta.exe"
0024:fixme:ntdll:NtRaiseHardError c0000005 stub
0024:fixme:event:wait_for_withdrawn_state window 0x10054/4c00001 wait timed out
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
2024/02/07 15:25:13 ERROR Failed to find Roblox log file error="roblox log file not found after 6s"
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module
0024:fixme:dbghelp:elf_search_auxv can't find symbol in module

Vinegar config: 

[player]
wineroot = "/home/abdul/.wine"
launcher = "gamemoderun"
dxvk = false
renderer = "Vulkan"

### System information

Arch linux 6.7.5 64 bit. (latest update as of the time I make this issue)

* Installation method:
flatpak run org.vinegarhq.Vinegar sysinfo output:
F: Not sharing "/usr/bin/wine64" with sandbox: Path "/usr" is reserved by Flatpak
2024/02/19 16:46:50 load config /home/abdul/.var/app/org.vinegarhq.Vinegar/config/vinegar/config.toml: player: invalid: bad wineroot: exec: "/home/abdul/.wine/bin/wine64": stat /home/abdul/.wine/bin/wine64: no such file or directory

**Comment by EDLLT** [comment]
The flatpak installation of vinegar is sandboxed so you'd need to take certain measures to be able to specify your own custom wineroot. This is already mentioned in the docs

For now, just try removing the wineroot line
```
[player]
launcher = "gamemoderun"
dxvk = false
renderer = "Vulkan"
```

**Comment by Abdulsarhan** [comment]
I removed the wineroot line and here is the output of running vinegar player:

F: Not sharing "/usr/bin/wine64" with sandbox: Path "/usr" is reserved by Flatpak
usage: vinegar [-config filepath] player|studio exec|run [args...]
usage: vinegar [-config filepath] player|studio kill|winetricks
       vinegar [-config filepath] sysinfo
       vinegar delete|edit|version

**Comment by EDLLT** [comment]
> I removed the wineroot line and here is the output of running vinegar player:
> 
> F: Not sharing "/usr/bin/wine64" with sandbox: Path "/usr" is reserved by Flatpak usage: vinegar [-config filepath] player|studio exec|run [args...] usage: vinegar [-config filepath] player|studio kill|winetricks vinegar [-config filepath] sysinfo vinegar delete|edit|version

Show me the vinegar sysinfo

```flatpak run org.vinegarhq.Vinegar sysinfo```

**Comment by Abdulsarhan** [comment]
F: Not sharing "/usr/bin/wine64" with sandbox: Path "/usr" is reserved by Flatpak
* Vinegar: v1.7.3
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Ryzen 5 5600X 6-Core Processor
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.7.5-arch1-1
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: amdgpu 0000:2d:00.0 /sys/class/drm/card1

**Comment by lunarlettuce** [comment]
Well yeah, /usr is a folder that Flatpak uses as part of its chroot. Move your custom wine outside of /usr/bin.

**Comment by Abdulsarhan** [comment]
> Well yeah, /usr is a folder that Flatpak uses as part of its chroot. Move your custom wine outside of /usr/bin, such as ~/Documents.

So, I should move /usr/bin/wine64 into my home directory or somewhere else and then add wineroot = "/path/to/wine64" into my config?

**Comment by Abdulsarhan** [comment]
Well, anyway, I did that and this is the output of running vinegar player:

F: Not replacing "/usr/bin/wine64" with tmpfs: Path "/usr" is reserved by Flatpak
usage: vinegar [-config filepath] player|studio exec|run [args...]
usage: vinegar [-config filepath] player|studio kill|winetricks
       vinegar [-config filepath] sysinfo
       vinegar delete|edit|version

**Comment by brotherman123** [comment]
I had the same issue now way!!!! heres the fix. first make sure that your using flatpak version. To download on flatpak run
`flatpak install vinegar`
then when its set up run:
`rm.var/app/org.vinegarhq.Vinegar/data/vinegar/state.json`
fixed hope i helped!

**Comment by Root-Time** [comment]
> I had the same issue now way!!!! heres the fix. first make sure that your using flatpak version. To download on flatpak run `flatpak install vinegar` then when its set up run: `rm.var/app/org.vinegarhq.Vinegar/data/vinegar/state.json` fixed hope i helped!

I cannot run this: `rm.var/app/org.vinegarhq.Vinegar/data/vinegar/state.json`

**Comment by brotherman123** [comment]
Oh then just go to delete it mannualy here 
`/home/USER/.var/app/org.vinegarhq.Vinegar/data/vinegar/`
