### ISSUE TITLE
Roblox crashes after starting it up

### ISSUE THREAD

**Issue by Cyanide-1** [vinegarhq/vinegar#376]
#### Describe the bug
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported
- [x] I have read the [minimum requirements](https://vinegarhq.org/Installation/index.html#requirements).

I used to be able to run roblox on this same machine and setup not too long ago, i am using the officially-maintained flatpak from flathub, the intel IGPU on my machine is capable of the required OpenGL version and runs roblox fine on OpenGL (albeit slowly), not sure why it is suddenly crashing.

#### To Reproduce
Steps to reproduce the behavior.

step 1. download a fresh install of vinegar (all user data removed)
step 2. try booting up roblox client
step 3. roblox crashes and closes the window immediately after popping up

### Logs
Reference log file contents, which are usually located in `~/.cache/vinegar/logs` or `~/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/` for Flatpak, of a run reproducing the bug

2024/02/19 22:55:19 INFO Fetching Binary Deployment name=WindowsPlayer channel=""
2024/02/19 22:55:19 INFO Binary is up to date! name=WindowsPlayer guid=version-85c66b72a4fe4a74
2024/02/19 22:55:19 INFO Enabling WINE DXVK DLL overrides
2024/02/19 22:55:19 INFO Connecting to Discord RPC
2024/02/19 22:55:19 ERROR Could not connect to Discord RPC error="drpc: discord is not running"
2024/02/19 22:55:19 INFO Running Binary name=WindowsPlayer cmd="/app/bin/wine64 /home/hedonist/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-85c66b72a4fe4a74/RobloxPlayerBeta.exe roblox-player:1+launchmode:play+gameinfo:ikgLX28vAKMDfbsspihlhBsUw08-Nv4x0FQDxm2x057IS4SgoVemUssd4NLxWDVYA9dcSb3MWDnea6t-t1DVBOVeX6p_ozOIyB_94ovFdvHJI5rTpdiVAfAJVzjrM_HK--MWSOHOK_qd_iemcWrOZQd7d-PudEPeQwMxmAA1REl7SvCcT1cg3BykFbGVP-1tAy_fDzpRYmlVnJrZvdaDfJ1SbG73DxA-LBnSM8KIfeg+launchtime:1708404919104+placelauncherurl:https%3A%2F%2Fassetgame.roblox.com%2Fgame%2FPlaceLauncher.ashx%3Frequest%3DRequestGameJob%26browserTrackerId%3D216452391262%26placeId%3D863266079%26gameId%3Dd4fa6b77-10e5-48c5-8c57-851f0c818f38%26isPlayTogetherGame%3Dfalse%26joinAttemptId%3D099f755c-91e2-4bd5-8f60-b6205a60174a%26joinAttemptOrigin%3DServerListJoin+browsertrackerid:216452391262+robloxLocale:en_us+gameLocale:en_us+channel:"
002c:fixme:winediag:loader_init wine-staging 9.2 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
0118:fixme:ntdll:NtRaiseHardError c0000005 stub
0118:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0118:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0118:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0140:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000000CA6FF50
0118:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0118:fixme:keyboard:LoadKeyboardLayoutW name L"00000409", flags 2, semi-stub!
Error [GENERAL |  | OpenXR-Loader] : RuntimeManifestFile::FindManifestFiles - failed to find active runtime file in registry
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - unknown error
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - failed to load a runtime
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed to find default runtime with RuntimeInterface::LoadRuntime()
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed querying extension properties
info:  Game: RobloxPlayerBeta.exe
info:  DXVK: v2.3
info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x6ffff9503f40
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_EXT_surface_maintenance1
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
warn:  Skipping Vulkan 1.2 adapter: Intel(R) HD Graphics 2500 (IVB GT1)
warn:  Skipping CPU adapter: llvmpipe (LLVM 17.0.6, 256 bits)
warn:  DXVK: No adapters found. Please check your device filter settings and Vulkan setup. A Vulkan 1.3 capable driver is required.
warn:  DXGI: Found monitors not associated with any adapter, using fallback
Error [GENERAL |  | OpenXR-Loader] : RuntimeManifestFile::FindManifestFiles - failed to find active runtime file in registry
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - unknown error
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - failed to load a runtime
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed to find default runtime with RuntimeInterface::LoadRuntime()
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed querying extension properties
warn:  D3D11CreateDevice: Unsupported driver type
warn:  DXGI: Found monitors not associated with any adapter, using fallback
err:   D3D11CreateDevice: No default adapter available

### System information

CPU: Intel(R) Core(TM) i5-3570 (4) @ 3.80 GHz
GPU: Integrated Graphics

* Installation method:

F: Not sharing "/usr/share/icons" with sandbox: Path "/usr" is reserved by Flatpak
* Vinegar: v1.7.3 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.7.5-zen1-1-zen
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card1

#### Additional context

I am on a properly-configured Arch Linux system with KDE Plasma

**Comment by derspyy** [comment]
i also have 
```
0118:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
```

**Comment by lunarlettuce** [comment]
> i also have
> 
> ```
> 0118:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
> ```

Harmless

**Comment by lunarlettuce** [comment]
> #### Describe the bug
> 
>     * [x]  I have searched open and closed issues to make sure that the bug has not yet been reported
> 
>     * [x]  I have read the [minimum requirements](https://vinegarhq.org/Installation/index.html#requirements).
> 
> 
> A clear and concise description of what the bug is.
> 
> I used to be able to run roblox on this same machine and setup not too long ago, i am using the officially-maintained flatpak from flathub, the intel IGPU on my machine is capable of the required OpenGL version and runs roblox fine on OpenGL (albeit slowly), not sure why it is suddenly crashing.
> #### To Reproduce
> 
> Steps to reproduce the behavior.
> 
> step 1. download a fresh install of vinegar (all user data removed) step 2. try booting up roblox client step 3. roblox crashes and closes the window immediately after popping up
> ### Logs
> 
> Reference log file contents, which are usually located in `~/.cache/vinegar/logs` or `~/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/` for Flatpak, of a run reproducing the bug
> 
> 2024/02/19 22:55:19 INFO Fetching Binary Deployment name=WindowsPlayer channel="" 2024/02/19 22:55:19 INFO Binary is up to date! name=WindowsPlayer guid=version-85c66b72a4fe4a74 2024/02/19 22:55:19 INFO Enabling WINE DXVK DLL overrides 2024/02/19 22:55:19 INFO Connecting to Discord RPC 2024/02/19 22:55:19 ERROR Could not connect to Discord RPC error="drpc: discord is not running" 2024/02/19 22:55:19 INFO Running Binary name=WindowsPlayer cmd="/app/bin/wine64 /home/hedonist/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-85c66b72a4fe4a74/RobloxPlayerBeta.exe roblox-player:1+launchmode:play+gameinfo:ikgLX28vAKMDfbsspihlhBsUw08-Nv4x0FQDxm2x057IS4SgoVemUssd4NLxWDVYA9dcSb3MWDnea6t-t1DVBOVeX6p_ozOIyB_94ovFdvHJI5rTpdiVAfAJVzjrM_HK--MWSOHOK_qd_iemcWrOZQd7d-PudEPeQwMxmAA1REl7SvCcT1cg3BykFbGVP-1tAy_fDzpRYmlVnJrZvdaDfJ1SbG73DxA-LBnSM8KIfeg+launchtime:1708404919104+placelauncherurl:https%3A%2F%2Fassetgame.roblox.com%2Fgame%2FPlaceLauncher.ashx%3Frequest%3DRequestGameJob%26browserTrackerId%3D216452391262%26placeId%3D863266079%26gameId%3Dd4fa6b77-10e5-48c5-8c57-851f0c818f38%26isPlayTogetherGame%3Dfalse%26joinAttemptId%3D099f755c-91e2-4bd5-8f60-b6205a60174a%26joinAttemptOrigin%3DServerListJoin+browsertrackerid:216452391262+robloxLocale:en_us+gameLocale:en_us+channel:" 002c:fixme:winediag:loader_init wine-staging 9.2 is a testing version containing experimental patches. 002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org. 0118:fixme:ntdll:NtRaiseHardError c0000005 stub 0118:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems 0118:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution. 0118:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems 0140:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000000CA6FF50 0118:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION 0118:fixme:keyboard:LoadKeyboardLayoutW name L"00000409", flags 2, semi-stub! Error [GENERAL | | OpenXR-Loader] : RuntimeManifestFile::FindManifestFiles - failed to find active runtime file in registry Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - unknown error Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - failed to load a runtime Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed to find default runtime with RuntimeInterface::LoadRuntime() Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed querying extension properties info: Game: RobloxPlayerBeta.exe info: DXVK: v2.3 info: Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x6ffff9503f40 info: Built-in extension providers: info: Win32 WSI info: OpenVR info: OpenXR info: OpenVR: could not open registry key, status 2 info: OpenVR: Failed to locate module info: Enabled instance extensions: info: VK_EXT_surface_maintenance1 info: VK_KHR_get_surface_capabilities2 info: VK_KHR_surface info: VK_KHR_win32_surface MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete warn: Skipping Vulkan 1.2 adapter: Intel(R) HD Graphics 2500 (IVB GT1) warn: Skipping CPU adapter: llvmpipe (LLVM 17.0.6, 256 bits) warn: DXVK: No adapters found. Please check your device filter settings and Vulkan setup. A Vulkan 1.3 capable driver is required. warn: DXGI: Found monitors not associated with any adapter, using fallback Error [GENERAL | | OpenXR-Loader] : RuntimeManifestFile::FindManifestFiles - failed to find active runtime file in registry Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - unknown error Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - failed to load a runtime Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed to find default runtime with RuntimeInterface::LoadRuntime() Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed querying extension properties warn: D3D11CreateDevice: Unsupported driver type warn: DXGI: Found monitors not associated with any adapter, using fallback err: D3D11CreateDevice: No default adapter available
> ### System information
> 
> CPU: Intel(R) Core(TM) i5-3570 (4) @ 3.80 GHz GPU: Integrated Graphics
> 
>     * Installation method:
> 
> 
> F: Not sharing "/usr/share/icons" with sandbox: Path "/usr" is reserved by Flatpak
> 
>     * Vinegar: v1.7.3
> 
>     * Distro: Freedesktop SDK 23.08 (Flatpak runtime)
> 
>     * Processor: Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
>       
>       * Supports AVX: true
>       * Supports split lock detection: false
> 
>     * Kernel: 6.7.5-zen1-1-zen
> 
>     * Wine (Player): v9.2 (Staging)
> 
>     * Wine (Studio): v9.2 (Staging)
> 
>     * Flatpak: [x]
> 
>     * Cards:
>       
>       * Card 0: i915 0000:00:02.0 /sys/class/drm/card1
> 
> 
> #### Additional context
> 
> Add any other context about the problem here.
> 
> I am on a properly-configured Arch Linux system with KDE Plasma

```warn: DXVK: No adapters found. Please check your device filter settings and Vulkan setup. A Vulkan 1.3 capable driver is required.```

You'll need to use OpenGL, or get a new laptop.

**Comment by Cyanide-1** [comment]
> > #### Describe the bug
> > ```
> > * [x]  I have searched open and closed issues to make sure that the bug has not yet been reported
> > 
> > * [x]  I have read the [minimum requirements](https://vinegarhq.org/Installation/index.html#requirements).
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > A clear and concise description of what the bug is.
> > I used to be able to run roblox on this same machine and setup not too long ago, i am using the officially-maintained flatpak from flathub, the intel IGPU on my machine is capable of the required OpenGL version and runs roblox fine on OpenGL (albeit slowly), not sure why it is suddenly crashing.
> > #### To Reproduce
> > Steps to reproduce the behavior.
> > step 1. download a fresh install of vinegar (all user data removed) step 2. try booting up roblox client step 3. roblox crashes and closes the window immediately after popping up
> > ### Logs
> > Reference log file contents, which are usually located in `~/.cache/vinegar/logs` or `~/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/` for Flatpak, of a run reproducing the bug
> > 2024/02/19 22:55:19 INFO Fetching Binary Deployment name=WindowsPlayer channel="" 2024/02/19 22:55:19 INFO Binary is up to date! name=WindowsPlayer guid=version-85c66b72a4fe4a74 2024/02/19 22:55:19 INFO Enabling WINE DXVK DLL overrides 2024/02/19 22:55:19 INFO Connecting to Discord RPC 2024/02/19 22:55:19 ERROR Could not connect to Discord RPC error="drpc: discord is not running" 2024/02/19 22:55:19 INFO Running Binary name=WindowsPlayer cmd="/app/bin/wine64 /home/hedonist/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-85c66b72a4fe4a74/RobloxPlayerBeta.exe roblox-player:1+launchmode:play+gameinfo:ikgLX28vAKMDfbsspihlhBsUw08-Nv4x0FQDxm2x057IS4SgoVemUssd4NLxWDVYA9dcSb3MWDnea6t-t1DVBOVeX6p_ozOIyB_94ovFdvHJI5rTpdiVAfAJVzjrM_HK--MWSOHOK_qd_iemcWrOZQd7d-PudEPeQwMxmAA1REl7SvCcT1cg3BykFbGVP-1tAy_fDzpRYmlVnJrZvdaDfJ1SbG73DxA-LBnSM8KIfeg+launchtime:1708404919104+placelauncherurl:https%3A%2F%2Fassetgame.roblox.com%2Fgame%2FPlaceLauncher.ashx%3Frequest%3DRequestGameJob%26browserTrackerId%3D216452391262%26placeId%3D863266079%26gameId%3Dd4fa6b77-10e5-48c5-8c57-851f0c818f38%26isPlayTogetherGame%3Dfalse%26joinAttemptId%3D099f755c-91e2-4bd5-8f60-b6205a60174a%26joinAttemptOrigin%3DServerListJoin+browsertrackerid:216452391262+robloxLocale:en_us+gameLocale:en_us+channel:" 002c:fixme:winediag:loader_init wine-staging 9.2 is a testing version containing experimental patches. 002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org. 0118:fixme:ntdll:NtRaiseHardError c0000005 stub 0118:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems 0118:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution. 0118:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems 0140:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000000CA6FF50 0118:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION 0118:fixme:keyboard:LoadKeyboardLayoutW name L"00000409", flags 2, semi-stub! Error [GENERAL | | OpenXR-Loader] : RuntimeManifestFile::FindManifestFiles - failed to find active runtime file in registry Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - unknown error Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - failed to load a runtime Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed to find default runtime with RuntimeInterface::LoadRuntime() Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed querying extension properties info: Game: RobloxPlayerBeta.exe info: DXVK: v2.3 info: Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x6ffff9503f40 info: Built-in extension providers: info: Win32 WSI info: OpenVR info: OpenXR info: OpenVR: could not open registry key, status 2 info: OpenVR: Failed to locate module info: Enabled instance extensions: info: VK_EXT_surface_maintenance1 info: VK_KHR_get_surface_capabilities2 info: VK_KHR_surface info: VK_KHR_win32_surface MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete warn: Skipping Vulkan 1.2 adapter: Intel(R) HD Graphics 2500 (IVB GT1) warn: Skipping CPU adapter: llvmpipe (LLVM 17.0.6, 256 bits) warn: DXVK: No adapters found. Please check your device filter settings and Vulkan setup. A Vulkan 1.3 capable driver is required. warn: DXGI: Found monitors not associated with any adapter, using fallback Error [GENERAL | | OpenXR-Loader] : RuntimeManifestFile::FindManifestFiles - failed to find active runtime file in registry Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - unknown error Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - failed to load a runtime Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed to find default runtime with RuntimeInterface::LoadRuntime() Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed querying extension properties warn: D3D11CreateDevice: Unsupported driver type warn: DXGI: Found monitors not associated with any adapter, using fallback err: D3D11CreateDevice: No default adapter available
> > ### System information
> > CPU: Intel(R) Core(TM) i5-3570 (4) @ 3.80 GHz GPU: Integrated Graphics
> > ```
> > * Installation method:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > F: Not sharing "/usr/share/icons" with sandbox: Path "/usr" is reserved by Flatpak
> > ```
> > * Vinegar: v1.7.3
> > 
> > * Distro: Freedesktop SDK 23.08 (Flatpak runtime)
> > 
> > * Processor: Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
> >   
> >   * Supports AVX: true
> >   * Supports split lock detection: false
> > 
> > * Kernel: 6.7.5-zen1-1-zen
> > 
> > * Wine (Player): v9.2 (Staging)
> > 
> > * Wine (Studio): v9.2 (Staging)
> > 
> > * Flatpak: [x]
> > 
> > * Cards:
> >   
> >   * Card 0: i915 0000:00:02.0 /sys/class/drm/card1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### Additional context
> > Add any other context about the problem here.
> > I am on a properly-configured Arch Linux system with KDE Plasma
> 
> `warn: DXVK: No adapters found. Please check your device filter settings and Vulkan setup. A Vulkan 1.3 capable driver is required.`
> 
> You'll need to use OpenGL, or get a new laptop.

How do i use OpenGL? i couldn't find anything in the docs or wiki.

**Comment by Cyanide-1** [comment]
nevermind i found out how to fix it, thank you
