### ISSUE TITLE
Failed to run roblox: roblox process: exit status 1

### ISSUE THREAD

**Issue by personman102** [vinegarhq/vinegar#377]
Whenever i open roblox it shows a white screen then crashes and shows the error Failed to run roblox: roblox process: exit status 1
i do not know what my problem is 

i do not know how to fix it

Vinegar: v1.7.3 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.5.0-18-generic
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card0

i was getting the memory dump error even tho i used wine 9.0 and i removed the prefix it worked but not it shows the white screen crashes then shows the error

**Comment by apprehensions** [comment]
use vulkan

**Comment by personman102** [comment]
whats vulkan?

**Comment by apprehensions** [comment]
read the docs

**Comment by personman102** [comment]
im insanely stupid where are the docs

**Comment by apprehensions** [comment]
on the README page of vinegar

**Comment by personman102** [comment]
k thx

**Comment by personman102** [comment]
i cant find the readme page i think i have brain damadge

**Comment by personman102** [comment]
nvm i got it

**Comment by personman102** [comment]
how do i switch from dvkx

**Comment by personman102** [comment]
i found a page and its saying this This may also indicate that your GPU doesn't meet the minimum Vulkan requirements; Use the OpenGL renderer, or set the installed DXVK version to one which includes a legacy version of Vulkan supported by your GPU.
but i have no idea what any of this stuff means

**Comment by apprehensions** [comment]
```
dxvk_version = "1.10.3"
```

**Comment by personman102** [comment]
what do i do with that?

**Comment by personman102** [comment]
do i put it in the terminal?

**Comment by apprehensions** [comment]
in the vinegar configuration

**Comment by lunarlettuce** [comment]
run `flatpak run org.vinegarhq.Vinegar edit`

**Comment by personman102** [comment]
do i paste that in there?

**Comment by personman102** [comment]
now what i put it in there but how do i make it do that command

**Comment by personman102** [comment]
how do i save it

**Comment by personman102** [comment]
:(

**Comment by personman102** [comment]
i edited the file still getting the error

**Comment by EDLLT** [comment]
> i edited the file still getting the error

Ask in this channel [#helpdesk-freeform](https://discord.com/channels/1069506340973707304/1162962714713399397) and we could try to help

You need to join the discord server if you haven't already otherwise the link above won't work
https://discord.gg/vinegarhq

**Comment by personman102** [comment]
invite is invalid

**Comment by EDLLT** [comment]
> invite is invalid
mb try this

https://discord.gg/dzdzZ6Pps2

**Comment by personman102** [comment]
nvm its not i just had to try it again

**Comment by personman102** [comment]
well it didint join me in to the server

**Comment by personman102** [comment]
nvm i got it

**Comment by personman102** [comment]
this is closed is now fixed How to fix: open files go to .var if you cant see it its in your home page then press ctrl + h if you still cant see it then go to config vinegar then config.toml and open it and type it in EXACTLY like this
[Player]
renderer="Vulkan"
dxvk=false
