### ISSUE TITLE
"wayland" variable for the config 

### ISSUE THREAD

**Issue by unittensor** [vinegarhq/vinegar#378]
While Wine 9.0 and over are allowing the use of the [Wayland driver through regedit and a variable](https://forum.winehq.org/viewtopic.php?p=142727&sid=bfc16e7bcf5c62a5ace1fa51fe3910cd#p142727) it would be nice if the Vinegar config offered `wayland = true` for `[studio]` and `[player]` that automatically enables/disables this variable in the regedit for wine prefixes.

**Comment by apprehensions** [comment]
No

**Comment by apprehensions** [comment]
Let wine decide when it is time to ship it by default. The wine driver is still experimental.
