### ISSUE TITLE
Cannot find Studio desktop

### ISSUE THREAD

**Issue by armalitedev** [vinegarhq/vinegar#380]
HI, I'm running the latest version of Vinegar on Ubuntu.
On Studio, I've exported a project but I cannot find the directory where it is located.

![Screenshot from 2024-02-21 10-29-14](https://github.com/vinegarhq/vinegar/assets/80101791/c6a0c187-02a3-4911-928c-17f56a6f5310)

**Comment by armalitedev** [comment]
^ I couldn't find this anywhere on my machine

**Comment by apprehensions** [comment]
Go in your app launcher, and make sure you have read the Vinegar installation instructions for Flatpak.

**Comment by armalitedev** [comment]
![Screenshot from 2024-02-21 10-50-26](https://github.com/vinegarhq/vinegar/assets/80101791/f123979c-f48b-476a-8031-483dab9b98f3)
![Screenshot from 2024-02-21 10-51-23](https://github.com/vinegarhq/vinegar/assets/80101791/2b5fd068-d95a-4a35-9746-6b0d7aac9baf)

There is nothing here that helps me.

**Comment by apprehensions** [comment]
Screenshotting your environment doesn't help. Did you check your application launcher?

**Comment by armalitedev** [comment]
THAT is my application launcher.

**Comment by apprehensions** [comment]
![image](https://github.com/vinegarhq/vinegar/assets/47404953/799a198f-3ee3-4f66-a85b-790f16a0e338)

**Comment by armalitedev** [comment]
![Uploading Screenshot from 2024-02-21 10-57-51.png…]()

**Comment by armalitedev** [comment]
![Screenshot from 2024-02-21 10-57-51](https://github.com/vinegarhq/vinegar/assets/80101791/1bc7197f-4fba-4c8f-b21e-3c8900d2b7ff)

**Comment by armalitedev** [comment]
I meant the simulated one.

**Comment by apprehensions** [comment]
?
