### ISSUE TITLE
02b4:err:esync:esync_init Failed to open esync shared memory file; make sure no stale wineserver instances are running without WINEESYNC.

### ISSUE THREAD

**Issue by TheCorruptCat** [vinegarhq/vinegar#381]
02b4:err:esync:esync_init Failed to open esync shared memory file; make sure no stale wineserver instances are running without WINEESYNC.

there is no wineserver

**Comment by apprehensions** [comment]
restart your pc

**Comment by apprehensions** [comment]
read the issue template b tw
