### ISSUE TITLE
DXVK doesn't get installed to prefix after running `vinegar delete`

### ISSUE THREAD

**Issue by guihkx** [vinegarhq/vinegar#384]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I have a DXVK version specified for the Player:

```toml
[player]
renderer = "D3D11"
dxvk = true
dxvk_version = "1.10.3"
```

Then, I deleted the prefix and binaries with:

```
$ flatpak run org.vinegarhq.Vinegar delete
2024/02/21 20:22:44 INFO Deleting Wineprefixes and Roblox Binary deployments!
```

However, upon launching the Player again, Vinegar didn't set up DXVX.

The workaround I found was to manually delete the state file: `~/.var/app/org.vinegarhq.Vinegar/data/vinegar/state.json`. Then, launching the Player again made Vinegar set up DXVK correctly.

### System information

```shell
* Vinegar: v1.7.3 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.7.5-arch1-1
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: nvidia 0000:01:00.0 /sys/class/drm/card0
```

**Comment by apprehensions** [comment]
Solved in a48ad4c671ee9b464ed526a403389f51491222ac

Needs a stable release.
