### ISSUE TITLE
I didnt touch the config but today it didnt start.

### ISSUE THREAD

**Issue by wotikama** [vinegarhq/vinegar#386]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[wotikama@archlinux ~]$ vinegar player run
2024/02/22 22:52:03 INFO Logging to file path=/home/wotikama/.cache/vinegar/logs/Player-2024-02-22T22:52:03+01:00.log
2024/02/22 22:52:03 INFO Fetching Binary Deployment name=WindowsPlayer channel=""
2024/02/22 22:52:04 INFO Binary is up to date! name=WindowsPlayer guid=version-70a2467227df4077
2024/02/22 22:52:04 INFO Connecting to Discord RPC
2024/02/22 22:52:04 ERROR Could not connect to Discord RPC error="drpc: discord is not running"
2024/02/22 22:52:04 INFO Running Binary name=WindowsPlayer cmd="/usr/bin/gamemoderun /usr/bin/wine64 /home/wotikama/.local/share/vinegar/versions/version-70a2467227df4077/RobloxPlayerBeta.exe"
gamemodeauto: 
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0024:fixme:ntdll:NtRaiseHardError c0000005 stub
0024:err:seh:call_stack_handlers invalid frame 000000017007A260 (0000000000122000-0000000000320000)
0024:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
2024/02/22 22:52:05 failed to run roblox: roblox process: exit status 5

I tried with Vulkan/D3D11, both same error

### System information

```shell
[wotikama@archlinux ~]$ vinegar sysinfo
* Vinegar: v1.7.3 (501372490598e0fc61d8fd08c49b89a5b3c79822)
* Distro: Arch Linux
* Processor: AMD Ryzen 5 5600 6-Core Processor
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.7.5-zen1-1-zen
* Wine (Player): wine-8.10
* Wine (Studio): wine-8.10
* Cards:
  * Card 0: nvidia 0000:05:00.0 /sys/class/drm/card0
```

**Comment by brotherman123** [comment]
delete state.json at
/home/USER/.var/app/org.vinegarhq.Vinegar/data/vinegar/
then use the desktop app

**Comment by strawbberrys** [comment]
Having the same issue. I've tried on wine-ge, wine-9.2, and wine-staging, all produce the same crash. Didn't start happening until last night. Only thing I can think of is Roblox doesn't work without flatpak specific patches now? Haven't tried flatpak yet.

**Comment by wotikama** [comment]
That worked, thank you..
