### ISSUE TITLE
Could someone just copy and paste state.json? 

### ISSUE THREAD

**Issue by brotherman123** [vinegarhq/vinegar#390]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Could someone just copy and paste state.json? It said state.json is a directory. So i deleted the directory as it was just a studio prefix. I made my own state.json but it didn't work as i dont have the text.

### System information

```shell
* Vinegar: v1.7.3 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.7.5-200.fc39.x86_64
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card0
  * Card 1: nouveau 0000:01:00.0 /sys/class/drm/card1
```

**Comment by apprehensions** [comment]
state.json is internal. You as a normal user are never meant to modify it.

**Comment by brotherman123** [comment]
Yes i realize this
