### ISSUE TITLE
Forcing version insta crashes.

### ISSUE THREAD

**Issue by brotherman123** [vinegarhq/vinegar#391]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I changed studio to be version `c021e5affd3d38dadf2f70fdbdd37b285f1f1eb5bdbc14a70dfe138ab89e993e`  (as it was the only one where authentication was working fine) running roblox studio instantly crashes it. This was my only solution as webview2 isn't implemented yet.
(this is my config)`
`# See how to configure Vinegar on the documentation website:`
`# https://vinegarhq.org/Configuration`
`[studio]`
`forced_version = 'c021e5affd3d38dadf2f70fdbdd37b285f1f1eb5bdbc14a70dfe138ab89e993e'`

screenshot of trying to open studio:
![image](https://github.com/vinegarhq/vinegar/assets/156553255/e7a91ddc-f8d5-4c5b-9608-970bca058e0e)

### System information

```shell
* Vinegar: v1.7.3 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.7.5-200.fc39.x86_64
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card0
  * Card 1: nouveau 0000:01:00.0 /sys/class/drm/card1
```

**Comment by apprehensions** [comment]
`c021e5affd3d38dadf2f70fdbdd37b285f1f1eb5bdbc14a70dfe138ab89e993e` is not a valid Version GUID. There is a reason why it is `403 Forbidden` as it is invalid.
