### ISSUE TITLE
vinegar wont start

### ISSUE THREAD

**Issue by maribtw** [vinegarhq/vinegar#400]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Roblox wont start (i was literally playing before, didnt update anything on my laptop and after i tried to run roblox again, it didnt work). config file is the one in troubleshooting. had the same error with it or mine.

❯ flatpak run org.vinegarhq.Vinegar -config=~/config.toml player run
2024/03/01 00:53:37 INFO Logging to file path=/home/mari/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/Player-2024-03-01T00:53:37Z.log
2024/03/01 00:53:37 INFO Fetching Binary Deployment name=WindowsPlayer channel=""
2024/03/01 00:53:38 INFO Binary is up to date! name=WindowsPlayer guid=version-bca459bcd1854ce4
2024/03/01 00:53:38 INFO Enabling WINE DXVK DLL overrides
2024/03/01 00:53:38 INFO Connecting to Discord RPC
2024/03/01 00:53:38 ERROR Could not connect to Discord RPC error="drpc: discord is not running"
2024/03/01 00:53:38 INFO Running Binary name=WindowsPlayer cmd="/app/bin/wine64 /home/mari/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-bca459bcd1854ce4/RobloxPlayerBeta.exe"
002c:fixme:winediag:loader_init wine-staging 9.2 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
0050:err:winediag:is_broken_driver Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
0050:fixme:xrandr:xrandr10_get_current_mode Non-primary adapters are unsupported.
00e4:err:winediag:is_broken_driver Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
0050:fixme:xrandr:xrandr10_get_current_mode Non-primary adapters are unsupported.
0050:fixme:xrandr:xrandr10_get_current_mode Non-primary adapters are unsupported.
00e4:fixme:xrandr:xrandr10_get_current_mode Non-primary adapters are unsupported.
0034:err:winediag:is_broken_driver Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
002c:err:winediag:is_broken_driver Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
0024:err:winediag:is_broken_driver Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
0130:err:winediag:is_broken_driver Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
0130:fixme:ntdll:NtRaiseHardError 50000018 stub
0130:fixme:dialog:MessageBoxTimeoutW timeout not supported (0)
2024/03/01 00:53:44 ERROR Failed to find Roblox log file error="roblox log file not found after 6s"
2024/03/01 00:55:29 ERROR failed to run roblox: roblox process: exit status 187

### System information

```shell
* Vinegar: v1.7.4 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Ryzen 7 7840HS w/ Radeon 780M Graphics
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.7.6-arch1-2
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: simple-framebuffer simple-framebuffer.0 /sys/class/drm/card0
  * Card 1: nvidia 0000:01:00.0 /sys/class/drm/card1
  * Card 2: amdgpu 0000:05:00.0 /sys/class/drm/card2
```

**Comment by maribtw** [comment]
Also I tried to unintall and reinstall everything because I read #396 but it still didn't work :(

**Comment by lunarlettuce** [comment]
#397
