### ISSUE TITLE
Save Studio settings after deleting prefixes

### ISSUE THREAD

**Issue by Eggflaw** [vinegarhq/vinegar#406]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

Whenever I delete wine prefixes, all of my studio settings will get deleted and setting them up again is annoying and tedious to me.

### Describe the Solution you'd Like

After doing my own research I found out these three files which saves the settings written below

- `(studio prefix)/user.reg` : Studio theme, Docking layout
- `(studio prefix)/drive_c/users/(user)/AppData/Local/Roblox/GlobalSettings_13.xml`: Most of the studio settings ( Fonts etc )
- `(studio prefix)/drive_c/users/(user)/AppData/Local/Roblox/GlobalBasicSettings_13_Studio.xml`: Extra studio settings ( MicroProfiler, Fullscreen )

### Here's how I would Implement this
1. Before deleting wine prefixes,  Save those three files above into folder called `studio` and put it under the `cache` or `data` directory.
2. After the studio prefix is initialized, copy the files to their respective path.
3. Done?

Feel free give your own ideas or mention any problems with mine.

### Describe Alternatives you've considered

At first, I was thinking about using symlinks but since normally copying files works fine, I think it is unnecessary. 

### Before copying files
https://github.com/vinegarhq/vinegar/assets/108559753/2ee5fe7b-5a53-427b-a0de-07a9faa3d081

### After copying files and logging in
https://github.com/vinegarhq/vinegar/assets/108559753/bfcd2c4b-cfea-4371-b475-360c64572281

Notes:
- First video is compressed due to high file size
- I don't know why I have to log in again after copying the files

**Comment by apprehensions** [comment]
It is the users responsibility to backup their wineprefix data.

**Comment by Eggflaw** [comment]
At least give a warning that encourages the user to backup their data before deleting wineprefixes?
I'm certain there are users that don't know where the data is and are unaware their settings will be wiped.

**Comment by apprehensions** [comment]
Again, it is the users responsibility to keep in mind the data is somewhere. Alongside acknowledging that Wine is being used, one can assume it is in the wineprefix. If you'd like, you can suggest or contribute a way to warn the user. Deleting wineprefixes is very common for Player but not for Studio.

**Comment by Eggflaw** [comment]
I'll try
