### ISSUE TITLE
"wine not supported"

### ISSUE THREAD

**Issue by wuvxy2** [vinegarhq/vinegar#407]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

[Player-2024-03-07T17:28:55-06:00.log](https://github.com/vinegarhq/vinegar/files/14531204/Player-2024-03-07T17.28.55-06.00.log)

**Comment by lunarlettuce** [comment]
#397

**Comment by sulincix** [comment]
```C
#include <windows.h>
#include <stdio.h>
int main(void)
{
    static const char *(CDECL *pwine_get_version)(void);
    HMODULE hntdll = GetModuleHandle("ntdll.dll");
    if(!hntdll)
    {
        puts("Not running on NT.");
        return 1;
    }

    pwine_get_version = (void *)GetProcAddress(hntdll, "wine_get_version");
    if(pwine_get_version)
    {
        printf("Running on Wine... %s\n",pwine_get_version());
    }
    else
    {
        puts("did not detect Wine.");
    }

    return 0;
}
```
![image](https://github.com/vinegarhq/vinegar/assets/55052890/207e8966-7305-404e-9d2b-6b14e4004095)

**Comment by apprehensions** [comment]
Well, how did it go?

**Comment by sulincix** [comment]
![image](https://github.com/vinegarhq/vinegar/assets/55052890/1b9fbcdf-1e0b-4ba6-9343-d3dffcf640e6)

1. patch binary with sed command
2. run installer and install.
3. go installed files and patch again
4. remove installer file and replace with empty file
5. replace ntdll.dll file from windows xp
6. set wine version as 7
7. run :D

**Comment by sulincix** [comment]
I think this patch required :
https://github.com/wine-staging/wine-staging/blob/master/patches/ntdll-Hide_Wine_Exports/0001-ntdll-Add-support-for-hiding-wine-version-informatio.patch

**Comment by tristann21** [comment]
> ![image](https://private-user-images.githubusercontent.com/55052890/328668437-1b9fbcdf-1e0b-4ba6-9343-d3dffcf640e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMTUwNjEsIm5iZiI6MTcxNTExNDc2MSwicGF0aCI6Ii81NTA1Mjg5MC8zMjg2Njg0MzctMWI5ZmJjZGYtMWUwYi00YmE2LTkzNDMtZDNkZmZjZjY0MGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDIwNDYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxOWU3MjA3NmYyZTE3NGI3Y2FkNTQwNmQxNTQ3MTBlYjlkYzExNDlkYmMzNzE3NGE4M2YwOWJmZTkyYjM5MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.se0we9TBhroc5V5XA9M0zvCz2JBg1gc_9CGUrV-zV4A)
> 
>     1. patch binary with sed command
> 
>     2. run installer and install.
> 
>     3. go installed files and patch again
> 
>     4. remove installer file and replace with empty file
> 
>     5. replace ntdll.dll file from windows
> 
>     6. set wine version as 7
> 
>     7. run :D

Doesn't Hyperion just bork?

**Comment by TeknosQuet** [comment]
roblox hyperion (10 mil invested)
VS
replace 1 dll file and run on linux (0 dollar invested)

**Comment by km9l** [comment]
>     7. run :D

8. see the smoke come out
