### ISSUE TITLE
vinegar not found by bash

### ISSUE THREAD

**Issue by Awire9966** [vinegarhq/vinegar#409]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

My bash terminal is not finding vinegar. 
My console: 
awire@DDO:~/Downloads/vinegar$ flatpak run org.vinegarhq.Vinegar run

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/awire/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

usage: vinegar [-config filepath] [-firstrun] player|studio run [args...]
       vinegar [-config filepath] player|studio kill|winetricks
       vinegar [-config filepath] sysinfo
       vinegar delete|edit|uninstall|version
awire@DDO:~/Downloads/vinegar$ vinegar
bash: vinegar: command not found

### System information

```shell
Dell Optiplex 790
8 GB of ram
Intel i3
Debian 12
LXDE
```

**Comment by Eggflaw** [comment]
If you installed Vinegar from flatpak, you're supposed to run
`flatpak run org.vinegarhq.Vinegar studio run`

**Comment by apprehensions** [comment]
Flatpak is sandboxed, make an alias:

```
alias vinegar='flatpak run org.vinegarhq.Vinegar'
```
