### ISSUE TITLE
Mouse cursor too fast in roblox Studio

### ISSUE THREAD

**Issue by gougoules** [vinegarhq/vinegar#410]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Hello, my mouse cursor is too fast and it goes sometimes in the wrong way (with a delay), I don't know why. I tried to change my cursor speed in roblox studio settings but it doesn't change. I tried to reduce my DPI on my mouse it doesn't work too

### System information

```shell
* Vinegar: v1.7.4 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
  * Supports AVX: true
  * Supports split lock detection: true
* Kernel: 6.5.5-200.fc38.x86_64
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: nouveau 0000:01:00.0 /sys/class/drm/card1
  * Card 1: i915 0000:00:02.0 /sys/class/drm/card2
FEDORA 38
```

**Comment by jrelvas-ipc** [comment]
Are you on a Wayland session?

**Comment by gougoules** [comment]
How can we know that ?

**Comment by gougoules** [comment]
Yes Wayland

**Comment by jrelvas-ipc** [comment]
This is a [known limitation](https://vinegarhq.org/Troubleshooting/index.html#cursor-fails-to-lock) with XWayland and Roblox Studio. The recommendation is to try the X11 session and see if the problem still happens.

**Comment by gougoules** [comment]
I run this command "flatpak run org.vinegarhq.Vinegar studio run --force-grab-cursor" but it doesn't seems to work :(

**Comment by apprehensions** [comment]
That isn't a real flag. Read the comment.

**Comment by jrelvas-ipc** [comment]
That's a `gamescope` option, which is configured separately as a [launcher](https://vinegarhq.org/Configuration/index.html#binary-configuration). Gamescope doesn't really work well for Studio anyways, so the best thing to do here would be to switch to the X11 session. For example:

![imagem](https://github.com/vinegarhq/vinegar/assets/55360900/ee770cef-b81f-4da5-842b-19a510f5984d)

**Comment by gougoules** [comment]
Ok thanks, I looked for change to x11 and it's now all working, thanks a lot

**Comment by LSeelig** [comment]
Is there a better way to deal with it? Moving the look/view with the mouse seems broken with my high dpi display. It resolves itself in play mode, so there must be a way to sync the look between the two or use whatever fix play mode uses.
