### ISSUE TITLE
Double quotation marks turning into backticks

### ISSUE THREAD

**Issue by luj-s** [vinegarhq/vinegar#412]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Typing double quotation marks in any Roblox Studio input field(script editor, properties, text boxes etc.), instead of inserting the correct character ("), inserts a pair of backticks (``).
Any other character works as expected.
Latest log file: 
[Studio-2024-04-29T21:27:26Z.log](https://github.com/vinegarhq/vinegar/files/15156573/Studio-2024-04-29T21.27.26Z.log)

### System information

```shell
Compositor: Sway (Wayland)
Keyboard layout: br (Brazil portuguese) nodeadkeys

Output of run org.vinegarhq.Vinegar sysinfo:
* Vinegar: v1.7.4 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Ryzen 3 2200G with Radeon Vega Graphics
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.8.7-arch1-2
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: amdgpu 0000:08:00.0 /sys/class/drm/card1
```

**Comment by apprehensions** [comment]
This is due to your keyboard layout.

**Comment by luj-s** [comment]
> This is due to your keyboard layout.

Oh, i switched to the normal variant and it now works. Still, it's kinda weird because it works fine in other programs.
