### ISSUE TITLE
Please update this to let people know it no longer works and will never work again.

### ISSUE THREAD

**Issue by Roadhog360** [vinegarhq/vinegar#422]
On behalf of several Linux help subreddits, **PLEASE UPDATE THIS SO PEOPLE STOP ASKING US FOR HELP WITH IT**! We know it is broken and will never work again but that fact isn't abundantly clear, even with Google someone may get the impression it is fixable. It is not. It throws vague errors or doesn't clearly tell the user that it is permanently broken, and the vague errors give users hope that it is fixable, when it is not. Please make an update for this to clearly state that it can no longer launch ROBLOX, it never will again, and suggest to uninstall it. Please also update all of your front pages to state this fact. Also state that no, Grapejuice won't work either. ROBLOX is going out of their way to block Linux and VMs and there is NO WAY for it to work again.

A simple notice that states something along the lines of "This application is no longer functional due to ROBLOX blocking Linux. Unless they reverse this decision, there is no way to play the game on your system." message would suffice when the user tries to open the game. This way, it'll stop the stream of confused people who want help, as the program they downloaded to try to get ROBLOX on their computer, will give them their definitive answer. I come here because there are people still downloading this to this day and trying to get it working, not knowing about the fact that ROBLOX has gone out of their way to prevent it.

I have not tested studio since I don't really know how to use it. If studio still works then this warning should only apply to the game itself. It *opened* but I'm not really sure how I'd go about properly testing if it worked so I just closed it. Someone else can testify whether or not it still works.

**Comment by apprehensions** [comment]
Sure.

**Comment by apprehensions** [comment]
Next time, make a feature request.

**Comment by km9l** [comment]
> On behalf of several Linux help subreddits, PLEASE UPDATE THIS SO PEOPLE STOP ASKING US FOR HELP WITH IT!

if they cant google, find the only alive launcher and read this [faq](https://vinegarhq.org/Home/rol_faq.html) they should stop using a computer
it is not our fault that people follow years old random guides on youtube
and if anyone comes to your subreddits asking about roblox link the faq

**Comment by Roadhog360** [comment]
As mentioned in the OP, Google does not clearly state it. Linking the faq won't stop them, I think it'd be more productive to make the issue readily apparent, instead of expecting the user to go to websites that aren't immediately visible.

Google is NOT reliable on this topic:
![image](https://github.com/user-attachments/assets/13f4f2ab-1c4d-47ee-aa39-e45dbb37f5b1)
![image](https://github.com/user-attachments/assets/b5cee6d6-693b-4522-b89c-2ea308253176)

**Comment by km9l** [comment]
> I think a better option would be to do an AVX-style block. It would the user about the issue, but not outright block it. It's not a good idea to fully block the user off, in the case that one wants to experiment with something.

doesnt roblox have a wine block prompt? why are we implementing this ourselves?

> Google is NOT reliable on this topic:

because that roblox fandom page is outdated and google for some reason decided to show that up
im pretty sure that fandom page is public, why wont you go and edit it?

**Comment by Roadhog360** [comment]
I often forget that Wikis are publicly editable. I'm not personally a fan of creating a Fandom account but for this I will do it.

**Comment by Roadhog360** [comment]
Even the other results, have varying results, since they're from the past. People are going to see this and mistakenly think it's possible to fix. Why not just include the message, which solves the problem at its root by clearly stating to users right then and there, that they are not going to get it to work, and why. Why make people find external websites when the application itself can do it? The developer knows their launcher won't work any more, so why should the user have to find that out themselves?

**Comment by Roadhog360** [comment]
> km9l does bring up a good point, Roblox itself has a "Wine is not supported" error. Adding one would be pretty redundant.

You typed this while I was writing my previous reply so I did not see it right away. When does it state this? I launched the program with Vinegar as a test before submitting this, and it displayed no such error on Grapejuice or Vinegar. So on some setups there may be different errors in the way of that, but in that case that only strengthens the case for something like this, as there's no point in trying to fix it, as if we get past whatever is stopping me from seeing it, we'll only be greeted by ROBLOX saying it. All that fixing and tinkering for nothing.

**Comment by km9l** [comment]
> When does it state this? I launched the program with Vinegar as a test before submitting this, and it displayed no such error on Grapejuice or Vinegar.

you do have a point because the warning broke
i thought it was fixed after people reported it to devforum, but it appears not...

**Comment by Roadhog360** [comment]
My case here is it shouldn't even try. It should display the message, which saves time, effort and hard disk space. Why should it go through the process of downloading and trying to launch the game when it will fail 100% of the time?

Why download and install the game just to display this error that apparently didn't show up for everyone, including me? I didn't even know this was a thing.

**Comment by Roadhog360** [comment]
I appreciate the developers listening to this request.
