### ISSUE TITLE
Verify the Flatpak package on Flathub

### ISSUE THREAD

**Issue by orowith2os** [vinegarhq/vinegar#43]
Flathub Beta has a feature for verifying applications that are officially endorsed by their developers. Hundreds of apps (~300 currently) take advantage of this feature, and it is relatively simple to implement. 

As this project seems to officially provide the flatpak, it would be ideal to verify it. I can assist with doing so if desired.

**Comment by orowith2os** [comment]
Endorsing the packaging, not what the apps themselves do ;)

Should have mentioned that

**Comment by apprehensions** [comment]
elaborate by packaging

**Comment by orowith2os** [comment]
AUR package, Flatpak package, Fedora package, etc. A collection of binaries and/or build scripts used to build a bundle that can be installed and used to run the application.

**Comment by apprehensions** [comment]
I mean what you meant by 'endorsing packaging'

**Comment by orowith2os** [comment]
By definition, endorse means ones public approval or support of something. By endorsing a package, you approve or support it.

**Comment by apprehensions** [comment]
ok its been verifi,ed
