### ISSUE TITLE
When 

### ISSUE THREAD

**Issue by python-coding-404** [vinegarhq/vinegar#433]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

After installing the roblox client, it tried to run it.
When trying to run it when the progress bar when full nothing happened.
All I could see was the log entry `0278:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub` repeat infinitely.

Here are the logs:

`Sep 20 17:07:35.957 INF Fetching Binary Deployment name=WindowsPlayer channel=""
Sep 20 17:07:36.624 INF Fetched Binary Deployment! name=WindowsPlayer channel="" guid=version-43ad1853ad91427d version=0.642.0.6420636
Sep 20 17:07:36.624 INF Binary is up to date! name=WindowsPlayer guid=version-43ad1853ad91427d
Sep 20 17:07:36.624 INF Enabling WINE DXVK DLL overrides
Sep 20 17:07:36.624 INF DXVK up to date! version=2.3
Sep 20 17:07:36.624 INF Running Binary name=WindowsPlayer cmd="/etc/eselect/wine/bin/wine64 /home/zander/.local/share/vinegar/versions/version-43ad1853ad91427d/RobloxPlayerBeta.exe"
esync: up and running.
002c:fixme:winediag:loader_init wine-staging 9.15 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc00000bb,0x5e7db189,0xae6efc43,0x00000000) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x8,0x9e4a1562,0x00000008) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
0024:fixme:file:NtSetVolumeInformationFile (0xffffffffffffffff,0xc0000022,0x62,0xb2ba55e2,0x00000062) stub
`  and so on and so on.

### System information

```shell
* Vinegar: v1.7.5 
* Distro: Gentoo Linux 2.15
* Processor: Intel(R) Core(TM) i5-10200H CPU @ 2.40GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.6.47-gentoo-x86_64
* Wine (Player): wine-9.15 (Staging)
* Wine (Studio): wine-9.15 (Staging)
* Cards:
  * Card 0: nvidia 0000:01:00.0 /sys/class/drm/card0
  * Card 1: i915 0000:00:02.0 /sys/class/drm/card1
```

**Comment by apprehensions** [comment]
Wine is currently blocked on WindowsPlayer (#397), and you should have received a dialog telling you so.

See https://vinegarhq.org/ for more information.
