### ISSUE TITLE
vinegar memory usage progressively increasing while editing a game

### ISSUE THREAD

**Issue by RapidRuwuby** [vinegarhq/vinegar#434]
### Acknowledgement of preliminary instructions

- [x] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

runs fine right after install but does this when ran again (reaches around 24 gigs within 10~ minutes) 
this started happening after i reinstalled vinegar cause autofill stopped working
![image](https://github.com/user-attachments/assets/ee0f9560-b386-49f7-950c-07999ac076ef)

### System information

```shell
* Vinegar: v1.7.5 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Ryzen 5 5500
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.9.12-3-MANJARO
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: amdgpu 0000:03:00.0 /sys/class/drm/card1
```

**Comment by apprehensions** [comment]
This is most likely Studio itself consuming memory, and not Vinegar. You can confirm this by looking at the individual processes using your task manager.

**Comment by RapidRuwuby** [comment]
![image](https://github.com/user-attachments/assets/73c3f983-eb52-4078-b969-2bd9ea9b81d3)
i feel like i should mention that this happens on every game, even baseplates
