### ISSUE TITLE
Rendering Glitches

### ISSUE THREAD

**Issue by CatapultTV** [vinegarhq/vinegar#446]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Not sure if it is a problem with Roblox Studios or maybe my computer, but there seems to be some problems when rendering objects as well as the scene and place, sometimes the icons in the windows also glitch out white and come back, here's how the scene looks inside of Studio:
![image](https://github.com/user-attachments/assets/414a2f41-c69a-42a9-b8cb-4b3cc67c4329)

Here's one for a car:
![image](https://github.com/user-attachments/assets/6c6fef55-bff2-43db-8526-4f58d1c28789)

### System information

```shell
* Vinegar: v1.7.7 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
  * Supports AVX: true
  * Supports split lock detection: true
* Kernel: 6.8.0-45-generic
* Wine (Player): wine-9.18 (Staging)
* Wine (Studio): wine-9.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card1
```

**Comment by CatapultTV** [comment]
As you can see in the second picture (the car) the background was fixed. However, if I were to add a new object, move the camera, or even just idle there, then the background starts stuttering

**Comment by CatapultTV** [comment]
![image](https://github.com/user-attachments/assets/7f782482-b38c-4a39-a509-f4fd3cb697ae)
![image](https://github.com/user-attachments/assets/bf5ad090-0250-48db-9e3c-55d9be97e81d)


Um Idk abt the second one I tried opening it up using the command "flatpak run org.vinegarhq.Vinegar edit" but it only shows these two lines

**Comment by CatapultTV** [comment]
![image](https://github.com/user-attachments/assets/71a0b3a6-463b-47b6-8ae4-67e0bd62d119)


Though I know the issue is the rendering and I also know that the rendering engine is wrong but when I tried to change it in the file, it did not work AT ALL, studio wont open up if I change anything in this file

**Comment by gresm** [comment]
@CatapultTV  If you set ``renderer = "OpenGL"`` or ``renderer = "Vulkan"``, you have to also set ``dxvk = false``
Quoting from the docs:
> The renderer must be one of the following: ``"OpenGL"``, ``"D3D11FL10"``, ``"D3D11"``, ``"Vulkan"``; when using DXVK, ensure that the renderer is ``"D3D11"``, otherwise Roblox will not utilize DXVK.

**Comment by CatapultTV** [comment]
Thanks @gresm

**Comment by CatapultTV** [comment]
Case closed

**Comment by CatapultTV** [comment]
Though I still have verryyyyyy terrible performance issues due to openGl and I cant use vulcan for some reason

**Comment by gresm** [comment]
@CatapultTV See https://github.com/vinegarhq/vinegar/issues/444#issuecomment-2395473060
