### ISSUE TITLE
Disable fps unlocker option?

### ISSUE THREAD

**Issue by Wibbbs** [vinegarhq/vinegar#45]
Is there anyway to disable the fps unlocker? I am trying this on a steam deck, and it is not respecting the os frame cap limiter in game mode. Since I am playing on 60hz displays i would like to cap at 60fps to try to smooth out frame times a bit.

**Comment by apprehensions** [comment]
https://vinegarhq.github.io/Configuration/index.html

> Note that RCO is going to also unlock the FPS in Roblox by default, so using rbxfpsunlocker is reccomended only when not using RCO. RCO unlocks FPS by setting the FFlag DFIntTaskSchedulerTargetFps to a arbitrary big value (10000). However, if you also want to limit the FPS you may set the FFlag's value to your requested limit (eg. 30)

**Comment by Wibbbs** [comment]
DFIntTaskSchedulerTargetFps Did the trick. Thanks!
