### ISSUE TITLE
Roblox Studio cannot login

### ISSUE THREAD

**Issue by efa** [vinegarhq/vinegar#466]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Roblox Studio start but fail to login.
Show: WebView2 installation required to load login page.
Login via Browser will open Chrome where I'm already logged in in another tab, but once logged in, cannot back to Roblox Studio, see attached images.
![RobloxStudio_login0](https://github.com/user-attachments/assets/a9b61906-2089-404b-a706-103c87c343b1)
![RobloxStudio_login1](https://github.com/user-attachments/assets/01840e5e-2fa0-429b-9864-52f81114151e)
![RobloxStudio_login2](https://github.com/user-attachments/assets/7ee3c09e-56c4-482a-905f-e91055962bd5)

### System information

```shell
$ flatpak run org.vinegarhq.Vinegar sysinfo
* Vinegar: v1.7.7 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.1.0-28-amd64
* Wine (Player): wine-9.18 (Staging)
* Wine (Studio): wine-9.18 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: radeon 0000:01:00.0 /sys/class/drm/card0
  * Card 1: i915 0000:00:02.0 /sys/class/drm/card1

$ flatpak list
Name                                 Application ID                       Version                  Branch      Origin  Installation
Freedesktop Platform                 org.freedesktop.Platform             freedesktop-sdk-23.08.25 23.08       flathub user
Mesa                                 org.freedesktop.Platform.GL.default  24.2.5                   23.08       flathub user
Mesa (Extra)                         org.freedesktop.Platform.GL.default  24.2.5                   23.08-extra flathub user
Mesa                                 org.freedesktop.Platform.GL.default  24.2.7                   24.08       flathub user
Mesa (Extra)                         org.freedesktop.Platform.GL.default  24.2.7                   24.08extra  flathub user
Intel VAAPI driver                   org.freedesktop.Platform.VAAPI.Intel                          23.08       flathub user
openh264                             org.freedesktop.Platform.openh264    2.1.0                    2.2.0       flathub user
openh264                             org.freedesktop.Platform.openh264    2.4.1                    2.4.1       flathub user
GNOME Application Platform version … org.gnome.Platform                                            47          flathub user
Breeze GTK theme                     org.gtk.Gtk3theme.Breeze             6.2.4                    3.22        flathub user
Sober                                org.vinegarhq.Sober                  0.0.0-9619e88            master      sober   user
Vinegar                              org.vinegarhq.Vinegar                1.7.7                    stable      flathub user
```

**Comment by efa** [comment]
here the stderr on the terminal. Stdout is empty:
[RobloxStudio_Login_stderr.txt.tar.gz](https://github.com/user-attachments/files/17982738/RobloxStudio_Login_stderr.txt.tar.gz)

**Comment by WTlynx** [comment]
also have this issue of not having webview2 installed, but after a few attempts it finally let me in. try using the multiple_instances configuration

```
[env]
WINEESYNC = "0"
multiple_instances = "true"
 
[studio]
#forced_version="version-9b68669a3b644e31"
```

```
* Vinegar: v1.7.8 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  * Supports AVX: true
  * Supports split lock detection: true
* Kernel: 6.11.0-9-generic
* Wine (Player): wine-9.22 (Staging)
* Wine (Studio): wine-9.22 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card1
  * Card 1: nouveau 0000:01:00.0 /sys/class/drm/card2
```

**Comment by efa** [comment]
With last flatpak update, Roblox Studio started to stuck on splash. Once commented forced_version back to cannot login.
Tryed multiple_instances and WINEESYNC with no luck, still cannot login

**Comment by apprehensions** [comment]
multiple_instances is removed from Vinegar.

Your WebView installation is broken.

Closing in favor of comment https://github.com/vinegarhq/vinegar/issues/427#issuecomment-2256626206

**Comment by efa** [comment]
I'm sure I've never installed WebView2 on this Linux.
Is this something that native wine had to install (like it does for Mono) or is it part of the flatpak runtime?

**Comment by apprehensions** [comment]
Webview is installed automatically by Vinegar. run `vinegar delete`

**Comment by efa** [comment]
YES, after delete, on next studio run, I can correctly login

**Comment by efa** [comment]
it flicker a lot but work

**Comment by BnDLett** [comment]
I'm currently experiencing this issue. It states that it extracts webview2, but I cannot login via Roblox Studio. I'm on Arch Linux.

(not all logs; only in-terminal logs that contains "webview2")
```
02:07:55 INFO Extracting package name=WebView2.zip dest=.
02:07:55 INFO Extracting package name=WebView2RuntimeInstaller.zip dest=WebView2RuntimeInstaller
2:08:01 RBLX WebView2: Failed to find an installed WebView2 runtime or non-stable Microsoft Edge installation.\n
02:08:01 RBLX WebView2: Failed to find an installed WebView2 runtime or non-stable Microsoft Edge installation.\n
```
