### ISSUE TITLE
Shift-lock Cursor Not Centred

### ISSUE THREAD

**Issue by toolifelesstocode** [vinegarhq/vinegar#47]
When using the Windows version of ROBLOX, going into shift-lock mode would make the cursor go to the centre of the app, no matter how much you try to make it move (it does not move likely so that turning your avatar is easier). However, when I do so on the Vinegar ROBLOX app, the shift-lock cursor goes anywhere on the screen when I try move it.

Note, I am not too sure if this is a Vinegar issue specifically or something else.

**Comment by apprehensions** [comment]
https://vinegarhq.github.io/Installation/index.html

> Make sure you have installed Wine 8.3 and up, it has Low Fragmentation Heap implemented, which can give a large performance increase.

Your Wine somehow does not support cursor locking, are you on X11 or Wayland? Wayland has issues with cursor locking and is yet to be fixed.

**Comment by apprehensions** [comment]
Currently, workarounds to this are to use Gamescope.

The wine wayland driver is a choice but is heavily in the works and is not suited for Roblox, or programs at the moment.
