### ISSUE TITLE
native package for Debian

### ISSUE THREAD

**Issue by efa** [vinegarhq/vinegar#472]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

On page: https://vinegarhq.org/Installation/guides/package.html
is not listed the native package for Debian

### Describe the Solution you'd Like

the availability of a native .deb package for Debian 12.
Can you please supply one together other like Arch, Fedora, Gentoo and Alpine?

### Describe Alternatives you've considered

installing a portable cross-distro package like AppImage, but is not available.
Flatpak minimum installation is over 1 GB, not comparable

**Comment by apprehensions** [comment]
Be the change you wish to see.
