### ISSUE TITLE
Immense lag with spawning items

### ISSUE THREAD

**Issue by Coder2195Text** [vinegarhq/vinegar#54]
https://discord.com/channels/1069506340973707304/1087385827354611772/1094736061177024513 On the discord server.

If you play an FPS like Flag Wars where ppl are spawning tons of bullets through machine guns, it lags tremendously.

**Comment by apprehensions** [comment]
Vinegar is the wrapper, it is not the software that is actually running Roblox. This is an issue with your wine installation, or Wine has been setup incorrectly; whether that be missing graphics libraries, using the wrong graphics card, using the wrong renderer, it can vary.

**Comment by Thelolguy1** [comment]
What wine, distro, specs?

**Comment by Coder2195Text** [comment]
> What wine, distro, specs?

Wine 8.0
Ubuntu 22.04.2 LTS running on x11

**Comment by apprehensions** [comment]
Fixed with latest versions of RCO
