### ISSUE TITLE
Feral gamemode under flatpak

### ISSUE THREAD

**Issue by nickname76** [vinegarhq/vinegar#55]
Please add support for using gamemoderun as a launcher option under flatpak distribution

**Comment by apprehensions** [comment]
Please know that gamemode shouldn't be effective under Flatpak, Flatpak is sandboxed, while gamemode needs access to the system.

Its reccomended to use source installation of Vinegar.

**Comment by nickname76** [comment]
Afaik gamemoderun is fully working out-of-the-box in steam flatpak, so i think it might be a good idea to just copy how gamemode works in it (don't ask me, I don't know how to configure flatpaks)

**Comment by Thelolguy1** [comment]
Noted, will investigate

**Comment by Thelolguy1** [comment]
@nickname76 https://github.com/flathub/io.github.vinegarhq.Vinegar/pull/13

Done, please add `launcher = "gamemoderun"` to your config to use gamemode.
