### ISSUE TITLE
I can't open Roblox Studio.

### ISSUE THREAD

**Issue by euqlidifier** [vinegarhq/vinegar#57]
Whenever I try to open Studio it closes automatically.

**Comment by apprehensions** [comment]
Please know that Studio on Linux isn't a very good process.
Are you on source or flatpak?
Try checking your logs, with `vinegar logs`.

**Comment by apprehensions** [comment]
Actually, seems that the latest versions of Studio has been completely broken on Wine...

**Comment by Thelolguy1** [comment]
Unfortunately, we cannot fix this issue at the moment as it depends on wine upstream.
