### ISSUE TITLE
Bad uninstall

### ISSUE THREAD

**Issue by Coder2195** [vinegarhq/vinegar#58]
When installing from source, files got put in /usr/bin/

![image](https://user-images.githubusercontent.com/63069499/233681212-42101a99-817b-4f13-8a2e-e41f2647a776.png)

When uninstalling, using make uninstall, it attempts to remove files in /usr/local/bin

![image](https://user-images.githubusercontent.com/63069499/233681300-693b90c9-39eb-4955-adf3-3efc72872fab.png)

**Comment by apprehensions** [comment]
You installed vinegar with `make PREFIX=/usr install`, which it tells the installation to install it onto /usr and not /usr/local. This isn't a bad uninstall, but a bad user as they forgot where and what the prefix meant.

**Comment by Coder2195Text** [comment]
> You installed vinegar with `make PREFIX=/usr install`, which it tells the installation to install it onto /usr and not /usr/local. This isn't a bad uninstall, but a bad user as they forgot where and what the prefix meant.

And btw it is bad practice to use `/usr` prefix

According to [this answer](https://unix.stackexchange.com/questions/8656/usr-bin-vs-usr-local-bin-on-linux)

> /usr/local/bin is for normal user programs not managed by the distribution package manager, e.g. locally compiled packages. You should not install them into /usr/bin because future distribution upgrades may modify or delete them without warning.

So I think the docs should be changed to fit this. This technically would become a bad install because a bad developer didn't know about good conventions

**Comment by apprehensions** [comment]
No.

**Comment by Coder2195Text** [comment]
Bad developers and sensitive discord mods choosing to not adhere to conventions? Alr not my problem I'm not using this crap anyways 
It gives me exit code 255 anyways

**Comment by Thelolguy1** [comment]
You do realize you aren't beholden to the docs right? You can realistically install it anywhere you want.

**Comment by echnobas** [comment]
oh ma gawd can you not literally do make PREFIX=/usr uninstall

**Comment by PetrifiedOak** [comment]
> oh ma gawd can you not literally do make PREFIX=/usr uninstall

you can, this guy is just malding
