### ISSUE TITLE
Changing renderer doesn't work

### ISSUE THREAD

**Issue by epic0421** [vinegarhq/vinegar#61]
When I put `renderer = "Vulkan"` in my config file, Roblox still launches with DXVK. There is no other lines in my file besides the documentation comments

**Comment by apprehensions** [comment]
Because DXVK needs D3D11, as it translates DirectX to Vulkan, and you're using Roblox's Vulkan.

**Comment by apprehensions** [comment]
So? OpenGL is [Roblox's] OpenGL, not DirectX.

**Comment by apprehensions** [comment]
Oh, sorry for misunderstanding. Yes, DXVK is enabled by default, just a question, did you edit with `vinegar edit`? If yes, I can add a warning to the user of having a different renderer when dxvk is enabled.
