### ISSUE TITLE
High CPU/GPU Present Times

### ISSUE THREAD

**Issue by zoe2276** [vinegarhq/vinegar#64]
I'm having an issue while running through vinegar where the CPU/GPU presentation time spikes up to the thousands of milliseconds, usually immediately following the Scheduler Render timing slowly creep up to around 100ms. I can watch my frames drop from 450 to around 17 throughout this process, before it will eventually return to normal. I was able to procure this screenshot from a recording I was taking to see the issue. I've been able to replicate this issue within every game I've played within Roblox (Phantom Forces, Bad Business, and a couple tycoon games). As time goes on, the frequency increases and, if I let it go long enough (usually about an hour), it will crash the client entirely while leaving Vinegar running in the background. I have to force close it from the system monitor to return to the game. 

![image](https://user-images.githubusercontent.com/56496871/235378749-d8af3f76-720d-4672-b566-f566007a6005.png)

Specs:

- Ubuntu 22.04 (specifically Kubuntu)
- Ryzen 7 5800X @ 4.7ghz
- 32gb DDR4 RAM @ 3600Mhz
- NVIDIA 2060 SUPER with graphics driver version 530.41.03.

Let me know if there is any additional information I can provide. I would love to add the logs but, if I'm honest, I have no idea where those are located.

**Comment by zoe2276** [comment]
Yes, I am. Sorry I should've included more info. Should I try building it from source? I haven't had any other issues with flatpaks but I'm open to anything at this point lol

**Comment by Thelolguy1** [comment]
You might have better luck building vinegar from source and using wine-tkg or wine-GE (see docs for more info). The flatpak itself uses stock wine 8.4 with staging patches.

**Comment by zoe2276** [comment]
Okay! I will try it out over a couple of days and see how it goes. I'll close it out if things get better (: Thanks for the help!

**Comment by zoe2276** [comment]
The spikes into the thousands are gone, however -- I'm watching less than 30% of my GPU total usage and less than 15% CPU, while still seeing frequent spikes from sub 1ms CPU timings (viewable from the Shift-F2 menu) up to ~20ms, split evenly between the Prepare/Present columns instead now. When this happens my frames drop from 250-300 all the way to 13-20. As stated before, the frequency of this increases until my game crashes entirely.

It seems as though this may be a different issue, as it's no longer an issue with the CPU/GPU presentation times... although the symptoms are very similar; almost identical, even. I'll try to play with some of the configuration settings and see what I can come up with. After compiling from source, I went ahead and added WINEESYNC to the environment variables via `vinegar edit` in the hopes I would see a change -- no luck. Any ideas of what flags I should specifically look for, or other Wine environment variables? I'm starting with changing the renderer from D3D11 and seeing what happens. 

What, am I gonna break it? 😉

**Comment by Thelolguy1** [comment]
I'd start with the renderer, Vulkan has been reported to be far better for some people.

**Comment by zoe2276** [comment]
Doesn't seem to be doing anything different; I'm not sure how accurate it is but every renderer I select just continues to show "D3D11" after the GPU timing. I spent so long trying to even build Vinegar from source (mostly because GnuTLS didn't recognize nettle 3.4.1 being installed... ever) and I'm not even sure I did that right, if I'm honest. 

Feel like I'm in way over my head here. If it's a Wine issue I'm pretty much out of luck in terms of ever fixing it. I'm just really not sure what more I can do, considering.

**Comment by Thelolguy1** [comment]
Try using wine-tkg

**Comment by zoe2276** [comment]
I didn't try hard enough when I was looking the first time -- I will report back (:

**Comment by zoe2276** [comment]
Whelp -- just built with the default-tkg and, while my fps was boosted by a bit on average, I was still getting the same drops corresponding with increased CPU time. I didn't let it play long enough to crash this time, though, as it's late and I need sleep.

I'll continue troubleshooting and check out wine-GE tomorrow. Thank you for all of your help thus far.

**Comment by Spas-Nikolaev-Dimitrov** [comment]
You could try using grapejuice's patched wine

**Comment by Thelolguy1** [comment]
Probably wouldn't make much of a difference; that is just wine-tkg.

**Comment by zoe2276** [comment]
Well, wine-tkg is certainly helping. Since I built it correctly, that is. I don't want to talk about how it removed all of my system drivers because I wasn't paying attention, so don't ask ):<

I'll call this resolved and, if it isn't, it's seeming to be more of a wine issue than a vinegar issue. Thanks again for all of your help.

For now, I guess I'll just cry because I'm getting the "Wine is not supported" error now 😭
