### ISSUE TITLE
Applying RCO flags failed

### ISSUE THREAD

**Issue by mr-sihc** [vinegarhq/vinegar#67]
```
2023/06/01 15:41:46 Applying RCO FFlags
2023/06/01 15:41:46 Downloading: https://raw.githubusercontent.com/L8X/Roblox-Client-Optimizer/main/ClientAppSettings.json
2023/06/01 15:41:46 failed to apply fflags: invalid character '#' looking for beginning of value
```

this is a simple fix, the moved from github to thier own website, so this is a simple replacement
\
\
just swap the \[ https://raw.githubusercontent.com/L8X/Roblox-Client-Optimizer/main/ClientAppSettings.json ]
with \[ https://roblox-client-optimizer.simulhost.com/ClientAppSettings.json ]

as it says on the old site (https://raw.githubusercontent.com/L8X/Roblox-Client-Optimizer/main/ClientAppSettings.json)

**Comment by mr-sihc** [comment]
ah didnt see the mr

**Comment by mr-sihc** [comment]
ah the mr doesnt fix the error, its something different

**Comment by apprehensions** [comment]
You are using an old version of Vinegar; where the latest will apply RCO without a link, and plus Roblox no longer runs on Wine.

**Comment by mr-sihc** [comment]
ohhhhhhh, man stable version are such a bad thing to be less stable than git version,
but thats the arch aur maintainers fault, ok!

**Comment by TheComputerGuy96** [comment]
@mr-sihc I'll update the `vinegar` AUR package as soon as a new tagged release is available (but for now I'll put a comment telling people to use `vinegar-git` instead)

**Comment by mr-sihc** [comment]
nice!
So it IS the fault of vinegar

**Comment by pizzaboxer** [comment]
bruh
