### ISSUE TITLE
Allow launcher aurguments

### ISSUE THREAD

**Issue by beanietechie** [vinegarhq/vinegar#72]
As it is now, the `launcher` option only accepts an executable, whether an absolute path or a file in `$PATH`, without arguments. I believe allowing launcher arguments would be a great addition since it would enable use of Feral GameMode alongside Gamescope (for FidelityFX FSR or what have you). I would love to see a similar syntax to Steam's per-game launch options.

**Comment by beanietechie** [comment]
nvm i'm dumb

**Comment by beanietechie** [comment]
wait no i'm not it still doesn't work

**Comment by apprehensions** [comment]
Why was this closed? Vinegar indeed doesn't support more than one launcher argument at a time.

**Comment by apprehensions** [comment]
fixed by 787d8974c9729a7d341260a5a43df99282b9013e
