### ISSUE TITLE
Serious problem with RobloxPlayerBeta.exe

### ISSUE THREAD

**Issue by Ollix27** [vinegarhq/vinegar#80]
This is the info that was shown to me after i clicked "Show details"
0x000001411a6a7d: mov (%r10), %rax
Modules:
Module	Address					Debug info	Name (104 modules)
PE	0000000005a30000-0000000005a5f000	Deferred        webview2loader
PE	0000000005a70000-0000000005a87000	Deferred        dnsapi
PE	000000007a800000-000000007a909000	Deferred        opengl32
PE	000000007b000000-000000007b29f000	Deferred        kernelbase
PE	000000007b600000-000000007b65f000	Deferred        kernel32
ELF	000000007d000000-000000007d005000	Deferred        <wine-loader>
PE	0000000170000000-00000001700a8000	Deferred        robloxplayerbeta
PE	0000000180000000-0000000182820000	Deferred        robloxplayerbeta
PE	00000001ccdd0000-00000001cce02000	Deferred        rsaenh
PE	00000001cd620000-00000001cd632000	Deferred        aclui
PE	00000001ce760000-00000001ce76e000	Deferred        kerberos
PE	00000001d0e20000-00000001d0f5e000	Deferred        oleaut32
PE	00000001d8c90000-00000001d8cd3000	Deferred        advapi32
PE	00000001de160000-00000001de203000	Deferred        urlmon
PE	00000001eaf60000-00000001eaf8a000	Deferred        sechost
PE	00000001f8340000-00000001f835c000	Deferred        cryptnet
PE	00000001ffb10000-00000001ffb22000	Deferred        rtworkq
PE	000000020b860000-000000020b981000	Deferred        ole32
PE	00000002169d0000-0000000216b7d000	Deferred        user32
PE	0000000218320000-000000021834a000	Deferred        msdmo
PE	0000000228280000-000000022831b000	Deferred        msvcrt
PE	000000023bc00000-000000023c54f000	Deferred        shell32
PE	000000023ecb0000-000000023ed25000	Deferred        dbghelp
PE	00000002445a0000-00000002445b0000	Deferred        ncrypt
PE	0000000250cd0000-0000000250cef000	Deferred        mpr
PE	0000000251d80000-0000000251db2000	Deferred        winex11
PE	000000025dc30000-000000025dc3e000	Deferred        version
PE	00000002604a0000-00000002604b0000	Deferred        imagehlp
PE	0000000263650000-0000000263684000	Deferred        propsys
PE	0000000267930000-000000026793b000	Deferred        psapi
PE	000000026c190000-000000026c19c000	Deferred        nsi
PE	000000026c230000-000000026c266000	Deferred        uxtheme
PE	0000000284ea0000-0000000284ead000	Deferred        powrprof
PE	00000002945e0000-00000002946a4000	Deferred        winmm
PE	00000002964d0000-00000002965a3000	Deferred        crypt32
PE	00000002a2380000-00000002a23dc000	Deferred        shlwapi
PE	00000002bb0a0000-00000002bb121000	Deferred        gdi32
PE	00000002bde30000-00000002bde4b000	Deferred        shcore
PE	00000002c73a0000-00000002c73d9000	Deferred        win32u
PE	00000002c7470000-00000002c7536000	Deferred        ucrtbase
PE	00000002ee630000-00000002ee647000	Deferred        bcrypt
PE	00000002fb3c0000-00000002fb50c000	Deferred        comctl32
PE	000000031b430000-000000031b43b000	Deferred        cryptsp
PE	000000031c5d0000-000000031c62d000	Deferred        combase
PE	0000000345640000-00000003456c3000	Deferred        wininet
PE	0000000351a60000-0000000351a80000	Deferred        msacm32
PE	0000000359d40000-0000000359d4c000	Deferred        sensapi
PE	0000000368420000-00000003684ab000	Deferred        rpcrt4
PE	000000036d860000-000000036d8e0000	Deferred        setupapi
PE	0000000370f70000-0000000370f98000	Deferred        ws2_32
PE	0000000393730000-000000039374c000	Deferred        imm32
PE	00000003982d0000-0000000398307000	Deferred        iphlpapi
PE	00000003afef0000-00000003aff11000	Deferred        secur32
PE	00000003bb450000-00000003bb4b6000	Deferred        mfplat
ELF	00007fefc737b000-00007fefc739e000	Deferred        libnss_resolve.so.2
ELF	00007fefc73be000-00007fefc73c3000	Deferred        kerberos.so
ELF	00007fefc73c3000-00007fefc7501000	Deferred        opengl32.so
ELF	00007fefc7501000-00007fefc7515000	Deferred        libresolv.so.2
ELF	00007fefc7519000-00007fefc7525000	Deferred        secur32.so
ELF	00007fefc7549000-00007fefc7551000	Deferred        libxfixes.so.3
ELF	00007fefc7551000-00007fefc755e000	Deferred        libxcursor.so.1
ELF	00007fefc755e000-00007fefc7572000	Deferred        libxi.so.6
ELF	00007fefc7572000-00007fefc7577000	Deferred        libxcomposite.so.1
ELF	00007fefc7577000-00007fefc7584000	Deferred        libxrandr.so.2
ELF	00007fefc7584000-00007fefc7591000	Deferred        libxrender.so.1
ELF	00007fefc7591000-00007fefc7598000	Deferred        libxxf86vm.so.1
ELF	00007fefc7598000-00007fefc759d000	Deferred        libxinerama.so.1
ELF	00007fefc759d000-00007fefc75c9000	Deferred        libxcb.so.1
ELF	00007fefc75c9000-00007fefc7711000	Deferred        libx11.so.6
ELF	00007fefc7711000-00007fefc7725000	Deferred        libxext.so.6
ELF	00007fefc7729000-00007fefc772e000	Deferred        dnsapi.so
ELF	00007fefc772e000-00007fefc7735000	Deferred        ws2_32.so
ELF	00007fefc7735000-00007fefc77c8000	Deferred        winex11.so
ELF	00007fefc77c8000-00007fefc77d8000	Deferred        libffi.so.8
ELF	00007fefc77d8000-00007fefc7856000	Deferred        libgmp.so.10
ELF	00007fefc7856000-00007fefc78a1000	Deferred        libhogweed.so.6
ELF	00007fefc78a1000-00007fefc78f2000	Deferred        libnettle.so.8
ELF	00007fefc78f2000-00007fefc7908000	Deferred        libtasn1.so.6
ELF	00007fefc7908000-00007fefc7ac1000	Deferred        libunistring.so.2
ELF	00007fefc7ac1000-00007fefc7b15000	Deferred        libidn2.so.0
ELF	00007fefc7b15000-00007fefc7c4f000	Deferred        libp11-kit.so.0
ELF	00007fefc7c4f000-00007fefc7e6c000	Deferred        libgnutls.so.30
ELF	00007fefc7e6f000-00007fefc7e75000	Deferred        libxau.so.6
ELF	00007fefc7e75000-00007fefc7e7c000	Deferred        crypt32.so
ELF	00007fefc7e7c000-00007fefc7e88000	Deferred        bcrypt.so
ELF	00007fefc80ae000-00007fefc80db000	Deferred        libexpat.so.1
ELF	00007fefc80db000-00007fefc8129000	Deferred        libfontconfig.so.1
ELF	00007fefc8129000-00007fefc8171000	Deferred        libpcre.so.1
ELF	00007fefc8171000-00007fefc8194000	Deferred        libbrotlicommon.so.1
ELF	00007fefc8194000-00007fefc81b8000	Deferred        libgraphite2.so.3
ELF	00007fefc81b8000-00007fefc82f1000	Deferred        libglib-2.0.so.0
ELF	00007fefc82f1000-00007fefc82fe000	Deferred        libbrotlidec.so.1
ELF	00007fefc82fe000-00007fefc8407000	Deferred        libharfbuzz.so.0
ELF	00007fefc8407000-00007fefc8441000	Deferred        libpng16.so.16
ELF	00007fefc8441000-00007fefc8455000	Deferred        libbz2.so.1
ELF	00007fefc8455000-00007fefc8516000	Deferred        libfreetype.so.6
ELF	00007fefc8526000-00007fefc86e4000	Deferred        win32u.so
ELF	00007fefc8cb5000-00007fefc8cd0000	Deferred        libz.so.1
ELF	00007fefc8cd0000-00007fefc8cfa000	Deferred        liblzma.so.5
ELF	00007fefc8cfa000-00007fefc8d1b000	Deferred        libgcc_s.so.1
ELF	00007fefc8d1b000-00007fefc8dfe000	Deferred        libm.so.6
ELF	00007fefc8dfe000-00007fefc8e19000	Deferred        libunwind.so.8
ELF	00007fefc8e19000-00007fefc8f01000	Dwarf           ntdll.so
ELF	00007fefc9124000-00007fefc915d000	Deferred        ld-linux-x86-64.so.2
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 start.exe
	00000024    0     
00000038 services.exe
	["C:\windows\system32\services.exe"]
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	0000004c    0     wine_rpcrt4_io
	00000050    0     wine_threadpool_worker
	00000070    0     wine_rpcrt4_io
	0000007c    0     wine_rpcrt4_io
	0000009c    0     wine_rpcrt4_io
	000000b4    0     wine_rpcrt4_io
	000000c4    0     
	000000e4    0     wine_rpcrt4_io
	000000e8    0     wine_threadpool_worker
00000044 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000048    0     
	00000054    0     
	00000058    0     wine_sechost_service
	0000005c    0     
	00000060    0     
	000000c0    0     
00000068 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	0000006c    0     
	00000074    0     
	00000078    0     wine_sechost_service
	00000080    0     
	00000084    0     
	00000088    0     
	00000094    0     
	00000098    0     
0000008c plugplay.exe
	[C:\windows\system32\plugplay.exe]
	00000090    0     
	000000a0    0     
	000000a4    0     wine_sechost_service
	000000a8    0     wine_rpcrt4_server
000000ac svchost.exe
	[C:\windows\system32\svchost.exe -k LocalServiceNetworkRestricted]
	000000b0    0     
	000000b8    0     
	000000bc    0     wine_sechost_service
000000c8 explorer.exe
	["C:\windows\system32\explorer.exe" /desktop]
	000000cc    0     
	000000d0    0     
	000000d4    0     wine_rpcrt4_server
000000dc rpcss.exe
	[C:\windows\system32\rpcss.exe]
	000000e0    0     
	000000ec    0     
	000000f0    0     wine_sechost_service
	000000f4    0     wine_rpcrt4_server
	000000f8    0     wine_rpcrt4_server
	000000fc    0     wine_rpcrt4_io
	00000100    0     wine_threadpool_worker
	00000198    0     wine_rpcrt4_io
00000104 (D) Z:\home\ollix27\.var\app\io.github.vinegarhq.Vinegar\data\vinegar\prefix\vinegar\versions\version-9fafbcb7814046ec\RobloxPlayerBeta.exe
	["Z:\home\ollix27\.var\app\io.github.vinegarhq.Vinegar\data\vinegar\prefix\vinegar\versions\version-9fafbcb7814046ec\RobloxPlayerBeta.exe" -app]
	00000108    0     
	0000010c    0     
	00000110    0     
	00000114    0     
	00000118    0     
	0000011c    0     
	00000120   15     
	00000128    0     
	00000130    0     
	00000134    0 <== 
	00000138    0     
	0000013c    0     
	00000140    0     
	00000144    0     
	00000148    0     
	0000014c    0     
	00000150    0     
	00000154    0     
	00000158    0     
	0000015c    0     
	00000160    0     
	00000164    0     
	00000168    0     
	0000016c    0     
	00000170    0     
	00000174    0     
	00000178    0     
	00000184    0     
00000188 explorer.exe
	["C:\windows\system32\explorer.exe" /desktop]
	0000018c    0     
	00000190    0     
	00000194    0     wine_rpcrt4_server
System information:
    Wine build: v8.5 (Staging)
    Platform: x86_64
    Version: Windows 10
    Host system: Linux
    Host version: 5.15.0-79-generic

**Comment by Thelolguy1** [comment]
Considering you have webview2 as the last module and you launched Roblox Player with -app, I am guessing you tried to open a login screen or Roblox browser window. At the moment, Wine has no support for these features and may crash.

**Comment by Thelolguy1** [comment]
See #32

**Comment by Ollix27** [comment]
Solved by switching channel to zlivem
