### ISSUE TITLE
Server selection screen not working

### ISSUE THREAD

**Issue by stacode123** [vinegarhq/vinegar#84]
https://github.com/vinegarhq/vinegar/assets/49679054/dd25714e-82e6-4ce1-ab7b-ba7268e07408

Sound got destroyed somehow after convert

**Comment by stacode123** [comment]
IS this with the embedded website issue?

**Comment by TheComputerGuy96** [comment]
@stacode123 This is definitely a duplicate of #32 (you need some weird stuff for that feature to work because I tried fixing this issue)

**Comment by stacode123** [comment]
Ok thanks closing
